'use client';
import {useEffect,useState} from 'react';
import {db} from '@/lib/supabase';
import {freshSheet,sheetSchema,type Sheet} from '@/lib/model';
import type {Entry} from '@/lib/catalog';
import SheetEditor from './sheet-editor';
type Row={id:string;data:Sheet;revision:number};
export default function Onix(){
 const [role,setRole]=useState(''),[catalog,setCatalog]=useState<Entry[]>([]),[members,setMembers]=useState<{email:string;role:string}[]>([]);
 const [user,setUser]=useState(''),[ready,setReady]=useState(false),[rows,setRows]=useState<Row[]>([]),[active,setActive]=useState<Row|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[mode,setMode]=useState('login');
 async function load(){if(!db)return;const me=await db.auth.getUser();if(!me.data.user)return;const access=await db.from('members').select('role').eq('email',me.data.user.email!.toLowerCase()).maybeSingle();if(access.error)throw access.error;setRole(access.data?.role||'');if(!access.data){setCatalog([]);setRows([]);return;}const books=await db.from('catalog').select('data').limit(1000);if(books.error)throw books.error;setCatalog((books.data||[]).map(x=>x.data));if(access.data.role==='master'){const m=await db.from('members').select('email,role').order('email');if(m.error)throw m.error;setMembers(m.data||[]);}const {data,error}=await db.from('characters').select('id,data,revision').order('updated_at',{ascending:false});if(error)throw error;setRows((data||[]).map(r=>({...r,data:sheetSchema.parse(r.data)})));}
 const report=(e:unknown)=>setMessage(e instanceof Error?e.message:'Não foi possível concluir a operação.');
 useEffect(()=>{if(!db){setReady(true);return;}db.auth.getSession().then(({data,error})=>{if(error)report(error);setUser(data.session?.user.email||'');setReady(true);if(data.session)load().catch(report);});const {data}=db.auth.onAuthStateChange((event,session)=>{setUser(session?.user.email||'');if(event==='PASSWORD_RECOVERY')setMode('reset');if(event==='SIGNED_OUT'){setActive(null);setRows([]);setDirty(false);setRole('');setCatalog([]);setMembers([]);}if(event==='SIGNED_IN')setTimeout(()=>load().catch(report),0);});return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
 async function auth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!db)return;setBusy(true);setMessage('');const f=new FormData(e.currentTarget),email=String(f.get('email')||''),password=String(f.get('password')||'');try{const r=mode==='register'?await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):mode==='forgot'?await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin}):mode==='reset'?await db.auth.updateUser({password}):await db.auth.signInWithPassword({email,password});if(r.error)throw r.error;setMessage(mode==='register'?'Confira seu e-mail para confirmar o cadastro.':mode==='forgot'?'Se a conta existir, você receberá um link por e-mail.':mode==='reset'?'Senha atualizada.':'');if(mode==='reset')setMode('login');}catch(e){report(e);}finally{setBusy(false);}}
 function leave(){return !dirty||confirm('Descartar alterações não salvas?');}
 async function create(data=freshSheet()){if(!db||!leave())return;setBusy(true);try{const r=await db.from('characters').insert({data:sheetSchema.parse(data)}).select('id,data,revision').single();if(r.error)throw r.error;setActive(r.data);setDirty(false);await load();}catch(e){report(e);}finally{setBusy(false);}}
 async function save(){if(!db||!active)return;setBusy(true);try{const parsed=sheetSchema.parse(active.data);const r=await db.from('characters').update({data:parsed,revision:active.revision+1,updated_at:new Date().toISOString()}).eq('id',active.id).eq('revision',active.revision).select('id,data,revision').single();if(r.error)throw Error('Não foi possível salvar. Se outra janela alterou a ficha, exporte sua cópia antes de recarregar.');setActive(r.data);setDirty(false);setMessage('Ficha salva.');await load();}catch(e){report(e);}finally{setBusy(false);}}
 function download(){if(!active)return;const url=URL.createObjectURL(new Blob([JSON.stringify(active.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ficha-onix.json';a.click();URL.revokeObjectURL(url);}
 if(!ready)return <main className="auth"><p>Carregando…</p></main>;
 if(!user||mode==='reset')return <main className="auth"><div className="brand">◈ ONIX <small>SISTEMA DE FICHAS</small></div><section><p className="eyebrow">SEU PRÓXIMO CAPÍTULO</p><h1>Sobreviva.<br/>Deixe sua marca.</h1><p>Suas fichas, equipamentos e segredos em um só lugar.</p>{!db?<p role="status">A plataforma está aguardando a configuração do servidor para liberar o cadastro.</p>:<form onSubmit={auth}><h2>{({login:'Entrar',register:'Criar conta',forgot:'Recuperar acesso',reset:'Nova senha'} as Record<string,string>)[mode]}</h2>{mode!=='reset'&&<label>E-mail<input name="email" type="email" required autoComplete="email"/></label>}{mode!=='forgot'&&<label>Senha<input name="password" type="password" minLength={8} required autoComplete={mode==='login'?'current-password':'new-password'}/></label>}<button className="primary" disabled={busy}>{busy?'Aguarde…':'Continuar'}</button><div className="authlinks"><button type="button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Criar conta':'Voltar para entrar'}</button>{mode==='login'&&<button type="button" onClick={()=>setMode('forgot')}>Esqueci minha senha</button>}</div></form>}<p role="status">{message}</p></section></main>;
 if(!role)return <main className="auth"><div className="brand">◈ ONIX</div><section><h1>Acesso restrito</h1><p>Sua conta precisa ser autorizada pelo mestre para abrir as fichas.</p><p role="status">{message}</p><button onClick={()=>load().catch(report)}>Verificar autorização</button><button onClick={()=>db!.auth.signOut()}>Sair</button></section></main>;
 return <><header><a className="brand" href="/" onClick={e=>{if(!leave())e.preventDefault();}}>◈ ONIX</a><span>Minhas fichas</span><div className="account">{user}<button onClick={async()=>{if(leave()){const r=await db!.auth.signOut();if(r.error)report(r.error);}}}>Sair</button></div></header><main className="workspace">{role==='master'&&<details><summary>Gerenciar acesso dos jogadores</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const email=String(f.get('email')).trim().toLowerCase();const r=await db!.from('members').upsert({email,role:'player'});if(r.error)report(r.error);else{setMessage('Jogador autorizado. Ele já pode criar sua conta.');await load().catch(report);}}}><label>E-mail do jogador<input name="email" type="email" required/></label><button>Autorizar jogador</button></form>{members.map(m=><p key={m.email}>{m.email} · {m.role}{m.role==='player'&&<button onClick={async()=>{if(!confirm('Revogar acesso deste jogador?'))return;const r=await db!.from('members').delete().eq('email',m.email);if(r.error)report(r.error);else await load().catch(report);}}>Revogar</button>}</p>)}</details>}<div className="toolbar"><select aria-label="Selecionar ficha" value={active?.id||''} onChange={e=>{if(leave()){setActive(rows.find(r=>r.id===e.target.value)||null);setDirty(false);}}}><option value="">Selecione uma ficha</option>{rows.map(r=><option key={r.id} value={r.id}>{r.data.name}</option>)}</select><button disabled={busy} onClick={()=>create()}>+ Nova ficha</button><label className="import">Importar<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];try{if(f){if(f.size>2000000)throw Error('Arquivo muito grande.');await create(sheetSchema.parse(JSON.parse(await f.text())));}}catch(err){report(err);}e.target.value='';}}/></label>{active&&<><button onClick={download}>Exportar</button><button className="primary" disabled={busy||!dirty} onClick={save}>{busy?'Salvando…':dirty?'Salvar alterações':'Salvo'}</button></>}</div>{message&&<div className="notice" role="status">{message}<button aria-label="Fechar aviso" onClick={()=>setMessage('')}>×</button></div>}{active?<SheetEditor isMaster={role==='master'} catalog={catalog} sheet={active.data} onChange={data=>{setActive({...active,data});setDirty(true);}} onDelete={async()=>{if(!confirm('Excluir esta ficha permanentemente?'))return;const r=await db!.from('characters').delete().eq('id',active.id);if(r.error)report(r.error);else{setActive(null);setDirty(false);await load().catch(report);}}}/>:<section className="empty"><p className="eyebrow">ARQUIVO DE SOBREVIVENTES</p><h1>Quem enfrenta o próximo dia?</h1><p>Crie sua primeira ficha ou selecione um personagem acima.</p><button className="primary" disabled={busy} onClick={()=>create()}>Criar personagem</button></section>}</main></>;
}
