-- ADUNATIO // PROTOCOLO PANI // EVENTOS DE CONTENCAO ANOMALA v1.1
-- Estado sincronizado, votos, reconexao e corrupcao secreta do Mestre.

create schema if not exists pani_private;
revoke all on schema pani_private from public, anon, authenticated;

create table if not exists pani_private.containment_session (
  session_id text primary key,
  join_code text,
  state jsonb not null default '{}'::jsonb,
  secret_state jsonb not null default '{}'::jsonb,
  revision bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists pani_private.containment_participant (
  session_id text not null references pani_private.containment_session(session_id) on delete cascade,
  crew_id text not null references public.crew_access(crew_id) on delete cascade,
  joined boolean not null default true,
  joined_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  hold_until timestamptz,
  primary key (session_id, crew_id)
);

create table if not exists pani_private.containment_vote (
  session_id text not null references pani_private.containment_session(session_id) on delete cascade,
  event_id text not null,
  phase_key text not null,
  crew_id text not null references public.crew_access(crew_id) on delete cascade,
  value text not null check (char_length(value) between 1 and 40),
  updated_at timestamptz not null default now(),
  primary key (session_id, event_id, phase_key, crew_id)
);

create table if not exists pani_private.containment_log (
  id bigint generated by default as identity primary key,
  session_id text not null,
  actor text not null,
  event_type text not null,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists containment_participant_presence_idx
  on pani_private.containment_participant(session_id, joined, last_seen desc);
create index if not exists containment_participant_crew_idx
  on pani_private.containment_participant(crew_id);
create index if not exists containment_vote_phase_idx
  on pani_private.containment_vote(session_id, event_id, phase_key, updated_at desc);
create index if not exists containment_vote_crew_idx
  on pani_private.containment_vote(crew_id);
create index if not exists containment_log_session_idx
  on pani_private.containment_log(session_id, created_at desc);

alter table pani_private.containment_session enable row level security;
alter table pani_private.containment_participant enable row level security;
alter table pani_private.containment_vote enable row level security;
alter table pani_private.containment_log enable row level security;
revoke all on all tables in schema pani_private from public, anon, authenticated;
revoke all on all sequences in schema pani_private from public, anon, authenticated;

create or replace function pani_private.containment_default_state()
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'protocol_version', 'containment_v1_1',
    'released', false,
    'status', 'dormant',
    'active_event', null,
    'saturation', 0,
    'modules_restored', '[]'::jsonb,
    'event_status', jsonb_build_object(
      'knowledge', 'detected', 'energy', 'detected',
      'blood', 'detected', 'death', 'detected'),
    'representative_id', null,
    'witness_id', null,
    'corruption_charges', 2,
    'pani_charges', jsonb_build_object('scan', 1, 'lock', 1),
    'paused', false,
    'timer_end', null,
    'timer_remaining', null,
    'glitch', jsonb_build_object('revision', 0, 'duration_ms', 0, 'at', null),
    'announcement', null,
    'announcement_revision', 0,
    'residue_status', 'locked',
    'event', '{}'::jsonb
  );
$$;

create or replace function pani_private.containment_default_secret()
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'knowledge', '{}'::jsonb,
    'energy', '{}'::jsonb,
    'blood', '{}'::jsonb,
    'death', '{}'::jsonb,
    'corruption', null,
    'corruption_backup', null
  );
$$;

create or replace function pani_private.containment_log_event(
  p_session text, p_actor text, p_event text, p_detail text default null)
returns void
language sql
volatile
set search_path = ''
as $$
  insert into pani_private.containment_log(session_id, actor, event_type, detail)
  values (p_session, left(coalesce(p_actor, 'PANI'), 120), left(coalesce(p_event, 'event'), 120), left(p_detail, 1200));
$$;

create or replace function pani_private.containment_vote_summary(
  p_session text, p_event text, p_phase text)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select coalesce(jsonb_object_agg(q.value, q.total), '{}'::jsonb)
  from (
    select v.value, count(*)::int as total
    from pani_private.containment_vote v
    where v.session_id = p_session and v.event_id = p_event and v.phase_key = p_phase
    group by v.value order by v.value
  ) q;
$$;

create or replace function pani_private.containment_knowledge_line(
  p_marks jsonb, p_size integer, p_mark text)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare r integer; c integer; needed integer := 3;
begin
  if p_size not between 3 and 4 or p_mark not in ('X','O') then return false; end if;
  for r in 0..p_size-1 loop
    for c in 0..p_size-needed loop
      if p_marks->>('c'||(r*p_size+c)) = p_mark
         and p_marks->>('c'||(r*p_size+c+1)) = p_mark
         and p_marks->>('c'||(r*p_size+c+2)) = p_mark then return true; end if;
    end loop;
  end loop;
  for c in 0..p_size-1 loop
    for r in 0..p_size-needed loop
      if p_marks->>('c'||(r*p_size+c)) = p_mark
         and p_marks->>('c'||((r+1)*p_size+c)) = p_mark
         and p_marks->>('c'||((r+2)*p_size+c)) = p_mark then return true; end if;
    end loop;
  end loop;
  for r in 0..p_size-needed loop
    for c in 0..p_size-needed loop
      if p_marks->>('c'||(r*p_size+c)) = p_mark
         and p_marks->>('c'||((r+1)*p_size+c+1)) = p_mark
         and p_marks->>('c'||((r+2)*p_size+c+2)) = p_mark then return true; end if;
    end loop;
    for c in 2..p_size-1 loop
      if p_marks->>('c'||(r*p_size+c)) = p_mark
         and p_marks->>('c'||((r+1)*p_size+c-1)) = p_mark
         and p_marks->>('c'||((r+2)*p_size+c-2)) = p_mark then return true; end if;
    end loop;
  end loop;
  return false;
end;
$$;

create or replace function pani_private.containment_blood_case(p_beat integer)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select case ((greatest(p_beat,1)-1) % 6)+1
    when 1 then jsonb_build_object('answer','B','readings',jsonb_build_array(
      'A pressão não tolera o fluxo máximo.','B mantém pressão e coagulação compatíveis.','C eleva a temperatura acima do limite.'))
    when 2 then jsonb_build_object('answer','C','readings',jsonb_build_array(
      'A pulsa mais rápido do que a leitura segura.','B coagula antes de completar o circuito.','C é a única válvula com fluxo menor que a pressão.'))
    when 3 then jsonb_build_object('answer','A','readings',jsonb_build_array(
      'A não apresenta o marcador vermelho.','B e C compartilham a mesma falha de temperatura.','Exatamente uma leitura permanece estável.'))
    when 4 then jsonb_build_object('answer','B','readings',jsonb_build_array(
      'A afirma que C é segura.','B contradiz A sem exceder o pulso.','C afirma que A e B são inseguras.'))
    when 5 then jsonb_build_object('answer','C','readings',jsonb_build_array(
      'A: pressão 7 / fluxo 9.','B: pressão 4 / fluxo 4.','C: pressão 6 / fluxo 5.'))
    else jsonb_build_object('answer','A','readings',jsonb_build_array(
      'A estabiliza quando o pulso cai.','B exige duas leituras idênticas, mas elas divergem.','C inverte pressão e coagulação.'))
  end;
$$;

create or replace function pani_private.containment_death_case(p_cycle integer, p_anchor text default null)
returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare answer text; fallback text; kind text;
begin
  case greatest(1, least(4, p_cycle))
    when 1 then answer := 'clock'; fallback := 'lamp'; kind := 'obvious';
    when 2 then answer := 'sample'; fallback := 'chair'; kind := 'two_suspects';
    when 3 then answer := 'door'; fallback := 'mirror'; kind := 'order';
    else answer := 'mirror'; fallback := 'lamp'; kind := 'temporal';
  end case;
  if answer = p_anchor then answer := fallback; end if;
  return jsonb_build_object(
    'answer', answer,
    'public', jsonb_build_object(
      'scene_kind', kind,
      'changed_visuals', jsonb_build_array(answer),
      'missing_object', null,
      'memory_overlay', false
    )
  );
end;
$$;

create or replace function pani_private.containment_capture(p_state jsonb, p_event text)
returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare st jsonb := p_state; mods jsonb; statuses jsonb; n integer; sat integer;
begin
  mods := coalesce(st->'modules_restored','[]'::jsonb);
  if not mods @> jsonb_build_array(p_event) then mods := mods || jsonb_build_array(p_event); end if;
  statuses := jsonb_set(coalesce(st->'event_status','{}'::jsonb), array[p_event], '"contained"'::jsonb, true);
  n := jsonb_array_length(mods);
  sat := greatest(0, coalesce((st->>'saturation')::int,0)-1);
  st := st || jsonb_build_object(
    'modules_restored', mods,
    'event_status', statuses,
    'active_event', null,
    'status', case when n = 4 then 'contained' else 'lobby' end,
    'representative_id', null,
    'witness_id', null,
    'paused', false,
    'timer_end', null,
    'timer_remaining', null,
    'saturation', sat,
    'event', '{}'::jsonb,
    'residue_status', case when n = 4 then 'available' else coalesce(st->>'residue_status','locked') end,
    'announcement', case when n = 4
      then 'QUATRO ASSINATURAS RECAPTURADAS. VARREDURA LIMPA DISPONÍVEL.'
      else 'ASSINATURA RECAPTURADA. MÓDULO PANI RESTAURADO.' end,
    'announcement_revision', coalesce((st->>'announcement_revision')::int,0)+1
  );
  return st;
end;
$$;

create or replace function pani_private.containment_tick(p_session text)
returns void
language plpgsql
volatile
set search_path = ''
as $$
declare s pani_private.containment_session%rowtype; st jsonb; sec jsonb; ev jsonb;
  beat integer; stab integer; hemo integer; picked text; answer text; nxt jsonb;
begin
  select * into s from pani_private.containment_session where session_id=p_session for update;
  if s.session_id is null then return; end if;
  st := s.state; sec := s.secret_state;
  if st->>'active_event' <> 'blood' or coalesce((st->>'paused')::boolean,false)
     or st->>'timer_end' is null or (st->>'timer_end')::timestamptz > now()
     or st#>>'{event,phase}' <> 'beats' then return; end if;

  ev := st->'event'; beat := coalesce((ev->>'beat')::int,1);
  stab := coalesce((ev->>'stabilization')::int,0); hemo := coalesce((ev->>'hemorrhage')::int,0);
  picked := ev->>'selected_valve'; answer := sec#>>'{blood,answer}';
  if picked = answer then stab := stab + 1; else hemo := hemo + 1; end if;
  if hemo >= 3 then
    stab := 2; hemo := 0;
    st := jsonb_set(st,'{saturation}',to_jsonb(least(8,coalesce((st->>'saturation')::int,0)+1)));
    st := st || jsonb_build_object('announcement','HEMORRAGIA CRÍTICA. RETORNO AO PATAMAR 2/4.','announcement_revision',coalesce((st->>'announcement_revision')::int,0)+1);
  end if;
  if stab >= 4 then
    ev := ev || jsonb_build_object('phase','final','stabilization',4,'hemorrhage',hemo,'selected_valve',null,'representative_ready',false,'vote_phase','blood:seals');
    st := st || jsonb_build_object('event',ev,'timer_end',null,'timer_remaining',null);
  else
    beat := beat + 1; nxt := pani_private.containment_blood_case(beat);
    ev := ev || jsonb_build_object('beat',beat,'stabilization',stab,'hemorrhage',hemo,
      'readings',nxt->'readings','selected_valve',null,'vote_phase','blood:beat'||beat,
      'one_may_lie',false);
    sec := jsonb_set(sec,'{blood}',jsonb_build_object('beat_index',beat,'answer',nxt->>'answer','fake_votes',null),true);
    st := st || jsonb_build_object('event',ev,'timer_end',(now()+make_interval(secs=>coalesce((ev->>'beat_seconds')::int,15)))::text);
  end if;
  update pani_private.containment_session set state=st,secret_state=sec,revision=revision+1,updated_at=now() where session_id=p_session;
  perform pani_private.containment_log_event(p_session,'PANI','blood_beat_resolved','beat='||beat||';picked='||coalesce(picked,'none'));
end;
$$;

insert into pani_private.containment_session(session_id, state, secret_state)
values ('W77-01', pani_private.containment_default_state(), pani_private.containment_default_secret())
on conflict (session_id) do nothing;

create or replace function public.pani_containment_crew_state(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare c public.crew_access%rowtype; s pani_private.containment_session%rowtype;
  joined boolean := false; players jsonb := '[]'::jsonb; phase text; active_event text;
  summary jsonb := '{}'::jsonb; my_vote text; role_name text := 'spectator';
begin
  select * into c from public.crew_access
  where token_hash=encode(extensions.digest(p_token,'sha256'),'hex');
  if c.crew_id is null then raise exception 'unauthorized'; end if;
  perform pani_private.containment_tick('W77-01');
  select * into s from pani_private.containment_session where session_id='W77-01';
  select coalesce(p.joined,false) into joined from pani_private.containment_participant p
    where p.session_id='W77-01' and p.crew_id=c.crew_id;
  if joined then
    update pani_private.containment_participant set last_seen=now()
      where session_id='W77-01' and crew_id=c.crew_id;
  end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'crew_id',p.crew_id,'display_name',ca.display_name,'module',ca.module,
    'connected',p.last_seen > now()-interval '12 seconds','last_seen',p.last_seen)
    order by ca.display_name),'[]'::jsonb) into players
  from pani_private.containment_participant p join public.crew_access ca on ca.crew_id=p.crew_id
  where p.session_id='W77-01' and p.joined;

  active_event := s.state->>'active_event'; phase := s.state#>>'{event,vote_phase}';
  if c.crew_id = s.state->>'representative_id' then role_name := 'representative'; end if;
  if c.crew_id = s.state->>'witness_id' then role_name := 'witness'; end if;
  if active_event is not null and phase is not null then
    select v.value into my_vote from pani_private.containment_vote v
      where v.session_id='W77-01' and v.event_id=active_event and v.phase_key=phase and v.crew_id=c.crew_id;
    if (active_event='death' and role_name='witness') or (active_event in ('energy','blood') and role_name='representative') then
      summary := pani_private.containment_vote_summary('W77-01',active_event,phase);
      if active_event='blood' and role_name='representative' and s.secret_state#>'{blood,fake_votes}' is not null
         and s.secret_state#>'{blood,fake_votes}' <> 'null'::jsonb then
        summary := s.secret_state#>'{blood,fake_votes}';
      end if;
    end if;
  end if;
  return jsonb_build_object(
    'session_id','W77-01','released',coalesce((s.state->>'released')::boolean,false),
    'joined',joined,'state',s.state,'revision',s.revision,'server_time',now(),
    'player',jsonb_build_object('crew_id',c.crew_id,'display_name',c.display_name,'module',c.module,'role',role_name),
    'players',players,'vote_summary',summary,'my_vote',my_vote
  );
end;
$$;

create or replace function public.pani_containment_join(p_token text, p_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare c public.crew_access%rowtype; s pani_private.containment_session%rowtype;
begin
  select * into c from public.crew_access where token_hash=encode(extensions.digest(p_token,'sha256'),'hex');
  if c.crew_id is null then raise exception 'unauthorized'; end if;
  select * into s from pani_private.containment_session where session_id='W77-01' for update;
  if not coalesce((s.state->>'released')::boolean,false) then raise exception 'session_closed'; end if;
  if upper(trim(coalesce(p_code,''))) is distinct from upper(trim(coalesce(s.join_code,''))) then raise exception 'invalid_session_code'; end if;
  insert into pani_private.containment_participant(session_id,crew_id,joined,joined_at,last_seen)
  values ('W77-01',c.crew_id,true,now(),now())
  on conflict (session_id,crew_id) do update set joined=true,last_seen=now(),hold_until=null;
  perform pani_private.containment_log_event('W77-01',c.display_name,'player_joined',c.crew_id);
  return public.pani_containment_crew_state(p_token);
end;
$$;

create or replace function public.pani_containment_crew_action(
  p_token text, p_action text, p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare c public.crew_access%rowtype; s pani_private.containment_session%rowtype;
  st jsonb; sec jsonb; ev jsonb; active_event text; phase text; value text; rep text; witness text;
  marks jsonb; mark text; cell text; idx integer; size integer; wins integer; rule_id text;
  pos integer; pulse integer; overload integer; card text; effect text; deck jsonb; deck_i integer;
  choice text; answer text; cycle integer; scene jsonb; anchor text;
  seal_count integer; seal_required integer; connected_count integer; hold_count integer;
begin
  select * into c from public.crew_access where token_hash=encode(extensions.digest(p_token,'sha256'),'hex');
  if c.crew_id is null then raise exception 'unauthorized'; end if;
  perform pani_private.containment_tick('W77-01');
  select * into s from pani_private.containment_session where session_id='W77-01' for update;
  if not exists(select 1 from pani_private.containment_participant p where p.session_id='W77-01' and p.crew_id=c.crew_id and p.joined) then
    raise exception 'not_joined';
  end if;
  update pani_private.containment_participant set last_seen=now() where session_id='W77-01' and crew_id=c.crew_id;
  st:=s.state; sec:=s.secret_state; ev:=coalesce(st->'event','{}'::jsonb);
  active_event:=st->>'active_event'; phase:=ev->>'vote_phase'; rep:=st->>'representative_id'; witness:=st->>'witness_id';

  if p_action='vote' then
    value:=left(trim(coalesce(p_payload->>'value','')),40);
    if active_event is null or phase is null or value='' then raise exception 'vote_unavailable'; end if;
    if active_event='knowledge' then raise exception 'direct_play_required'; end if;
    if active_event='energy' and value not in ('advance','stable','volatile') then raise exception 'invalid_vote'; end if;
    if active_event='blood' and (ev->>'phase'<>'beats' or value not in ('A','B','C')) then raise exception 'invalid_vote'; end if;
    if active_event='death' and (ev->>'phase'<>'cycles' or value not in ('clock','lamp','door','sample','chair','mirror')) then raise exception 'invalid_vote'; end if;
    insert into pani_private.containment_vote(session_id,event_id,phase_key,crew_id,value,updated_at)
    values ('W77-01',active_event,phase,c.crew_id,value,now())
    on conflict (session_id,event_id,phase_key,crew_id) do update set value=excluded.value,updated_at=now();
    perform pani_private.containment_log_event('W77-01',c.display_name,'vote',active_event||':'||phase||':'||value);

  elsif p_action='knowledge_mark' then
    if active_event<>'knowledge' or ev->>'phase' not in ('round1','round2') then raise exception 'knowledge_unavailable'; end if;
    select count(*) into connected_count from pani_private.containment_participant p
      where p.session_id='W77-01' and p.joined and p.last_seen>now()-interval '12 seconds';
    if connected_count>1 and coalesce(ev->>'last_actor_id','')=c.crew_id then raise exception 'alternate_operator_required'; end if;
    cell:=coalesce(p_payload->>'cell',''); size:=coalesce((ev->>'size')::int,3);
    if cell !~ '^c[0-9]{1,2}$' then raise exception 'invalid_cell'; end if;
    idx:=substring(cell from 2)::int;
    if idx<0 or idx>=size*size then raise exception 'invalid_cell'; end if;
    marks:=coalesce(ev->'marks','{}'::jsonb); if marks ? cell then raise exception 'occupied_cell'; end if;
    if coalesce(ev->'unstable','[]'::jsonb) @> jsonb_build_array(cell) then raise exception 'unstable_cell'; end if;
    rule_id:=sec#>>'{knowledge,rule_id}';
    if ev->>'phase'='round2' and rule_id='diagonal_prohibited' and idx/size=idx%size then raise exception 'rule_violation'; end if;
    if ev->>'phase'='round2' and rule_id='false_center' and idx in (5,6,9,10) then raise exception 'rule_violation'; end if;
    mark:=coalesce(ev->>'current_mark','X'); marks:=jsonb_set(marks,array[cell],to_jsonb(mark),true);
    ev:=ev||jsonb_build_object('marks',marks,'current_mark',case when mark='X' then 'O' else 'X' end,
      'move',coalesce((ev->>'move')::int,0)+1,'last_actor_id',c.crew_id);
    if pani_private.containment_knowledge_line(marks,size,mark) then
      wins:=coalesce((ev->>'wins')::int,0)+1;
      if ev->>'phase'='round1' then
        ev:=jsonb_build_object('phase','round2','round',2,'size',4,'marks','{}'::jsonb,'current_mark','X','move',0,
          'wins',wins,'unstable',case when rule_id='mobile_cell' then jsonb_build_array('c7') else '[]'::jsonb end,
          'absent','[]'::jsonb,'rule_title','REGRA VARIÁVEL','rule_text',case rule_id
            when 'diagonal_prohibited' then 'Marcas na diagonal principal são rejeitadas.'
            when 'false_center' then 'O centro geométrico é uma zona falsa.'
            when 'mobile_cell' then 'Uma casa móvel permanece instável nesta rodada.'
            else 'Uma linha de três encerra a rodada antes da quarta marca.' end,
          'hint',null,'locked',false,'last_actor_id',null,'vote_phase','knowledge:r2:m1');
      else
        ev:=jsonb_build_object('phase','missing','round',3,'size',3,'marks',jsonb_build_object('c1','X','c7','X'),
          'current_mark','X','move',0,'wins',wins,'unstable','[]'::jsonb,'absent',jsonb_build_array('c4'),
          'rule_title','CASA AUSENTE','rule_text','A casa removida continua pertencendo ao tabuleiro.',
          'hint','A ausência também ocupa uma posição.','locked',false,'last_actor_id',null,'vote_phase','knowledge:missing');
      end if;
    elsif (select count(*) from jsonb_object_keys(marks))>=size*size-jsonb_array_length(coalesce(ev->'unstable','[]'::jsonb)) then
      ev:=ev||jsonb_build_object('marks','{}'::jsonb,'current_mark','X','move',0,'last_actor_id',null);
      st:=jsonb_set(st,'{saturation}',to_jsonb(least(8,coalesce((st->>'saturation')::int,0)+1)));
    else
      ev:=ev||jsonb_build_object('vote_phase','knowledge:r'||coalesce(ev->>'round','1')||':m'||(coalesce((ev->>'move')::int,0)+1));
    end if;
    st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='knowledge_missing' then
    if active_event<>'knowledge' or ev->>'phase'<>'missing' or p_payload->>'cell'<>'c4' then raise exception 'missing_house_required'; end if;
    st:=pani_private.containment_capture(st,'knowledge');
    delete from pani_private.containment_vote v where v.session_id='W77-01' and v.event_id='knowledge';

  elsif p_action in ('knowledge_scan','knowledge_lock') then
    if active_event<>'knowledge' then raise exception 'knowledge_unavailable'; end if;
    if p_action='knowledge_scan' then
      if coalesce((st#>>'{pani_charges,scan}')::int,0)<1 then raise exception 'charge_unavailable'; end if;
      st:=jsonb_set(st,'{pani_charges,scan}','0'::jsonb,true);
      ev:=ev||jsonb_build_object('hint',case sec#>>'{knowledge,rule_id}'
        when 'diagonal_prohibited' then 'SCAN: a diagonal principal não aceita matéria simbólica.'
        when 'false_center' then 'SCAN: o centro exibido não pertence ao tabuleiro lógico.'
        when 'mobile_cell' then 'SCAN: a casa C7 está deslocada da malha.'
        else 'SCAN: conclua a linha antes que uma quarta marca a invalide.' end);
    else
      if coalesce((st#>>'{pani_charges,lock}')::int,0)<1 then raise exception 'charge_unavailable'; end if;
      st:=jsonb_set(st,'{pani_charges,lock}','0'::jsonb,true); ev:=ev||jsonb_build_object('locked',true);
    end if;
    st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='energy_move' then
    if active_event<>'energy' or c.crew_id<>rep then raise exception 'representative_required'; end if;
    pos:=coalesce((ev->>'position')::int,0); pulse:=greatest(1,least(6,coalesce((ev->>'pulse')::int,1)));
    overload:=coalesce((ev->>'overload')::int,0); choice:=coalesce(p_payload->>'route','stable');
    if coalesce((ev->>'slowed')::boolean,false) then pulse:=greatest(1,floor(pulse/2.0)::int);ev:=ev-'slowed'; end if;
    if pos in (3,9,15) and choice not in ('stable','volatile') then raise exception 'route_required'; end if;
    if pos in (3,9,15) and choice='volatile' then pulse:=pulse+1; overload:=overload+1; end if;
    pos:=least(19,pos+pulse); deck:=coalesce(sec#>'{energy,deck}','[]'::jsonb); deck_i:=coalesce((sec#>>'{energy,index}')::int,0);
    card:=coalesce(sec#>>'{energy,override_card}',deck->>(deck_i%greatest(1,jsonb_array_length(deck))),'PULSO VAZIO');
    effect:='Sem alteração adicional.';
    case card
      when 'ZUMBI DE SANGUE' then if coalesce((p_payload->>'accept_overload')::boolean,false) then pos:=greatest(0,pos-1);overload:=overload+1;effect:='Recuo 1; sobrecarga aceita.';else pos:=greatest(0,pos-2);effect:='Recuo 2.';end if;
      when 'ESQUELETO DE LODO' then pos:=greatest(0,pos-1);effect:='A trilha puxou o peão uma casa.';
      when 'ANÁRQUICO' then idx:=(array[-2,0,2,4])[1+floor(random()*4)::int];pos:=greatest(0,least(19,pos+idx));effect:='Dado anárquico: '||case when idx>=0 then '+' else '' end||idx||'.';
      when 'EXISTIDO' then ev:=ev||jsonb_build_object('pani_blocked',true);effect:='Suportes PANI bloqueados no próximo turno.';
      when 'ENRAIZADO' then ev:=ev||jsonb_build_object('slowed',true);effect:='O próximo pulso será reduzido.';
      when 'MARIONETE' then overload:=overload+1;effect:='O último efeito ecoa: +1 sobrecarga.';
      when 'VIAJANTE' then ev:=ev||jsonb_build_object('hidden_cells',3);effect:='As próximas três casas ficaram ocultas.';
      when 'CARNIÇAL PRETO DA MORTE' then if coalesce((p_payload->>'accept_overload')::boolean,false) then pos:=least(19,pos+1);overload:=overload+2;effect:='+1 casa e +2 sobrecarga.';else pos:=greatest(0,pos-3);effect:='Recuo 3.';end if;
      when 'ENPAP-X' then ev:=ev||jsonb_build_object('ghost_cell',least(19,pos+2));effect:='Uma casa futura foi destruída.';
      when 'DEGOLIFICADA' then if p_payload->>'card_choice'='right' then overload:=overload+1;effect:='Carta oculta direita: +1 sobrecarga.';else pos:=greatest(0,pos-1);effect:='Carta oculta esquerda: recuo 1.';end if;
      when 'MAGISTRADA' then ev:=ev||jsonb_build_object('reordered',true);effect:='Cinco casas foram reorganizadas.';
      when 'DEUS DA MORTE' then pos:=case when pos>=13 then 13 when pos>=6 then 6 else 0 end;overload:=greatest(0,overload-2);effect:='Retorno ao checkpoint; -2 sobrecarga.';
      when 'DIABO' then if coalesce((p_payload->>'accept_overload')::boolean,false) then pos:=least(19,pos+5);overload:=overload+2;effect:='+5 casas e +2 sobrecarga.';else pos:=greatest(0,pos-1);effect:='Oferta recusada: recuo 1.';end if;
      when 'ANFITRIÃO' then idx:=(array[-3,-1,1,2])[1+floor(random()*4)::int];pos:=greatest(0,least(19,pos+idx));effect:='Deslocamento do Anfitrião: '||case when idx>=0 then '+' else '' end||idx||'.';
      else null;
    end case;
    if overload>=7 then
      pos:=case when pos>=13 then 13 when pos>=6 then 6 else 0 end; overload:=4;
      st:=jsonb_set(st,'{saturation}',to_jsonb(least(8,coalesce((st->>'saturation')::int,0)+1)));
      effect:=effect||' SOBRECARGA 7/7: retorno seguro ao checkpoint.';
    end if;
    if pos>=19 then st:=pani_private.containment_capture(st,'energy');
    else
      ev:=ev||jsonb_build_object('position',pos,'overload',overload,'pulse',1+floor(random()*4)::int,
        'turn',coalesce((ev->>'turn')::int,1)+1,'last_card',card,'last_effect',effect,
        'vote_phase','energy:t'||(coalesce((ev->>'turn')::int,1)+1));
      sec:=jsonb_set(sec,'{energy,index}',to_jsonb(deck_i+1),true);sec:=jsonb_set(sec,'{energy,override_card}','null'::jsonb,true);
      st:=jsonb_set(st,'{event}',ev,true);
    end if;

  elsif p_action='blood_select' then
    if active_event<>'blood' or c.crew_id<>rep or ev->>'phase'<>'beats' then raise exception 'representative_required'; end if;
    choice:=upper(coalesce(p_payload->>'valve','')); if choice not in ('A','B','C') then raise exception 'invalid_valve'; end if;
    ev:=ev||jsonb_build_object('selected_valve',choice); st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='blood_contain' then
    if active_event<>'blood' or ev->>'phase'<>'final' or c.crew_id<>rep then raise exception 'representative_required'; end if;
    ev:=ev||jsonb_build_object('representative_ready',true);st:=jsonb_set(st,'{event}',ev,true);
    select least(4,greatest(1,count(*) filter (where p.crew_id<>rep)))::int into seal_required
      from pani_private.containment_participant p
      where p.session_id='W77-01' and p.joined and p.last_seen>now()-interval '12 seconds';
    select count(distinct v.value) into seal_count from pani_private.containment_vote v
      where v.session_id='W77-01' and v.event_id='blood' and v.phase_key='blood:seals';
    if seal_count>=seal_required then st:=pani_private.containment_capture(st,'blood'); end if;

  elsif p_action='blood_seal' then
    if active_event<>'blood' or ev->>'phase'<>'final' then raise exception 'final_unavailable'; end if;
    if c.crew_id=rep then raise exception 'representative_must_contain'; end if;
    value:=upper(coalesce(p_payload->>'seal','')); if value not in ('A','B','C','D') then raise exception 'invalid_seal'; end if;
    insert into pani_private.containment_vote(session_id,event_id,phase_key,crew_id,value,updated_at)
    values ('W77-01','blood','blood:seals',c.crew_id,value,now())
    on conflict (session_id,event_id,phase_key,crew_id) do update set value=excluded.value,updated_at=now();
    select least(4,greatest(1,count(*) filter (where p.crew_id<>rep)))::int into seal_required
      from pani_private.containment_participant p
      where p.session_id='W77-01' and p.joined and p.last_seen>now()-interval '12 seconds';
    select count(distinct v.value) into seal_count from pani_private.containment_vote v
      where v.session_id='W77-01' and v.event_id='blood' and v.phase_key='blood:seals';
    if seal_count>=seal_required and coalesce((ev->>'representative_ready')::boolean,false) then st:=pani_private.containment_capture(st,'blood'); end if;

  elsif p_action='death_confirm' then
    if active_event<>'death' or c.crew_id<>witness or ev->>'phase'<>'cycles' then raise exception 'witness_required'; end if;
    choice:=coalesce(p_payload->>'object',''); answer:=sec#>>'{death,answer}';
    if choice=answer then
      cycle:=coalesce((ev->>'cycle')::int,1)+1;
      delete from pani_private.containment_vote v where v.session_id='W77-01' and v.event_id='death' and v.phase_key=ev->>'vote_phase';
      ev:=ev||jsonb_build_object('previous_witness',witness);
      if cycle>4 then ev:=ev||jsonb_build_object('phase','final','cycle',4,'vote_phase','death:hold');st:=st||jsonb_build_object('event',ev,'witness_id',null);
      else
        anchor:=ev->>'anchor';scene:=pani_private.containment_death_case(cycle,anchor);
        ev:=ev||jsonb_build_object('cycle',cycle,'scene_kind',scene#>>'{public,scene_kind}',
          'changed_visuals',scene#>'{public,changed_visuals}','missing_object',null,'memory_overlay',false,
          'attempts',0,'vote_phase','death:c'||cycle);
        sec:=jsonb_set(sec,'{death}',jsonb_build_object('cycle',cycle,'answer',scene->>'answer'),true);
        st:=st||jsonb_build_object('event',ev,'witness_id',null);
      end if;
    else
      ev:=ev||jsonb_build_object('attempts',coalesce((ev->>'attempts')::int,0)+1);
      st:=jsonb_set(st,'{event}',ev,true);st:=jsonb_set(st,'{saturation}',to_jsonb(least(8,coalesce((st->>'saturation')::int,0)+1)));
    end if;

  elsif p_action='death_anchor' then
    if active_event<>'death' or c.crew_id<>witness or ev->>'anchor' is not null then raise exception 'anchor_unavailable'; end if;
    value:=coalesce(p_payload->>'object',''); if value not in ('clock','lamp','door','sample','chair','mirror') then raise exception 'invalid_object'; end if;
    ev:=ev||jsonb_build_object('anchor',value);st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='death_hold' then
    if active_event<>'death' or ev->>'phase'<>'final' then raise exception 'final_unavailable'; end if;
    update pani_private.containment_participant set hold_until=now()+interval '2500 milliseconds',last_seen=now()
      where session_id='W77-01' and crew_id=c.crew_id;
    select count(*) into connected_count from pani_private.containment_participant p
      where p.session_id='W77-01' and p.joined and p.last_seen>now()-interval '12 seconds';
    select count(*) into hold_count from pani_private.containment_participant p
      where p.session_id='W77-01' and p.joined and p.last_seen>now()-interval '12 seconds' and p.hold_until>now();
    if connected_count>=1 and hold_count>=connected_count then st:=pani_private.containment_capture(st,'death'); end if;
  else
    raise exception 'unknown_action';
  end if;

  update pani_private.containment_session set state=st,secret_state=sec,revision=revision+1,updated_at=now() where session_id='W77-01';
  perform pani_private.containment_log_event('W77-01',c.display_name,p_action,active_event);
  return public.pani_containment_crew_state(p_token);
end;
$$;

create or replace function public.pani_containment_master_state(p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare s pani_private.containment_session%rowtype; players jsonb; votes jsonb; logs jsonb;
begin
  if not public.pani_master_valid(p_pin) then raise exception 'unauthorized'; end if;
  perform pani_private.containment_tick('W77-01');
  select * into s from pani_private.containment_session where session_id='W77-01';
  select coalesce(jsonb_agg(jsonb_build_object('crew_id',ca.crew_id,'display_name',ca.display_name,'module',ca.module,
    'joined',coalesce(p.joined,false),'connected',coalesce(p.last_seen>now()-interval '12 seconds',false),'last_seen',p.last_seen)
    order by ca.display_name),'[]'::jsonb) into players
  from public.crew_access ca left join pani_private.containment_participant p on p.crew_id=ca.crew_id and p.session_id='W77-01';
  select coalesce(jsonb_agg(jsonb_build_object('event_id',v.event_id,'phase_key',v.phase_key,'crew_id',v.crew_id,
    'display_name',ca.display_name,'value',v.value,'updated_at',v.updated_at) order by v.updated_at),'[]'::jsonb) into votes
  from pani_private.containment_vote v join public.crew_access ca on ca.crew_id=v.crew_id where v.session_id='W77-01';
  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into logs
  from (select id,actor,event_type,detail,created_at from pani_private.containment_log where session_id='W77-01' order by created_at desc limit 80) x;
  return jsonb_build_object('session_id','W77-01','join_code',s.join_code,'state',s.state,'secret_state',s.secret_state,
    'revision',s.revision,'server_time',now(),'players',players,'votes',votes,'logs',logs);
end;
$$;

create or replace function public.pani_containment_master_action(
  p_pin text, p_action text, p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare s pani_private.containment_session%rowtype; st jsonb; sec jsonb; ev jsonb;
  active_event text; target text; code text; rep text; witness text; kind text; rule_id text;
  duration integer; statuses jsonb; case_data jsonb; deck jsonb; delta integer; value integer;
  timer_seconds integer; backup jsonb; ghost text;
begin
  if not public.pani_master_valid(p_pin) then raise exception 'unauthorized'; end if;
  perform pani_private.containment_tick('W77-01');
  select * into s from pani_private.containment_session where session_id='W77-01' for update;
  st:=s.state; sec:=s.secret_state; ev:=coalesce(st->'event','{}'::jsonb);active_event:=st->>'active_event';

  if p_action='new_session' then
    code:=upper(trim(coalesce(p_payload->>'code','')));
    if code='' then code:=upper(substr(md5(random()::text||clock_timestamp()::text),1,4)); end if;
    if code!~'^[A-Z0-9]{4,8}$' then raise exception 'invalid_session_code'; end if;
    st:=pani_private.containment_default_state()||jsonb_build_object('released',true,'status','lobby',
      'announcement','VARREDURA CONCLUÍDA. QUATRO ASSINATURAS ANÔMALAS EM MOVIMENTO.','announcement_revision',1);
    sec:=pani_private.containment_default_secret();
    delete from pani_private.containment_vote where session_id='W77-01';
    delete from pani_private.containment_participant where session_id='W77-01';
    update pani_private.containment_session set join_code=code,state=st,secret_state=sec,revision=revision+1,updated_at=now() where session_id='W77-01';
    perform pani_private.containment_log_event('W77-01','MASTER','session_opened',code);
    return public.pani_containment_master_state(p_pin);

  elsif p_action='close_session' then
    st:=pani_private.containment_default_state();sec:=pani_private.containment_default_secret();
    delete from pani_private.containment_vote where session_id='W77-01';
    delete from pani_private.containment_participant where session_id='W77-01';
    update pani_private.containment_session set join_code=null,state=st,secret_state=sec,revision=revision+1,updated_at=now() where session_id='W77-01';
    perform pani_private.containment_log_event('W77-01','MASTER','session_closed',null);
    return public.pani_containment_master_state(p_pin);
  end if;

  if not coalesce((st->>'released')::boolean,false) then raise exception 'session_closed'; end if;

  if p_action='set_available' then
    target:=coalesce(p_payload->>'event',''); if target not in ('knowledge','energy','blood','death') then raise exception 'invalid_event'; end if;
    statuses:=coalesce(st->'event_status','{}'::jsonb);
    if statuses->>target='contained' then raise exception 'event_contained'; end if;
    statuses:=jsonb_set(statuses,array[target],to_jsonb(case when coalesce((p_payload->>'available')::boolean,true) then 'available' else 'detected' end),true);
    st:=jsonb_set(st,'{event_status}',statuses,true);

  elsif p_action='start_event' then
    target:=coalesce(p_payload->>'event',''); rep:=coalesce(p_payload->>'representative_id','');
    if target not in ('knowledge','energy','blood','death') then raise exception 'invalid_event'; end if;
    if active_event is not null then raise exception 'event_in_progress'; end if;
    if st#>>array['event_status',target] not in ('available','in_progress') then raise exception 'event_unavailable'; end if;
    if target in ('energy','blood') and not exists(select 1 from pani_private.containment_participant p where p.session_id='W77-01' and p.crew_id=rep and p.joined) then raise exception 'representative_unavailable'; end if;
    if target not in ('energy','blood') then rep:=null; end if;
    statuses:=jsonb_set(st->'event_status',array[target],'"in_progress"'::jsonb,true);
    st:=st||jsonb_build_object('status','active','active_event',target,'event_status',statuses,
      'representative_id',rep,'witness_id',null,'corruption_charges',2,'pani_charges',jsonb_build_object('scan',1,'lock',1),
      'paused',false,'timer_end',null,'timer_remaining',null,
      'announcement','NÃO DESTRUAM A ARENA. VENÇAM A ARENA.','announcement_revision',coalesce((st->>'announcement_revision')::int,0)+1);
    delete from pani_private.containment_vote v where v.session_id='W77-01' and v.event_id=target;
    if target='knowledge' then
      rule_id:=(array['diagonal_prohibited','false_center','mobile_cell','anti_three'])[1+floor(random()*4)::int];
      ev:=jsonb_build_object('phase','round1','round',1,'size',3,'marks','{}'::jsonb,'current_mark','X','move',0,'wins',0,
        'unstable',jsonb_build_array('c4'),'absent','[]'::jsonb,'rule_title','MALHA INSTÁVEL',
        'rule_text','Forme uma linha de três sem ocupar a casa instável.','hint',null,'locked',false,'ghost_cells','[]'::jsonb,'last_actor_id',null,
        'vote_phase','knowledge:r1:m1');
      sec:=jsonb_set(sec,'{knowledge}',jsonb_build_object('rule_id',rule_id),true);
    elsif target='energy' then
      deck:=jsonb_build_array('ZUMBI DE SANGUE','ESQUELETO DE LODO','ANÁRQUICO','EXISTIDO','ENRAIZADO','MARIONETE','VIAJANTE',
        'CARNIÇAL PRETO DA MORTE','ENPAP-X','DEGOLIFICADA','MAGISTRADA','DEUS DA MORTE','DIABO','ANFITRIÃO');
      ev:=jsonb_build_object('phase','trail','position',0,'overload',0,'pulse',1+floor(random()*4)::int,'turn',1,
        'checkpoints',jsonb_build_array(6,13),'forks',jsonb_build_array(3,9,15),'last_card',null,'last_effect','Aguardando pulso.',
        'hidden_cells',0,'ghost_cell',null,'vote_phase','energy:t1');
      sec:=jsonb_set(sec,'{energy}',jsonb_build_object('deck',deck,'index',0,'override_card',null),true);
    elsif target='blood' then
      timer_seconds:=greatest(12,least(18,coalesce((p_payload->>'beat_seconds')::int,15)));case_data:=pani_private.containment_blood_case(1);
      ev:=jsonb_build_object('phase','beats','beat',1,'beat_seconds',timer_seconds,'stabilization',0,'hemorrhage',0,
        'readings',case_data->'readings','selected_valve',null,'one_may_lie',false,'vote_phase','blood:beat1');
      sec:=jsonb_set(sec,'{blood}',jsonb_build_object('beat_index',1,'answer',case_data->>'answer','fake_votes',null),true);
      st:=st||jsonb_build_object('timer_end',(now()+make_interval(secs=>timer_seconds))::text);
    else
      case_data:=pani_private.containment_death_case(1,null);
      ev:=jsonb_build_object('phase','cycles','cycle',1,'scene_kind',case_data#>>'{public,scene_kind}',
        'changed_visuals',case_data#>'{public,changed_visuals}','missing_object',null,'memory_overlay',false,'anchor',null,
        'attempts',0,'vote_phase','death:c1');
      sec:=jsonb_set(sec,'{death}',jsonb_build_object('cycle',1,'answer',case_data->>'answer'),true);
    end if;
    st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='set_representative' then
    if active_event not in ('energy','blood') then raise exception 'representative_not_required'; end if;
    rep:=coalesce(p_payload->>'crew_id','');
    if not exists(select 1 from pani_private.containment_participant p where p.session_id='W77-01' and p.crew_id=rep and p.joined) then raise exception 'representative_unavailable'; end if;
    st:=jsonb_set(st,'{representative_id}',to_jsonb(rep),true);

  elsif p_action='set_witness' then
    witness:=coalesce(p_payload->>'crew_id','');
    if active_event<>'death' then raise exception 'death_only'; end if;
    select count(*) into value from pani_private.containment_participant p
      where p.session_id='W77-01' and p.joined and p.last_seen>now()-interval '12 seconds';
    if witness=coalesce(st->>'witness_id','') or (value>1 and witness=coalesce(ev->>'previous_witness',''))
       or not exists(select 1 from pani_private.containment_participant p where p.session_id='W77-01' and p.crew_id=witness and p.joined) then raise exception 'witness_unavailable'; end if;
    st:=jsonb_set(st,'{witness_id}',to_jsonb(witness),true);

  elsif p_action='corrupt' then
    if active_event is null or coalesce((st->>'corruption_charges')::int,0)<1 then raise exception 'corruption_unavailable'; end if;
    kind:=coalesce(p_payload->>'kind','');duration:=greatest(900,least(2200,coalesce((p_payload->>'duration_ms')::int,1400)));
    if kind='' then kind:=case active_event when 'knowledge' then 'ghost_mark' when 'energy' then 'swapped_card' when 'blood' then 'false_reading' else 'false_echo' end; end if;
    backup:=jsonb_build_object('event',ev,'event_secret',coalesce(sec->active_event,'{}'::jsonb));
    sec:=sec||jsonb_build_object('corruption',jsonb_build_object('event',active_event,'kind',kind),'corruption_backup',backup);
    if active_event='knowledge' then
      if kind='semantic_swap' then ev:=ev||jsonb_build_object('rule_text','A casa instável é obrigatória para validar a linha.');
      else ghost:='c'||floor(random()*greatest(1,coalesce((ev->>'size')::int,3)^2))::int;ev:=ev||jsonb_build_object('ghost_cells',coalesce(ev->'ghost_cells','[]'::jsonb)||jsonb_build_array(ghost)); end if;
    elsif active_event='energy' then
      if kind='charged_pulse' then ev:=ev||jsonb_build_object('pulse',least(6,coalesce((ev->>'pulse')::int,1)+2));
      else sec:=jsonb_set(sec,'{energy,override_card}',to_jsonb('ANFITRIÃO'::text),true);ev:=ev||jsonb_build_object('card_label_override','PULSO VAZIO'); end if;
    elsif active_event='blood' then
      if kind='corrupted_vote' then sec:=jsonb_set(sec,'{blood,fake_votes}',jsonb_build_object('A',67,'B',17,'C',16),true);
      else ev:=jsonb_set(ev,'{readings,0}',to_jsonb('A apresenta todos os parâmetros estáveis.'::text),true)||jsonb_build_object('one_may_lie',true); end if;
    else
      if kind='missing_frame' then ev:=ev||jsonb_build_object('missing_object','chair','missing_until',(now()+interval '2 seconds')::text);
      elsif kind='memory_overlay' then ev:=ev||jsonb_build_object('memory_overlay',true);
      else ev:=ev||jsonb_build_object('changed_visuals',coalesce(ev->'changed_visuals','[]'::jsonb)||jsonb_build_array('lamp')); end if;
    end if;
    st:=st||jsonb_build_object('event',ev,'corruption_charges',coalesce((st->>'corruption_charges')::int,0)-1,
      'glitch',jsonb_build_object('revision',coalesce((st#>>'{glitch,revision}')::int,0)+1,'duration_ms',duration,'at',now()),
      'announcement','INTERFERÊNCIA DETECTADA','announcement_revision',coalesce((st->>'announcement_revision')::int,0)+1);

  elsif p_action='restore_corruption' then
    backup:=sec->'corruption_backup'; if backup is null or backup='null'::jsonb then raise exception 'no_corruption'; end if;
    if backup ? 'event' then
      st:=jsonb_set(st,'{event}',backup->'event',true);
      sec:=jsonb_set(sec,array[active_event],coalesce(backup->'event_secret','{}'::jsonb),true);
    else
      st:=jsonb_set(st,'{event}',backup,true);
    end if;
    st:=jsonb_set(st,'{corruption_charges}',to_jsonb(least(2,coalesce((st->>'corruption_charges')::int,0)+1)),true);
    sec:=jsonb_set(sec,'{blood,fake_votes}','null'::jsonb,true)||jsonb_build_object('corruption',null,'corruption_backup',null);

  elsif p_action='pause' then
    if coalesce((st->>'paused')::boolean,false) then
      st:=st||jsonb_build_object('paused',false,'timer_end',case when st->>'timer_remaining' is null then null else (now()+make_interval(secs=>(st->>'timer_remaining')::int))::text end,'timer_remaining',null);
    else
      st:=st||jsonb_build_object('paused',true,'timer_remaining',case when st->>'timer_end' is null then null else greatest(0,extract(epoch from ((st->>'timer_end')::timestamptz-now()))::int) end,'timer_end',null);
    end if;

  elsif p_action='saturation' then
    if p_payload ? 'value' then value:=greatest(0,least(8,(p_payload->>'value')::int));
    else delta:=greatest(-8,least(8,coalesce((p_payload->>'delta')::int,0)));value:=greatest(0,least(8,coalesce((st->>'saturation')::int,0)+delta));end if;
    st:=jsonb_set(st,'{saturation}',to_jsonb(value),true);

  elsif p_action='grant_hint' then
    ev:=ev||jsonb_build_object('hint',left(coalesce(p_payload->>'text','PANI detecta uma inconsistência local.'),500));st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='force_phase' then
    ev:=ev||jsonb_build_object('phase',left(coalesce(p_payload->>'phase',ev->>'phase'),40));st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='clear_votes' then
    if active_event is null then
      delete from pani_private.containment_vote v where v.session_id='W77-01';
    else
      delete from pani_private.containment_vote v where v.session_id='W77-01' and v.event_id=active_event;
    end if;

  elsif p_action='knowledge_rule' then
    if active_event<>'knowledge' then raise exception 'knowledge_only'; end if;
    rule_id:=coalesce(p_payload->>'rule_id','anti_three');sec:=jsonb_set(sec,'{knowledge,rule_id}',to_jsonb(rule_id),true);
    ev:=ev||jsonb_build_object('rule_text',case rule_id when 'diagonal_prohibited' then 'Marcas na diagonal principal são rejeitadas.' when 'false_center' then 'O centro geométrico é uma zona falsa.' when 'mobile_cell' then 'Uma casa móvel permanece instável nesta rodada.' else 'Uma linha de três encerra a rodada antes da quarta marca.' end);st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='energy_pulse' then
    if active_event<>'energy' then raise exception 'energy_only'; end if; value:=greatest(1,least(6,(p_payload->>'value')::int));ev:=ev||jsonb_build_object('pulse',value);st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='energy_card' then
    if active_event<>'energy' then raise exception 'energy_only'; end if;sec:=jsonb_set(sec,'{energy,override_card}',to_jsonb(upper(left(p_payload->>'card',80))),true);

  elsif p_action='death_scene' then
    if active_event<>'death' then raise exception 'death_only'; end if;value:=greatest(1,least(4,(p_payload->>'cycle')::int));case_data:=pani_private.containment_death_case(value,ev->>'anchor');
    ev:=ev||jsonb_build_object('phase','cycles','cycle',value,'scene_kind',case_data#>>'{public,scene_kind}','changed_visuals',case_data#>'{public,changed_visuals}','vote_phase','death:c'||value);
    sec:=jsonb_set(sec,'{death}',jsonb_build_object('cycle',value,'answer',case_data->>'answer'),true);st:=jsonb_set(st,'{event}',ev,true);

  elsif p_action='blood_timer' then
    if active_event<>'blood' then raise exception 'blood_only'; end if;timer_seconds:=greatest(12,least(18,(p_payload->>'seconds')::int));ev:=ev||jsonb_build_object('beat_seconds',timer_seconds);st:=st||jsonb_build_object('event',ev,'timer_end',(now()+make_interval(secs=>timer_seconds))::text);

  elsif p_action='remove_player' then
    target:=coalesce(p_payload->>'crew_id','');update pani_private.containment_participant set joined=false,hold_until=null where session_id='W77-01' and crew_id=target;
    if st->>'representative_id'=target then st:=jsonb_set(st,'{representative_id}','null'::jsonb,true);end if;
    if st->>'witness_id'=target then st:=jsonb_set(st,'{witness_id}','null'::jsonb,true);end if;

  elsif p_action='reconnect_player' then
    target:=coalesce(p_payload->>'crew_id','');
    insert into pani_private.containment_participant(session_id,crew_id,joined,last_seen) values ('W77-01',target,true,now())
    on conflict(session_id,crew_id) do update set joined=true,last_seen=now();

  elsif p_action='contain_event' then
    if active_event is null then raise exception 'no_active_event'; end if;st:=pani_private.containment_capture(st,active_event);delete from pani_private.containment_vote v where v.session_id='W77-01' and v.event_id=active_event;

  elsif p_action='end_event' then
    if active_event is null then raise exception 'no_active_event'; end if;statuses:=jsonb_set(st->'event_status',array[active_event],'"available"'::jsonb,true);
    st:=st||jsonb_build_object('status','lobby','active_event',null,'event_status',statuses,'representative_id',null,'witness_id',null,'event','{}'::jsonb,'timer_end',null,'paused',false);

  elsif p_action='pani_say' then
    st:=st||jsonb_build_object('announcement',left(coalesce(p_payload->>'text','PANI aguarda instruções.'),600),'announcement_revision',coalesce((st->>'announcement_revision')::int,0)+1);

  elsif p_action='residue_reveal' then
    if st->>'residue_status'<>'available' then raise exception 'residue_unavailable'; end if;
    st:=st||jsonb_build_object('residue_status','revealed','announcement','RESÍDUO BIOLÓGICO NÃO CATALOGADO // SETOR AMBIENTAL','announcement_revision',coalesce((st->>'announcement_revision')::int,0)+1);

  elsif p_action='residue_complete' then
    if st->>'residue_status'<>'revealed' then raise exception 'residue_unavailable'; end if;
    st:=st||jsonb_build_object('residue_status','correlated','announcement','CORRELAÇÃO AMBIENTAL PRESERVADA. PRÓXIMA FASE SOB CONTROLE DO DIRETOR.','announcement_revision',coalesce((st->>'announcement_revision')::int,0)+1);
  else
    raise exception 'unknown_action';
  end if;

  update pani_private.containment_session set state=st,secret_state=sec,revision=revision+1,updated_at=now() where session_id='W77-01';
  perform pani_private.containment_log_event('W77-01','MASTER',p_action,coalesce(target,active_event));
  return public.pani_containment_master_state(p_pin);
end;
$$;

revoke execute on function public.pani_containment_crew_state(text) from public, anon, authenticated;
revoke execute on function public.pani_containment_join(text,text) from public, anon, authenticated;
revoke execute on function public.pani_containment_crew_action(text,text,jsonb) from public, anon, authenticated;
revoke execute on function public.pani_containment_master_state(text) from public, anon, authenticated;
revoke execute on function public.pani_containment_master_action(text,text,jsonb) from public, anon, authenticated;

grant execute on function public.pani_containment_crew_state(text) to anon, authenticated, service_role;
grant execute on function public.pani_containment_join(text,text) to anon, authenticated, service_role;
grant execute on function public.pani_containment_crew_action(text,text,jsonb) to anon, authenticated, service_role;
grant execute on function public.pani_containment_master_state(text) to anon, authenticated, service_role;
grant execute on function public.pani_containment_master_action(text,text,jsonb) to anon, authenticated, service_role;

revoke execute on all functions in schema pani_private from public, anon, authenticated;

comment on function public.pani_containment_crew_state(text) is
  'Snapshot público do Protocolo de Contenção v1.1; respostas e corrupções reais permanecem privadas.';
comment on function public.pani_containment_master_action(text,text,jsonb) is
  'Controles exclusivos do Diretor para sessão, arenas, testemunha, corrupção e gancho do resíduo.';
