'use strict';
const U='https://nvwzcnfonhpilnxmopgi.supabase.co';
const K='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52d3pjbmZvbmhwaWxueG1vcGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3NTI3NTcsImV4cCI6MjEwMjMyODc1N30.5FBDbk8J1uN8JLLpKMk_Hubw6K7kbQQiulIamwm9Vso';
const SID='W77-02',STATION_ID='W77-01';
const $=s=>document.querySelector(s),Q=new URLSearchParams(location.search),MASTER=Q.get('master')==='1';
const H={'apikey':K,'Authorization':'Bearer '+K,'Content-Type':'application/json'};
const N={ops:'OPERAÇÕES & INFRAESTRUTURA',gen:'PESQUISA GENÉTICA & BIOCONTENÇÃO',env:'ECOLOGIA & CONTROLE AMBIENTAL',med:'MEDICINA & PATOLOGIA',sec:'SEGURANÇA & CONTROLE DE ACESSO',inv:'INVESTIGAÇÃO & CORRELAÇÃO DE SINAIS',power:'OPERAÇÕES & INFRAESTRUTURA',bio:'PESQUISA GENÉTICA & BIOCONTENÇÃO',environment:'ECOLOGIA & CONTROLE AMBIENTAL',life:'MEDICINA & PATOLOGIA',navigation:'SEGURANÇA & CONTROLE DE ACESSO',comms:'INVESTIGAÇÃO & CORRELAÇÃO DE SINAIS'};
const NL={ops:'OPS',gen:'GEN',env:'ENV',med:'MED',sec:'SEC',inv:'INV',power:'OPS',bio:'GEN',environment:'ENV',life:'MED',navigation:'SEC',comms:'INV'};
const LEGACY_SECTOR={power:'ops',bio:'gen',environment:'env',life:'med',navigation:'sec',comms:'inv'};
let state={mode:'normal',energy_capacity:100,occupancy:6,system_health:{}},sepState={},sepMasterState={},me=null,prog={},tok=Q.get('access')||'',pin='',view='dash',fp='',manifest={},draft={};
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function conn(t,on){let c=$('#conn'),d=$('#dot');if(c)c.textContent=t;if(d)d.className='dot '+(on===true?'on':on===false?'off':'')}
function toast(t,e=false){let x=$('#toast');if(!x)return;x.textContent=t;x.className='toast'+(e?' err':'');clearTimeout(window.__paniToast);window.__paniToast=setTimeout(()=>x.classList.add('hidden'),4200)}
function parseErrorBody(s,status){let msg=s||String(status);try{let j=JSON.parse(s);msg=j.message||j.error_description||j.hint||j.details||j.code||msg}catch{}let e=new Error(msg);e.status=status;e.raw=s;return e}
async function req(path,opt={},retry=1){let c=new AbortController(),tm=setTimeout(()=>c.abort(),8000);try{let r=await fetch(U+path,{...opt,headers:{...H,...(opt.headers||{})},signal:c.signal,cache:'no-store'});let s=await r.text();if(!r.ok)throw parseErrorBody(s,r.status);return s?JSON.parse(s):null}catch(e){if(retry&&(!e.status||e.status>=500||e.name==='AbortError')){await new Promise(r=>setTimeout(r,450));return req(path,opt,0)}throw e}finally{clearTimeout(tm)}}
const rpc=(n,b)=>req('/rest/v1/rpc/'+n,{method:'POST',body:JSON.stringify(b)});
async function backendHealth(){let a=await req('/rest/v1/game_state?id=eq.'+encodeURIComponent(SID)+'&select=id,mode,updated_at',{},0);return !!a?.[0]}
async function getState(){let a=await req('/rest/v1/game_state?id=eq.'+encodeURIComponent(SID)+'&select=*');if(a?.[0]){state=a[0];conn(MASTER&&pin?'MASTER ONLINE':'ONLINE // SINCRONIZADO',true);return state}throw Error('state_unavailable')}
function sectorKey(){return sepState?.sector||LEGACY_SECTOR[me?.module]||me?.module||'ops'}
function solved(k=sectorKey()){return !!sepState?.[k+'_solved']}
function sepSolvedCount(){return ['ops','gen','env','med','sec'].reduce((n,k)=>n+(sepState?.[k+'_solved']?1:0),0)}
function modeName(){if(sepState?.reciprocity_established)return 'RECIPROCIDADE';if(sepState?.alien_event_armed)return 'AMEAÇA ARMADA';if(state.alert_severity==='critical')return 'ALERTA';return 'ESTAÇÃO'}
function capDraft(){document.querySelectorAll('#view input,#view select,#view textarea').forEach(e=>{if(e.id)draft[e.id]=e.value})}
function putDraft(){Object.entries(draft).forEach(([k,v])=>{let e=document.getElementById(k);if(e)e.value=v})}
function fingerprint(){return JSON.stringify([state.mode,state.occupancy,state.alert_text,state.alert_severity,state.transmission,state.system_health,sepState,prog,view])}
function alertRender(){let a=$('#alert');if(!a)return;if(!state.alert_text){a.className='hidden';return}a.textContent=state.alert_text;a.className='alert '+(state.alert_severity==='transmission'?'trans':state.alert_severity==='info'?'info':'')+(state.alert_severity==='critical'?' pulse':'')}
function navRender(){document.querySelectorAll('#nav [data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===view))}
function sysCards(){return ['ops','gen','env','med','sec','inv'].map(k=>{let mine=sectorKey()===k,locked=k==='inv'&&!sepState.inv_available&&!sepState.inv_solved,done=!!sepState[k+'_solved'];return `<div class="sys ${mine?'mine':''} ${locked?'sep-locked':''}"><div class="sub">${mine?'SEU SETOR':'SETOR W77-01'}</div><b>${NL[k]} // ${N[k]}</b><div class="sep-sysstate ${done?'ok':locked?'mut':'warn'}">${done?'ACESSO RESTAURADO':locked?'SEPULTADO // 5 PROVAS NECESSÁRIAS':'SETOR SEPULTADO'}</div>${mine?'<span class="tag">CREDENCIAL VINCULADA</span>':''}</div>`}).join('')}
function dash(){let count=sepSolvedCount(),mine=sectorKey(),call=!solved(mine)&&(mine!=='inv'||sepState.inv_available)?`<div class="cta"><div class="k" style="color:var(--red)">PROTOCOLO SEPULCRO // ${NL[mine]}</div><h2>ACESSO SETORIAL SEPULTADO</h2><p>PANI reconhece sua credencial, mas o registro normal da porta foi removido. A camada assinada por A. Dena exige uma prova.</p><button id="openSepulcro" class="btn r">INICIAR RESTAURAÇÃO →</button></div>`:'';let invStatus=sepState.inv_solved?'CONCLUÍDA':sepState.inv_available?'DISPONÍVEL':'BLOQUEADA';return `${call}<div class="card"><div class="k">${STATION_ID} // MATRIZ SETORIAL</div><h2>${esc(me.mission_role)}</h2><p class="mut">Você está operando dentro da estação W77-01. A antiga matriz de voo foi retirada de serviço; sua credencial agora está vinculada ao setor ${NL[mine]}.</p></div><div class="grid3" style="margin-top:14px">${sysCards()}</div><div class="grid" style="margin-top:14px"><div class="card"><div class="sub">PORTAS SETORIAIS RESTAURADAS</div><div class="metric">${count} / 5</div><div class="sub">INV // ${invStatus}</div></div><div class="card"><div class="term">STATION: ${STATION_ID}\nMODE: ${modeName()}\nPANI CORE: ${state.system_health?.pani??100}%\nSEMANTIC TOKENS: ${(sepState.semantic_tokens||[]).length}</div></div></div>`}
