'use strict';
const U='https://nvwzcnfonhpilnxmopgi.supabase.co';
const K='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52d3pjbmZvbmhwaWxueG1vcGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3NTI3NTcsImV4cCI6MjEwMjMyODc1N30.5FBDbk8J1uN8JLLpKMk_Hubw6K7kbQQiulIamwm9Vso';
const SID='W77-02';
const $=s=>document.querySelector(s),Q=new URLSearchParams(location.search),MASTER=Q.get('master')==='1';
const H={'apikey':K,'Authorization':'Bearer '+K,'Content-Type':'application/json'};
const N={power:'DISTRIBUIÇÃO DE ENERGIA',navigation:'NAVEGAÇÃO & ATITUDE',life:'SUPORTE DE VIDA',comms:'COMUNICAÇÕES & TELEMETRIA',bio:'BIOCONTENÇÃO GENÉTICA',environment:'CONTROLE AMBIENTAL'},NL={power:'ENERGIA',navigation:'NAVEGAÇÃO',life:'SUPORTE DE VIDA',comms:'COMUNICAÇÃO',bio:'BIOCONTENÇÃO',environment:'AMBIENTE'};
let state={mode:'normal',impact_active:false,energy_capacity:100,occupancy:6,system_health:{}},me=null,prog={},tok=Q.get('access')||'',pin='',view='dash',fp='',manifest={},draft={};
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function conn(t,on){let c=$('#conn'),d=$('#dot');if(c)c.textContent=t;if(d)d.className='dot '+(on===true?'on':on===false?'off':'')}
function toast(t,e=false){let x=$('#toast');if(!x)return;x.textContent=t;x.className='toast'+(e?' err':'');clearTimeout(window.__paniToast);window.__paniToast=setTimeout(()=>x.classList.add('hidden'),4200)}
function parseErrorBody(s,status){let msg=s||String(status);try{let j=JSON.parse(s);msg=j.message||j.error_description||j.hint||j.details||j.code||msg}catch{}let e=new Error(msg);e.status=status;e.raw=s;return e}
async function req(path,opt={},retry=1){let c=new AbortController(),tm=setTimeout(()=>c.abort(),8000);try{let r=await fetch(U+path,{...opt,headers:{...H,...(opt.headers||{})},signal:c.signal,cache:'no-store'});let s=await r.text();if(!r.ok)throw parseErrorBody(s,r.status);return s?JSON.parse(s):null}catch(e){if(retry&&(!e.status||e.status>=500||e.name==='AbortError')){await new Promise(r=>setTimeout(r,450));return req(path,opt,0)}throw e}finally{clearTimeout(tm)}}
const rpc=(n,b)=>req('/rest/v1/rpc/'+n,{method:'POST',body:JSON.stringify(b)});
async function backendHealth(){let a=await req('/rest/v1/game_state?id=eq.'+encodeURIComponent(SID)+'&select=id,mode,updated_at',{},0);return !!a?.[0]}
async function getState(){let a=await req('/rest/v1/game_state?id=eq.'+encodeURIComponent(SID)+'&select=*');if(a?.[0]){state=a[0];conn(MASTER&&pin?'MASTER ONLINE':'ONLINE // SINCRONIZADO',true);return state}throw Error('state_unavailable')}
function solved(){return !!prog[me?.module+'_solved']}
function modeName(){return state.mode==='transmission'?'TRANSMISSION':state.impact_active?'CONTINGÊNCIA':state.mode==='alert'?'ALERTA':'NOMINAL'}
function capDraft(){document.querySelectorAll('#view input,#view select,#view textarea').forEach(e=>{if(e.id)draft[e.id]=e.value})}
function putDraft(){Object.entries(draft).forEach(([k,v])=>{let e=document.getElementById(k);if(e)e.value=v})}
function fingerprint(){return JSON.stringify([state.mode,state.impact_active,state.energy_capacity,state.occupancy,state.alert_text,state.alert_severity,state.transmission,state.system_health,prog,manifest,view])}
function alertRender(){let a=$('#alert');if(!a)return;if(!state.alert_text){a.className='hidden';return}a.textContent=state.alert_text;a.className='alert '+(state.alert_severity==='transmission'?'trans':state.alert_severity==='info'?'info':'')+(state.impact_active?' pulse':'')}
function navRender(){document.querySelectorAll('#nav [data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===view))}
function sysCards(){return Object.entries(N).map(([k,n])=>{let h=state.system_health?.[k]??100;return `<div class="sys ${me.module===k?'mine':''} ${h<60?'bad':''}"><div class="sub">${me.module===k?'SEU MÓDULO':'SUBSISTEMA'}</div><b>${n}</b><div class="metric">${h}%</div>${me.module===k?'<span class="tag">AUTORIZADO</span>':'<span class="sub">ACESSO OPERACIONAL RESTRITO</span>'}</div>`}).join('')}
function dash(){let c=state.impact_active&&!solved()?`<div class="cta pulse"><div class="k" style="color:var(--red)">PROTOCOLO DE CONTINGÊNCIA W77</div><h2>${N[me.module]} REQUER INTERVENÇÃO</h2><p>PANI designou <b>${esc(me.display_name)}</b> como operador responsável.</p><button id="openEmergency" class="btn r">ABRIR MÓDULO DE EMERGÊNCIA →</button></div>`:'';return `${c}<div class="card"><div class="k">W77-02 // MATRIZ DE AUTORIZAÇÃO</div><h2>${esc(me.mission_role)}</h2><p class="mut">Seu terminal possui acesso operacional somente ao módulo designado. Dados gerais permanecem disponíveis para coordenação da tripulação.</p></div><div class="grid3" style="margin-top:14px">${sysCards()}</div><div class="grid" style="margin-top:14px"><div class="card"><div class="sub">ENERGIA DISPONÍVEL</div><div class="metric">${state.energy_capacity} U</div><div class="sub">OCUPAÇÃO BIOMÉTRICA: ${state.occupancy}</div></div><div class="card"><div class="term">FLIGHT ID: W77-02\nMODE: ${modeName()}\nPANI CORE: ${state.system_health?.pani??100}%</div></div></div>`}
