'use strict';

const ECO_META=Object.freeze({
 gilbert:{anchor:'GEN',game:'MATRIZ NØ',mirror:'IRIS VALENÇA',verb:'DEDUZIR CÓDIGO'},
 eklay:{anchor:'OPS',game:'REDE DE PARALAXE R-3',mirror:'THEO ARANTES',verb:'CONSTRUIR ROTA'},
 christian:{anchor:'SEC',game:'IFF-Ø // CONTATO SEM ROTA',mirror:'RAUL VOSS',verb:'RASTREAR CONTATO'},
 willy:{anchor:'MED',game:'ECO SOMÁTICO 03:17',mirror:'CAIO RAMIRES',verb:'REPRODUZIR RITMO'},
 aliya:{anchor:'INV',game:'CARTOGRAFIA DAS CONTRADIÇÕES',mirror:'ALEF DENA',verb:'LIGAR EVIDÊNCIAS'}
});
const ECO_NAMES={gilbert:'Gilbert William Beladona',eklay:'Eklay Evans Garrote',christian:'Christian Barletta',willy:'Willy Jacques Ofnir',aliya:'Aliya Kessler'};
const ECO_INTERFERENCE={gilbert:[['visual_mutation','MUTAÇÃO VISUAL'],['verifier_echo','VERIFICADOR ECO'],['no_label','RÓTULO NØ']],eklay:[['remote_rotate','ROTAÇÃO REMOTA'],['blind_queue','FILA CEGA'],['phantom_target','DESTINO FANTASMA']],christian:[['salto','SALTO Ø'],['false_echo','ECO FALSO'],['blind_camera','CÂMERA CEGA']],willy:[['ectopic','BATIMENTO ECTÓPICO'],['label_swap','LABEL SWAP'],['latency','LATÊNCIA']],aliya:[['mirror_document','DOCUMENTO ESPELHO'],['redaction','REDACTION'],['phantom_relation','RELAÇÃO FANTASMA']]};
let ecoMasterPaintKey='',ecoMasterUiDraft={selects:{},details:[]};

function ecoErr(e){let m=String(e?.message||e||'');return({eco_paused:'PROTOCOLO PAUSADO PELO MESTRE',eco_not_released:'PROTOCOLO NÃO LIBERADO',convergence_window_closed:'JANELA ENCERRADA // RECALIBRANDO',invalid_convergence_action:'AÇÃO FINAL INCOMPLETA',presence_locked_until_phase_two:'PRESENÇA DISPONÍVEL APÓS TODAS AS FASES 1',invalid_route_edge:'ROTA SEC CONTÉM UMA ARESTA IMPOSSÍVEL'}[m]||m.replaceAll('_',' ').toUpperCase())}
function ecoBtn(label,call,cls='',disabled=false){return `<button class="btn ${cls}" onclick="${call}" ${disabled?'disabled title="Ação indisponível neste estado"':''}><span>${label}</span></button>`}
function ecoPhaseName(n){return['','AQUISIÇÃO','ESCALADA','INTERFERÊNCIA','FIXAÇÃO'][Number(n)]||'—'}
function ecoPhases(a){return `<div class="eco-phases">${[1,2,3,4].map(n=>`<span class="${a.locked||a.phase>n?'done':a.phase===n?'active':''}"><i>${a.locked||a.phase>n?'✓':n}</i>${ecoPhaseName(n)}</span>`).join('')}</div>`}
function ecoStability(a){return `<div class="eco-stability"><span>ESTABILIDADE</span>${[1,2,3].map(n=>`<i class="${n<=a.stability?'on':''}"></i>`).join('')}</div>`}
function ecoDeadline(v){return `<div class="eco-timer"><span>TEMPO</span><b data-eco-deadline="${esc(v)}">--</b></div>`}

async function ecoCrewRefresh(repaint=true){if(MASTER||!tok||!me)return ecoState;try{ecoState=await rpc('pani_eco_status',{p_token:tok});if(repaint&&view==='eco')render(true)}catch(e){console.error('eco status',e)}return ecoState}
async function ecoInput(action,payload={},button=null){if(ecoBusy)return;ecoBusy=true;let b=button||document.activeElement,old=b?.innerHTML;if(b){b.disabled=true;b.innerHTML='<span>REGISTRANDO...</span>'}let ack=$('#eco-ack');if(ack)ack.textContent='INPUT RECEBIDO // AGUARDANDO SERVIDOR';try{ecoState=window.ecoQaInput?await window.ecoQaInput(action,payload):await rpc('pani_eco_input',{p_token:tok,p_action:action,p_payload:payload});ecoDraft.lastError='';toast('ECO-W77 // REGISTRADO');render(true)}catch(e){ecoDraft.lastError=ecoErr(e);toast('ECO-W77 // '+ecoDraft.lastError,true);if(ack)ack.textContent=ecoDraft.lastError}finally{ecoBusy=false;if(b&&document.contains(b)){b.disabled=false;b.innerHTML=old}}}

function ecoPage(){
 if(!ecoState)return `<section class="card eco-shell"><div class="k">ECO-W77 // SINCRONIZANDO</div><h2>CINCO ÂNCORAS</h2><p class="mut">Solicitando snapshot sanitizado ao servidor...</p></section>`;
 if(!ecoState.eligible)return `<section class="card eco-shell eco-denied"><div class="k">CREDENCIAL FORA DO MAPA</div><h2>CINCO ÂNCORAS ATUAIS</h2><p>${esc(ecoState.reason)}</p><div class="term">ÂNCORAS ATUAIS: 5\nCAMADAS HISTÓRICAS: 6\nNENHUM SEXTO JOGO AUTORIZADO</div></section>`;
 if(!ecoState.released)return `<section class="card eco-shell eco-standby"><div class="eco-coherence"><b>12%</b><span>COERÊNCIA ECO</span></div><div><div class="k">PROTOCOLO ECO-W77 // STANDBY</div><h2>CINCO ÂNCORAS</h2><p>A PANI detectou cadeias residuais, mas o Diretor da Sessão ainda não liberou a reconstrução.</p><div class="term">ROTA INDIVIDUAL: ${ECO_META[me.crew_id]?.anchor||'—'}\nESTADO: SELADA\nSOLUÇÕES: SOMENTE NO SERVIDOR</div></div></section>`;
 let a=ecoState.anchor,m=ECO_META[a.crewId]||ECO_META[me.crew_id],key=`${a.crewId}:${a.phase}:${a.locked}:${ecoState.status}`;if(ecoDraft.phaseKey!==key)ecoDraft={phaseKey:key};if(ecoState.status==='complete')return ecoComplete(a,m);
 return `<section class="eco-protocol ${a.anchorId} ${a.interference?.type?'is-interfered':''}"><header class="card eco-header"><div><div class="k">PANI // PROTOCOLO ECO-W77</div><h2>${m.anchor} // ${m.game}</h2><p>${esc(me.display_name)} ↔ ${m.mirror} // ${m.verb}</p></div><div class="eco-head-metrics"><div><b>${ecoState.coherence}%</b><span>COERÊNCIA</span></div><div><b>${ecoState.locks}/5</b><span>LOCKS</span></div><div><b>${ecoState.globalPressure}</b><span>PRESSÃO</span></div></div></header>${ecoState.paused?'<div class="card eco-paused"><b>PROTOCOLO PAUSADO</b><span>Timers congelados. Progresso preservado.</span></div>':''}${a.interference?.type?`<div class="eco-interference" role="alert"><b>INTERFERÊNCIA ECO</b><span>${esc(a.interference.type.replaceAll('_',' ').toUpperCase())}</span></div>`:''}${ecoPhases(a)}${ecoState.status==='convergence'?ecoConvergence(a):ecoGame(a)}<footer class="card eco-footer">${ecoStability(a)}<div id="eco-ack" class="eco-ack" aria-live="polite">${esc(a.publicState?.serverAck||'SERVIDOR AGUARDANDO INPUT')}</div><div><span>AJUDA PANI: ${a.helpTokens}</span>${ecoBtn('USAR AJUDA',`ecoInput('use_help',{},this)`,'',a.helpTokens<1||a.locked)}</div></footer>${a.publicState?.hint?`<aside class="card eco-hint"><div class="k">AJUDA PANI</div><p>${esc(a.publicState.hint)}</p></aside>`:''}${a.crossClue||ecoState.crossClue?`<aside class="card eco-cross"><div class="k">PISTA CRUZADA</div><b>${esc(ecoState.crossClue||a.crossClue)}</b><p>Comunique este dado; a interpretação depende de outra âncora.</p></aside>`:''}</section>`;
}
function ecoGame(a){let body=a.crewId==='gilbert'?ecoGen(a):a.crewId==='eklay'?ecoOps(a):a.crewId==='christian'?ecoSec(a):a.crewId==='willy'?ecoMed(a):ecoInv(a);return `<article class="card eco-game"><div class="eco-game-title"><div><span>FASE ${a.phase} // ${ecoPhaseName(a.phase)}</span><h3>${esc(a.publicState.title)}</h3></div><em>${a.progress}%</em></div><p class="eco-objective">${esc(a.publicState.feedback)}</p>${body}</article>`}

function ecoGen(a){let s=a.publicState,n=Number(s.slots||4),g=ecoDraft.genGuess;if(!Array.isArray(g)||g.length!==n)g=ecoDraft.genGuess=Array(n).fill(s.values?.[0]||'A1');let selects=`<div class="gen-slots">${g.map((v,i)=>`<label><span>SLOT ${i+1}</span><select onchange="ecoDraft.genGuess[${i}]=this.value;this.closest('label').classList.add('selected')">${s.values.map(x=>`<option ${x===v?'selected':''}>${esc(x)}</option>`).join('')}</select><i></i></label>`).join('')}</div>`;let ver=s.lastFeedback?.verifiers?`<div class="gen-verifiers">${Object.entries(s.lastFeedback.verifiers).map(([k,v])=>`<div class="${v==='PASS'?'pass':'fail'}"><span>${k}</span><b>${v}</b></div>`).join('')}</div>`:'';let hist=(s.history||[]).slice(-6).reverse().map((x,i)=>`<div><span>#${s.history.length-i}</span><code>${x.guess.join(' · ')}</code><b>${x.feedback.exact} EXATOS / ${x.feedback.present} PRESENTES</b></div>`).join('')||'<em>NENHUMA TENTATIVA</em>';if(a.phase===4)return `${selects}<label class="eco-check"><input id="gen-separate" type="checkbox"> MANTER DESCRIÇÃO EM CAMADA SEPARADA</label>${ecoBtn('FIXAR VERDADE',`ecoInput('gen_fix',{support:ecoDraft.genGuess,separateDescription:$('#gen-separate').checked},this)`,'a')}`;if(a.phase===3)return `${selects}${ver}${ecoBtn('TESTAR LEITURA',`ecoInput('gen_test',{guess:ecoDraft.genGuess},this)`,'a')}<div class="gen-suspects">${s.verifiers.map(x=>ecoBtn(x,`ecoInput('gen_suspect',{verifier:'${x}'},this)`)).join('')}</div><div class="eco-history">${hist}</div>`;return `${selects}${ver}<div class="actions">${ecoBtn('TESTAR ASSINATURA',`ecoInput('gen_test',{guess:ecoDraft.genGuess},this)`,'a')}<span>TENTATIVAS ${s.history?.length||0}/${s.maxAttempts}</span></div><div class="eco-history">${hist}</div>`}

function ecoGlyph(p){return({straight:'━',elbow:'┗',bridge:'⟺'}[p?.piece]||'·')}
function ecoOps(a){let s=a.publicState,n=Number(s.gridSize||6),placed=s.placed||{},sel=ecoDraft.opsSelected||'',cells=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++){let k=`${r},${c}`,p=placed[k],sp=k===s.origin?'origin':k===s.destination?'target':k===s.apparentDestination?'phantom':'';cells.push(`<button class="ops-cell ${sp} ${p?'placed':''} ${sel===k?'selected':''}" style="--rot:${(p?.rot||0)*90}deg" onclick="ecoOpsCell('${k}',${!!p})"><span>${sp==='origin'?'P':sp==='target'?'R-3':sp==='phantom'?'R-3?':ecoGlyph(p)}</span></button>`)}if(a.phase===4)return `<div class="ops-nodes">${s.nodes.map((x,i)=>`<button class="${i<s.nodeIndex?'done':i===s.nodeIndex?'active':''}" onclick="ecoInput('ops_node',{node:'${x}'},this)"><span>NODE</span><b>${x}</b></button>`).join('')}</div>`;let queue=s.queue.map((x,i)=>`<div class="${i<s.queueIndex?'used':i===s.queueIndex?'next':''}"><i>${ecoGlyph({piece:x})}</i><span>${x}</span></div>`).join('');return `<div class="ops-layout"><div class="ops-board" style="--grid:${n}">${cells.join('')}</div><aside><div class="k">FILA DE PEÇAS</div><div class="ops-queue ${a.interference?.type==='blind_queue'?'blind':''}">${queue}</div>${s.buildDeadline?ecoDeadline(s.buildDeadline):''}<div class="ops-readout"><span>PEÇAS ${s.queueIndex}/${s.pathLength}</span><span>PULSO ${s.pulseIndex||0}/${s.pathLength}</span></div></aside></div><div class="actions">${ecoBtn('SEGURAR PEÇA',`ecoOpsHold()`,'',!sel)}${ecoBtn('VALIDAR ROTA',`ecoInput('ops_validate',{},this)`,'a')}</div>`}
function ecoOpsCell(cell,occupied){ecoDraft.opsSelected=cell;if(occupied)ecoInput('ops_rotate',{cell});else ecoInput('ops_place',{cell})}function ecoOpsHold(){if(ecoDraft.opsSelected)ecoInput('ops_hold',{cell:ecoDraft.opsSelected})}

function ecoSec(a){let s=a.publicState,n=s.graph||[],sel=ecoDraft.secSector||n[0]||'HUB',map=`<div class="sec-map">${n.map((x,i)=>`<button class="sec-node n${i} ${sel===x?'selected':''}" onclick="ecoDraft.secSector='${x}';render(true)"><i></i><b>${x}</b></button>`).join('')}<svg viewBox="0 0 100 60"><path d="M15 30L39 11L50 30L73 15M15 30L50 30L38 50L73 45M50 30L88 31"/></svg></div>`;if(a.phase===4)return `<div class="sec-timeline">${s.timeline.map((x,i)=>`<button class="${ecoDraft.secBlackbox===i?'selected':''}" onclick="ecoDraft.secBlackbox=${i};render(true)"><span>0${i+1}</span><b>${x}</b></button>`).join('')}</div>${ecoBtn('MARCAR PRIMEIRO IMPOSSÍVEL',`ecoInput('sec_blackbox',{index:ecoDraft.secBlackbox},this)`,'a',ecoDraft.secBlackbox==null)}`;let log=(s.moveLog||[]).map((x,i)=>`<span><i>0${i+1}</i>${x}</span>`).join('')||'<em>SEM DESLOCAMENTOS</em>';if(a.phase===1)return `${map}<div class="sec-controls"><b>SETOR: ${sel}</b>${ecoBtn('SCAN',`ecoInput('sec_scan',{sector:ecoDraft.secSector||'${sel}'},this)`,'a')}</div>`;if(a.phase===3)return `${map}<div class="sec-log">${log}</div><div class="actions">${ecoBtn('SCAN',`ecoInput('sec_scan',{sector:ecoDraft.secSector||'${sel}'},this)`,'a')}${ecoBtn('ACUSAR SALTO NO PONTO 03',`ecoInput('sec_accuse_jump',{index:2},this)`,'r')}</div>`;return `${map}<div class="sec-log">${log}</div><div class="sec-controls">${ecoBtn('SCAN',`ecoInput('sec_scan',{sector:ecoDraft.secSector||'${sel}'},this)`,'a')}${ecoBtn('CROSSCHECK',`ecoInput('sec_crosscheck',{a:'HUB',b:ecoDraft.secSector||'${sel}',sector:ecoDraft.secSector||'${sel}'},this)`)}${ecoBtn('LOCKDOWN',`ecoInput('sec_lockdown',{sector:ecoDraft.secSector||'${sel}'},this)`,'',!s.lockdowns)}${ecoBtn('CÂMERA',`ecoInput('sec_camera',{sector:ecoDraft.secSector||'${sel}'},this)`,'',!s.camera)}</div>`}

function ecoMed(a){let s=a.publicState,input=ecoDraft.medInput||[];ecoDraft.medInput=input;let pads=(s.channels||['pulse','resp','neural','tonus']).map(ch=>`<button class="med-pad ${ch}" onclick="ecoMedPad('${ch}')"><i></i><b>${({pulse:'PULSO',resp:'RESPIRAÇÃO',neural:'NEURAL',tonus:'TÔNUS'}[ch])}</b></button>`).join('');if(a.phase===3){let marks=ecoDraft.medMarkers;if(!Array.isArray(marks))marks=ecoDraft.medMarkers=[...(s.visualStarts||[])];return `<div class="med-traces">${s.tracks.map((x,i)=>`<label><span>${x}</span><i style="--start:${s.visualStarts[i]}%"></i><input type="range" min="10" max="70" value="${marks[i]}" oninput="ecoDraft.medMarkers[${i}]=Number(this.value);this.nextElementSibling.textContent=this.value+'%'"><b>${marks[i]}%</b></label>`).join('')}<div class="med-environment" style="--end:${s.environmentEnd}%">EVENTO AMBIENTAL</div></div><div class="med-conclusions">${ecoBtn('CAUSA AMBIENTAL',`ecoInput('med_markers',{markers:ecoDraft.medMarkers,conclusion:'environment'},this)`)}${ecoBtn('RESPOSTA ANTECIPADA',`ecoInput('med_markers',{markers:ecoDraft.medMarkers,conclusion:'anticipated'},this)`,'a')}${ecoBtn('DADO INSUFICIENTE',`ecoInput('med_markers',{markers:ecoDraft.medMarkers,conclusion:'insufficient'},this)`)}</div>`}return `<div class="med-console"><div class="med-pads">${pads}</div><aside><div class="k">SEQUÊNCIA REGISTRADA</div><div class="med-sequence">${input.map((x,i)=>`<span>${i+1}<b>${x.channel}</b></span>`).join('')||'<em>AGUARDANDO</em>'}</div><label class="eco-check"><input id="med-audio-off" type="checkbox" ${ecoDraft.audioOff?'checked':''} onchange="ecoDraft.audioOff=this.checked"> MODO SEM ÁUDIO</label>${ecoBtn('REPRODUZIR REFERÊNCIA',`ecoMedPlay()`)}</aside></div><div class="actions">${ecoBtn('LIMPAR',`ecoDraft.medInput=[];ecoDraft.medStart=0;render(true)`)}${ecoBtn(a.phase===4?'PRESERVAR BRUTO':'CONFIRMAR SEQUÊNCIA',`ecoMedSubmit()`,'a',!input.length)}</div>`}
function ecoMedPad(channel){let now=performance.now();if(!ecoDraft.medStart)ecoDraft.medStart=now;(ecoDraft.medInput||(ecoDraft.medInput=[])).push({channel,time:Math.round(now-ecoDraft.medStart)});render(true)}function ecoMedSubmit(){let a=ecoState.anchor,x=ecoDraft.medInput||[];if(a.phase===1)ecoInput('med_repeat',{sequence:x.map(v=>v.channel)});else if(a.phase===2)ecoInput('med_timed',{sequence:x});else ecoInput('med_preserve',{sequence:x.map(v=>v.channel),preserveRaw:true});ecoDraft.medInput=[];ecoDraft.medStart=0}function ecoMedPlay(){let s=ecoState.anchor.publicState,seq=ecoState.anchor.phase===4?s.displaySequence:s.sequence;(seq||[]).forEach((v,i)=>setTimeout(()=>{let ch=v.channel||v;document.querySelector(`.med-pad.${ch}`)?.classList.add('play');setTimeout(()=>document.querySelector(`.med-pad.${ch}`)?.classList.remove('play'),250)},Number(v.time??i*600)))}

function ecoInv(a){let s=a.publicState;if(a.phase===1){let as=ecoDraft.invAssignments||s.assignments||{};ecoDraft.invAssignments=as;return `<div class="inv-board">${s.cards.map(c=>`<article><b>${c.id}</b><p>${esc(c.text)}</p><select onchange="ecoDraft.invAssignments['${c.id}']=this.value;this.closest('article').classList.add('selected')"><option value="">CLASSIFICAR...</option>${s.operations.map(o=>`<option ${as[c.id]===o?'selected':''}>${o}</option>`).join('')}</select></article>`).join('')}</div>${ecoBtn('CONFIRMAR CLASSIFICAÇÃO',`ecoInput('inv_classify',{assignments:ecoDraft.invAssignments},this)`,'a')}`}
 if(a.phase===2){let pairs=ecoDraft.invPairs||s.pairs||[],sel=ecoDraft.invPairSelection||[];ecoDraft.invPairs=pairs;ecoDraft.invPairSelection=sel;return `<div class="inv-statements">${s.statements.map(c=>`<button class="${sel.includes(c.id)?'selected':''}" onclick="ecoInvSelect('${c.id}')"><b>${c.id}</b><span>${esc(c.text)}</span></button>`).join('')}</div><div class="inv-links">${pairs.map((p,i)=>`<span>${p[0]} ↔ ${p[1]}<button onclick="ecoDraft.invPairs.splice(${i},1);render(true)">×</button></span>`).join('')||'<em>SEM PARES</em>'}</div><div class="actions">${ecoBtn('CONECTAR SELEÇÃO',`ecoInvConnect()`,'',sel.length!==2)}${ecoBtn('TESTAR 4 PARES',`ecoInput('inv_pairs',{pairs:ecoDraft.invPairs},this)`,'a',pairs.length!==4)}</div>`}
 if(a.phase===3)return `<div class="inv-hypotheses">${s.hypotheses.map(h=>`<button class="${s.tested?.[h.id]?.toLowerCase()||''}" onclick="ecoInput('inv_hypothesis',{hypothesis:'${h.id}'},this)"><b>${h.title}</b><p>${h.prediction}</p><span>${s.tested?.[h.id]||'TESTAR PREVISÃO'}</span></button>`).join('')}</div>`;let linked=ecoDraft.invLinked||[];ecoDraft.invLinked=linked;return `<div class="inv-constellation"><div class="inv-center">SEM NOME</div>${s.outputs.map((x,i)=>`<button class="n${i} ${linked.includes(x)?'linked':''}" onclick="ecoDraft.invLinked=ecoDraft.invLinked.includes('${x}')?ecoDraft.invLinked.filter(v=>v!=='${x}'):[...ecoDraft.invLinked,'${x}'];render(true)">${x}</button>`).join('')}</div><label class="eco-check"><input id="inv-no-name" type="checkbox"> NÃO ATRIBUIR NOME OU SIGNIFICADO</label>${ecoBtn('FIXAR RELAÇÃO',`ecoInput('inv_fix',{outputs:ecoDraft.invLinked,noName:$('#inv-no-name').checked},this)`,'a',linked.length!==5)}`}
function ecoInvSelect(id){let s=ecoDraft.invPairSelection||[];ecoDraft.invPairSelection=s.includes(id)?s.filter(x=>x!==id):s.length<2?[...s,id]:s;render(true)}function ecoInvConnect(){let s=ecoDraft.invPairSelection||[];if(s.length===2){(ecoDraft.invPairs||(ecoDraft.invPairs=[])).push([...s]);ecoDraft.invPairSelection=[];render(true)}}

function ecoConvergence(a){let c=ecoState.convergence||{};if(c.state==='recalibrating')return `<article class="card eco-convergence"><div class="eco-sync-core"><b>${c.readyCount||0}/5</b><span>RECALIBRANDO</span></div><div><h3>NENHUMA ÂNCORA FOI PERDIDA</h3><p>Uma nova janela abrirá automaticamente. Todos os locks permanecem.</p>${ecoDeadline(c.retryAt)}</div></article>`;return `<article class="card eco-convergence"><div class="eco-sync-core"><b>${c.readyCount||0}/5</b><span>READY</span></div><div><div class="k">CONVERGÊNCIA // 12 SEGUNDOS</div><h3>${ECO_META[a.crewId].verb}</h3><p>${({gilbert:'Mantenha NØ pressionado por 3 segundos.',eklay:'Ative NODE A, B e C.',christian:'Selecione Ø-C.',willy:'Reproduza pulse, resp, neural, tonus.',aliya:'Confirme sem atribuir nome.'}[a.crewId])}</p>${ecoConvControl(a.crewId)}</div>${ecoDeadline(c.windowEnd)}</article>`}
function ecoConvControl(c){if(c==='gilbert')return `<button class="eco-hold" onpointerdown="ecoHoldStart(this)" onpointerup="ecoHoldEnd(this)" onpointercancel="ecoHoldCancel(this)"><i></i><b>NØ</b><span>MANTER 3 S</span></button>`;if(c==='eklay')return `<div class="ops-nodes">${['A','B','C'].map(x=>`<button onclick="ecoConvNode('${x}')"><b>${x}</b></button>`).join('')}</div>${ecoBtn('READY',`ecoInput('convergence',{nodes:ecoDraft.convNodes},this)`,'a',(ecoDraft.convNodes||[]).join('')!=='ABC')}`;if(c==='christian')return ecoBtn('SETOR Ø-C',`ecoInput('convergence',{sector:'Ø-C'},this)`,'a');if(c==='willy')return ecoBtn('PRESERVAR SEQUÊNCIA CRUA',`ecoInput('convergence',{sequence:['pulse','resp','neural','tonus']},this)`,'a');return ecoBtn('CONFIRMAR NODO SEM NOME',`ecoInput('convergence',{noName:true},this)`,'a')}
function ecoConvNode(x){let a=ecoDraft.convNodes||[];if(a.length<3)a.push(x);ecoDraft.convNodes=a;render(true)}function ecoHoldStart(b){ecoDraft.holdAt=performance.now();b.classList.add('holding')}function ecoHoldCancel(b){ecoDraft.holdAt=0;b.classList.remove('holding')}function ecoHoldEnd(b){let ms=Math.round(performance.now()-(ecoDraft.holdAt||performance.now()));ecoHoldCancel(b);if(ms<3000)return toast('MANTENHA NØ POR 3 SEGUNDOS',true);ecoInput('convergence',{marker:'NØ',holdMs:ms},b)}
function ecoComplete(a,m){let x=ecoState.sixthLayer||{};return `<section class="eco-protocol complete"><article class="card eco-complete"><div class="eco-sync-core success"><b>5/5</b><span>SYNC</span></div><div><div class="k">PROTOCOLO ECO-W77 // ESTÁVEL</div><h2>UMA LÓGICA RECONSTRUÍDA</h2><p>Cinco fontes independentes concordam: tecnologia, corpo, matéria, segurança e relações pertencem ao mesmo evento.</p><div class="eco-output"><span>SUA ÂNCORA // ${m.anchor}</span><b>${esc(a.output||a.publicState.output)}</b></div></div></article><article class="card eco-sixth"><div><b>${x.historicalLayers||6}</b><span>CAMADAS HISTÓRICAS</span></div><div><div class="k">CONTAGEM INCONSISTENTE</div><h3>CAMADA ENV // SEM EQUIVALENTE ATUAL</h3><p>Âncoras ativas: 5. Uma credencial ausente do elenco consciente deixou resíduos.</p><div class="term">NOME: NÃO AUTORIZADO\nINTERPRETAÇÃO: PENDENTE\nMEMÓRIA: INSUFICIENTE</div></div></article></section>`}

function ecoBind(){ecoClock();if(!window.__ecoClock)window.__ecoClock=setInterval(ecoClock,100)}function ecoClock(){document.querySelectorAll('[data-eco-deadline]').forEach(e=>{let ms=Math.max(0,new Date(e.dataset.ecoDeadline).getTime()-Date.now());e.textContent=(ms/1000).toFixed(1)+' S';e.classList.toggle('critical',ms<4000)})}

async function ecoMasterRefresh(repaint=true){if(!MASTER||!pin)return ecoMasterState;try{ecoMasterState=await rpc('pani_eco_master_status',{p_pin:pin});ecoMasterInject();ecoMasterRender(!!repaint)}catch(e){console.error('eco master',e)}return ecoMasterState}
async function ecoMasterAction(action,payload={},question=''){let go=async()=>{try{ecoMasterState=await rpc('pani_eco_master_action',{p_pin:pin,p_action:action,p_payload:payload});ecoMasterRender();toast('ECO-W77 // CONTROLE REGISTRADO')}catch(e){toast(ecoErr(e),true)}};if(question)confirmBox('ECO-W77',question,go);else await go()}
function ecoMasterInject(){if(!MASTER||!$('#mapp')||$('#eco-master'))return;$('#mapp').insertAdjacentHTML('beforeend','<section id="eco-master" class="card eco-master"><div class="k">MASTER // PROTOCOLO ECO-W77</div><h2>CINCO ÂNCORAS</h2><div id="eco-master-body">SINCRONIZANDO...</div></section>')}
function ecoMasterCaptureUi(b){if(!b)return;ecoMasterUiDraft.selects={...ecoMasterUiDraft.selects};b.querySelectorAll('select[id]').forEach(x=>ecoMasterUiDraft.selects[x.id]=x.value);ecoMasterUiDraft.details=[...b.querySelectorAll('details')].map(x=>x.open)}
function ecoMasterRestoreUi(b){if(!b)return;b.querySelectorAll('select[id]').forEach(x=>{let v=ecoMasterUiDraft.selects[x.id];if(v!=null&&[...x.options].some(o=>o.value===String(v)))x.value=String(v)});b.querySelectorAll('details').forEach((x,i)=>x.open=!!ecoMasterUiDraft.details[i])}
function ecoMasterRender(force=false){let b=$('#eco-master-body'),s=ecoMasterState;if(!b||!s)return false;let key=paniDataKey(s);if(!force&&key===ecoMasterPaintKey)return false;if(!force&&paniEditing(b))return false;ecoMasterCaptureUi(b);let controls=!s.released?`<label>SEED<select id="eco-seed">${Array.from({length:10},(_,i)=>`<option value="${i+1}">SEED ${i+1}</option>`).join('')}</select></label>${ecoBtn('INICIAR CINCO ÂNCORAS',`ecoMasterAction('start',{seed:Number($('#eco-seed').value)},'Liberar as cinco rotas?')`,'a')}`:`<div class="actions">${ecoBtn(s.paused?'RETOMAR':'PAUSAR',`ecoMasterAction('${s.paused?'resume':'pause'}')`,s.paused?'a':'')}${ecoBtn('OCULTAR',`ecoMasterAction('stop',{},'Ocultar sem apagar progresso?')`)}${ecoBtn('RESETAR',`ecoMasterAction('reset',{seed:${s.seedId}},'Apagar somente o progresso ECO?')`,'r')}</div>`;b.innerHTML=`<div class="eco-master-status"><div><span>ESTADO</span><b>${s.status}</b></div><div><span>COERÊNCIA</span><b>${s.coherence}%</b></div><div><span>PRESENÇA</span><b>${s.presenceCharges}/5</b></div><div><span>RUPTURA</span><b>${s.ruptureAvailable?'PRONTA':'USADA'}</b></div></div>${controls}<div class="eco-master-anchors">${(s.anchors||[]).map(a=>ecoMasterAnchor(a,s)).join('')}</div>${ecoMasterRoute(s)}${s.status==='convergence'?ecoMasterConv(s):''}<details><summary>LOG ECO // ${s.logs?.length||0}</summary><div class="term">${(s.logs||[]).slice(0,40).map(x=>`${new Date(x.createdAt).toLocaleTimeString()} :: ${x.actor} :: ${x.type}`).join('\n')}</div></details>`;ecoMasterPaintKey=key;ecoMasterRestoreUi(b);return true}
function ecoMasterAnchor(a,s){let opts=(ECO_INTERFERENCE[a.crewId]||[]).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');return `<article class="eco-master-anchor ${a.locked?'locked':''}"><header><span>${ECO_META[a.crewId].anchor}</span><b>${ECO_NAMES[a.crewId]}</b><i>${a.joined?'LINK':'OFFLINE'}</i></header><div class="eco-ma-progress"><span style="--p:${a.progress}%"></span></div><p>FASE ${a.phase} // EST ${a.stability}/3 // AJUDA ${a.helpTokens}</p><div class="actions"><select id="eco-int-${a.crewId}">${opts}</select>${ecoBtn('INTERFERIR',`ecoMasterAction('interfere',{crewId:'${a.crewId}',type:$('#eco-int-${a.crewId}').value})`,'r',a.phase===1||a.locked||s.presenceCharges<1)}${ecoBtn('+ AJUDA',`ecoMasterAction('grant_help',{crewId:'${a.crewId}'})`,'',a.locked)}${ecoBtn('REDUZIR',`ecoMasterAction('reduce_phase',{crewId:'${a.crewId}'})`,'',a.locked)}</div></article>`}
function ecoMasterRoute(s){let route=s.secretState?.secRoute||['HUB','SEC','OPS','MED','INV','GEN'],nodes=['HUB','SEC','OPS','MED','INV','GEN'];return `<details class="eco-master-route"><summary>SEC // ROTA SECRETA</summary><div>${route.map((x,i)=>`<select id="eco-route-${i}">${nodes.map(n=>`<option ${n===x?'selected':''}>${n}</option>`).join('')}</select>`).join('<span>→</span>')}</div>${ecoBtn('VALIDAR ROTA',`ecoMasterAction('configure_sec',{nodes:[0,1,2,3,4,5].map(i=>$('#eco-route-'+i).value)})`,'a')}</details>`}
function ecoMasterConv(s){return `<section class="eco-master-convergence"><h3>CONVERGÊNCIA // ${s.convergence.readyCount||0}/5</h3>${ecoDeadline(s.convergence.windowEnd||s.convergence.retryAt)}<select id="eco-rupture">${s.anchors.map(a=>`<option value="${a.crewId}">${ECO_NAMES[a.crewId]}</option>`).join('')}</select>${ecoBtn('RUPTURA',`ecoMasterAction('rupture',{crewId:$('#eco-rupture').value},'Consumir o único uso?')`,'r',!s.ruptureAvailable||s.convergence.state!=='open')}</section>`}
setInterval(()=>{if(MASTER&&pin){ecoMasterInject();if(ecoMasterState)ecoMasterRender(false)}},3000);
