'use strict';

let mrCrewReports=[],mcCrewCodes=[],mrMasterReports=[],mcMasterCodes=[],mcMasterFiles=[],mcEditId=null,mrMasterReady=false;

function missionDate(v){try{return new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'medium'})}catch{return String(v||'—')}}
function missionShort(v,n=160){v=String(v||'');return v.length>n?v.slice(0,n)+'…':v}

/* ========================= PLAYER // REPORTS ========================= */
function missionReportPage(){
  if(!mrCrewReports.length)setTimeout(()=>missionCrewReportsRefresh(false),0);
  return `<div class="card mrpage">
    <div class="k">PANI // REGISTRO DE MISSÃO</div>
    <h2>RELATÓRIO DO DIA</h2>
    <p class="mut">Registre observações, incidentes, descobertas e informações relevantes do turno. O envio é permanente e será encaminhado ao Diretor da Sessão.</p>
    <div class="mrnotice"><b>IDENTIFICAÇÃO AUTOMÁTICA</b><span>${esc(me?.display_name||'TRIPULANTE')} // W77-02</span></div>
    <textarea id="mrtext" maxlength="12000" placeholder="Descreva os acontecimentos do dia..." oninput="missionReportCount()"></textarea>
    <div class="mrfoot"><span id="mrcount">0 / 12000</span><button id="mrsend" class="btn a" onclick="missionSubmitReport()">ENVIAR RELATÓRIO</button></div>
    <hr class="sep"><div class="mrhead"><div><div class="k">ARQUIVO PESSOAL</div><h3>RELATÓRIOS ENVIADOS</h3></div><button class="btn" onclick="missionCrewReportsRefresh(true)">SINCRONIZAR</button></div>
    <div id="mrhistory">${missionCrewReportHistory()}</div>
  </div>`;
}
function missionReportCount(){let e=$('#mrtext'),c=$('#mrcount');if(e&&c)c.textContent=e.value.length+' / 12000'}
function missionCrewReportHistory(){if(!mrCrewReports.length)return `<div class="mrzero">Nenhum relatório enviado por esta credencial.</div>`;return mrCrewReports.map(r=>`<article class="mrhistory"><div><b>RELATÓRIO #${r.id}</b><span>${missionDate(r.sent_at)}</span></div><p>${esc(missionShort(r.report_text,260))}</p><small class="${r.read_at?'ok':'warn'}">${r.read_at?'RECEBIDO E CONSULTADO':'RECEBIDO PELA PANI'}</small></article>`).join('')}
async function missionCrewReportsRefresh(rerender=true){if(MASTER||!tok||!me)return;try{mrCrewReports=await rpc('pani_crew_reports',{p_token:tok,p_limit:8})||[];if(rerender&&view==='report')render(true)}catch(e){console.error('report history',e)}}
async function missionSubmitReport(){let t=$('#mrtext')?.value||'';if(!t.length)return toast('O relatório está vazio.',true);let b=$('#mrsend');if(b){b.disabled=true;b.textContent='TRANSMITINDO...'}try{let r=await rpc('pani_submit_report',{p_token:tok,p_report:t});$('#mrtext').value='';missionReportCount();await missionCrewReportsRefresh(false);toast('PANI // RELATÓRIO ENVIADO E ARQUIVADO');render(true)}catch(e){let m=String(e?.message||'');toast(m.includes('report_too_long')?'Relatório excede 12000 caracteres.':'Falha ao enviar relatório.',true)}finally{if(b){b.disabled=false;b.textContent='ENVIAR RELATÓRIO'}}}

/* ========================= PLAYER // CREDENTIALS ========================= */
function missionCredentialPage(){
  if(!mcCrewCodes.length)setTimeout(()=>missionCrewCredentialRefresh(false),0);
  return `<div class="card mcpage">
    <div class="k">PANI // AUTORIZAÇÃO EXTERNA</div><h2>CREDENCIAIS</h2>
    <p class="mut">Insira exatamente o código recebido. Credenciais podem conter letras, números, espaços e caracteres especiais e são sensíveis a maiúsculas/minúsculas.</p>
    <div class="mccodebox"><input id="mccode" autocomplete="off" spellcheck="false" placeholder="INSERIR CREDENCIAL" onkeydown="if(event.key==='Enter')missionRedeemCredential()"><button id="mcredeem" class="btn a" onclick="missionRedeemCredential()">VALIDAR CREDENCIAL</button></div>
    <div id="mcresult" class="term">PANI aguardando credencial.</div>
    <hr class="sep"><div class="k">AUTORIZAÇÕES ADQUIRIDAS</div><div id="mcauths" class="mcauths">${missionCrewCredentialList()}</div>
  </div>`;
}
function missionCrewCredentialList(){if(!mcCrewCodes.length)return `<div class="mrzero">Nenhuma autorização adicional registrada.</div>`;return mcCrewCodes.map(c=>`<article class="mcauth"><span class="mcauthdot"></span><div><b>${esc(c.label||'CREDENCIAL')}</b><span>${esc(c.file_name||'ARQUIVO NÃO CATALOGADO')}</span><small>LIBERADO EM ${missionDate(c.unlocked_at)}</small></div></article>`).join('')}
async function missionCrewCredentialRefresh(rerender=true){if(MASTER||!tok||!me)return;try{mcCrewCodes=await rpc('pani_crew_credential_status',{p_token:tok})||[];if(rerender&&view==='cred')render(true)}catch(e){console.error('credential status',e)}}
async function missionRedeemCredential(){let input=$('#mccode'),code=input?.value??'';if(code.length<1)return toast('Informe uma credencial.',true);let b=$('#mcredeem');if(b){b.disabled=true;b.textContent='VALIDANDO...'}try{let r=await rpc('pani_crew_redeem_credential',{p_token:tok,p_code:code});if(!r?.ok){$('#mcresult').textContent='CREDENCIAL NÃO RECONHECIDA // ACESSO NEGADO';return toast('Credencial não reconhecida.',true)}input.value='';await missionCrewCredentialRefresh(false);if(r.new_unlock){$('#mcresult').textContent='SINAL NÃO CATALOGADO DETECTADO.';missionTransmissionGlitch(r.transmission_text||'UMA TRANSMISSÃO INESPERADA ACONTECEU.',r.file_name||'ARQUIVO RECUPERADO')}else{$('#mcresult').textContent='CREDENCIAL JÁ ASSOCIADA A ESTA IDENTIDADE.';toast('Credencial já autorizada.')}}catch(e){toast('Falha ao validar credencial.',true)}finally{if(b){b.disabled=false;b.textContent='VALIDAR CREDENCIAL'}}}

function missionTransmissionGlitch(message,fileName){let o=$('#mcsignal');if(!o)return;o.querySelector('.mcsignalmsg').textContent=String(message||'UMA TRANSMISSÃO INESPERADA ACONTECEU.').toUpperCase();o.querySelector('.mcsignalfile').textContent=fileName?`PACOTE RECEBIDO // ${fileName}`:'PACOTE DE DADOS RECEBIDO';o.classList.remove('hidden');document.body.classList.add('mcshaking');setTimeout(()=>o.classList.add('phase2'),650);setTimeout(()=>{o.classList.add('hidden');o.classList.remove('phase2');document.body.classList.remove('mcshaking');if(typeof paniCrewFilesRefresh==='function')paniCrewFilesRefresh(false);view='files';render(true)},3400)}

/* ========================= MASTER // REPORTS ========================= */
async function missionMasterReportsRefresh(){if(!MASTER||!pin)return;try{mrMasterReports=await rpc('pani_master_reports',{p_pin:pin,p_limit:500})||[];missionMasterReportsRender()}catch(e){console.error('master reports',e)}}
function missionMasterReportsRender(){let box=$('#mrmasterlist');if(!box)return;let crew=$('#mrfiltercrew')?.value||'all',status=$('#mrfilterstatus')?.value||'all';let arr=mrMasterReports.filter(r=>(crew==='all'||r.crew_id===crew)&&(status==='all'||(status==='unread'?!r.read_at:!!r.read_at)));let unread=mrMasterReports.filter(r=>!r.read_at).length;let badge=$('#mrunread');if(badge)badge.textContent=unread?`${unread} NÃO LIDO${unread===1?'':'S'}`:'TUDO CONSULTADO';box.innerHTML=arr.length?arr.map(r=>`<article class="mrmasteritem ${r.read_at?'':'unread'}" onclick="missionMasterOpenReport(${r.id})"><div class="mravatar">${esc((r.crew_name||'?').split(/\s+/).map(x=>x[0]).slice(0,2).join(''))}</div><div class="mrmasterbody"><div><b>${esc(r.crew_name)}</b><span>RELATÓRIO #${r.id}</span></div><p>${esc(missionShort(r.report_text,220))}</p><small>${missionDate(r.sent_at)} // ${esc(r.mission_role||r.occupation||'TRIPULANTE')}</small></div><span class="mrstate ${r.read_at?'read':'new'}">${r.read_at?'LIDO':'NOVO'}</span></article>`).join(''):`<div class="mrzero">Nenhum relatório corresponde ao filtro.</div>`}
function missionMasterFilter(){missionMasterReportsRender()}
async function missionMasterOpenReport(id){let r=mrMasterReports.find(x=>x.id===id);if(!r)return;$('#mrmodalname').textContent=r.crew_name;$('#mrmodalmeta').textContent=`RELATÓRIO #${r.id} // ${missionDate(r.sent_at)} // ${r.mission_role||r.occupation||'TRIPULANTE'}`;$('#mrmodaltext').textContent=r.report_text;$('#mrmodal').classList.remove('hidden');if(!r.read_at){try{await rpc('pani_master_report_read',{p_pin:pin,p_report:r.id,p_read:true});r.read_at=new Date().toISOString();missionMasterReportsRender()}catch{}}}
function missionMasterCloseReport(){$('#mrmodal').classList.add('hidden')}
async function missionMasterToggleUnread(){let id=Number($('#mrmodalmeta').textContent.match(/#(\d+)/)?.[1]||0);if(!id)return;try{await rpc('pani_master_report_read',{p_pin:pin,p_report:id,p_read:false});let r=mrMasterReports.find(x=>x.id===id);if(r)r.read_at=null;missionMasterReportsRender();missionMasterCloseReport();toast('Relatório marcado como não lido.')}catch{toast('Falha ao atualizar relatório.',true)}}

/* ========================= MASTER // CREDENTIALS ========================= */
async function missionMasterCodesRefresh(){if(!MASTER||!pin)return;try{let [codes,files]=await Promise.all([rpc('pani_master_access_codes',{p_pin:pin}),rpc('pani_master_files',{p_pin:pin})]);mcMasterCodes=codes||[];mcMasterFiles=(files||[]).filter(f=>f.storage_path&&['available','encrypted'].includes(f.status));missionMasterCodeFormFiles();missionMasterCodesRender()}catch(e){console.error('master access codes',e)}}
function missionMasterCodeFormFiles(){let s=$('#mcfile');if(!s)return;let current=s.value;s.innerHTML='<option value="">SELECIONE UM DOCUMENTO</option>'+mcMasterFiles.map(f=>`<option value="${f.id}">${esc(f.display_name)} // ${String(f.status).toUpperCase()}</option>`).join('');if(current)s.value=current}
function missionMasterCodesRender(){let box=$('#mcmasterlist');if(!box)return;box.innerHTML=mcMasterCodes.length?mcMasterCodes.map(c=>`<article class="mcmasteritem ${c.enabled?'':'disabled'}"><div><div class="mccredhead"><b>${esc(c.label)}</b><span class="${c.enabled?'ok':'mut'}">${c.enabled?'ATIVA':'DESATIVADA'}</span></div><code>${esc(c.code_value)}</code><p>${esc(c.file_name)}</p><small>${c.unlock_count||0} desbloqueio(s) // ${missionDate(c.created_at)}</small></div><div class="actions"><button class="btn" onclick="missionMasterEditCode('${c.id}')">EDITAR</button><button class="btn r" onclick="missionMasterDeleteCode('${c.id}')">EXCLUIR</button></div></article>`).join(''):`<div class="mrzero">Nenhuma credencial narrativa cadastrada.</div>`}
function missionMasterCodeReset(){mcEditId=null;$('#mclabel').value='';$('#mccodeadmin').value='';$('#mcfile').value='';$('#mcmessage').value='UMA TRANSMISSÃO INESPERADA ACONTECEU.';$('#mcenabled').checked=true;$('#mccodeadmin').placeholder='DIGITE O CÓDIGO EXATO';$('#mcsave').textContent='CADASTRAR CREDENCIAL';$('#mceditnote').textContent='O documento selecionado ficará invisível até a credencial ser validada.'}
function missionMasterEditCode(id){let c=mcMasterCodes.find(x=>x.id===id);if(!c)return;mcEditId=id;$('#mclabel').value=c.label||'';$('#mccodeadmin').value='';$('#mccodeadmin').placeholder='DEIXE VAZIO PARA MANTER O CÓDIGO ATUAL';$('#mcfile').value=c.file_id||'';$('#mcmessage').value=c.transmission_text||'UMA TRANSMISSÃO INESPERADA ACONTECEU.';$('#mcenabled').checked=!!c.enabled;$('#mcsave').textContent='SALVAR ALTERAÇÕES';$('#mceditnote').textContent=`EDITANDO: ${c.code_value}`;$('#mcmaster').scrollIntoView({behavior:'smooth',block:'start'})}
async function missionMasterSaveCode(){let label=$('#mclabel').value,code=$('#mccodeadmin').value,file=$('#mcfile').value,msg=$('#mcmessage').value,en=$('#mcenabled').checked;if(!file)return toast('Selecione o documento que será liberado.',true);if(!mcEditId&&!code.length)return toast('Digite a credencial.',true);let payload={id:mcEditId||'',label,file_id:file,transmission_text:msg,enabled:en};if(code.length)payload.code=code;let b=$('#mcsave');b.disabled=true;try{await rpc('pani_master_access_code_upsert',{p_pin:pin,p_payload:payload});missionMasterCodeReset();await missionMasterCodesRefresh();if(typeof pfMasterRefresh==='function')pfMasterRefresh();toast('Credencial cadastrada. Documento protegido.')}catch(e){let m=String(e?.message||'');toast(m.includes('file_not_ready')?'O documento precisa estar íntegro e possuir arquivo físico.':m.includes('credential_code_or_file_exists')?'Esse código ou documento já possui uma credencial.':'Falha ao salvar credencial.',true)}finally{b.disabled=false}}
function missionMasterDeleteCode(id){let c=mcMasterCodes.find(x=>x.id===id);confirmBox('Excluir credencial?',`O documento ${c?.file_name||''} voltará à configuração de acesso anterior.`,async()=>{try{await rpc('pani_master_access_code_delete',{p_pin:pin,p_access_code:id});await missionMasterCodesRefresh();if(typeof pfMasterRefresh==='function')pfMasterRefresh();toast('Credencial excluída.')}catch{toast('Falha ao excluir credencial.',true)}})}

function missionInject(){
  if(!$('#mcsignal'))document.body.insertAdjacentHTML('beforeend',`<div id="mcsignal" class="mcsignal hidden"><div class="mcnoise"></div><div class="mcscan"></div><div class="mcsignalcore"><div class="mcsigalt">SIGNAL INTERRUPT // SOURCE UNKNOWN</div><div class="mcsignalmsg">UMA TRANSMISSÃO INESPERADA ACONTECEU.</div><div class="mcsignalfile">PACOTE DE DADOS RECEBIDO</div></div></div>`);
  if(!$('#mrmodal'))document.body.insertAdjacentHTML('beforeend',`<div id="mrmodal" class="modalback hidden"><div class="card mrmodal"><div class="k">MASTER // RELATÓRIO RECEBIDO</div><h2 id="mrmodalname"></h2><p id="mrmodalmeta" class="mut"></p><pre id="mrmodaltext"></pre><div class="actions"><button class="btn" onclick="missionMasterToggleUnread()">MARCAR NÃO LIDO</button><button class="btn a" onclick="missionMasterCloseReport()">FECHAR</button></div></div></div>`);
  if(MASTER&&!$('#mrmaster')){$('#mapp').insertAdjacentHTML('beforeend',`<section id="mrmaster" class="card mrmaster"><div class="mrhead"><div><div class="k">MASTER // CAIXA DE ENTRADA</div><h2>RELATÓRIOS DA TRIPULAÇÃO</h2><p class="mut">Registros enviados pelos terminais individuais. O horário é registrado pelo servidor no momento do recebimento.</p></div><span id="mrunread" class="pill">—</span></div><div class="mrmasterfilters"><select id="mrfiltercrew" onchange="missionMasterFilter()"><option value="all">TODOS OS TRIPULANTES</option>${[['gilbert','Gilbert'],['willy','Willy'],['viego','Viego'],['alice','Alice'],['eklay','Eklay'],['christian','Christian']].map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select><select id="mrfilterstatus" onchange="missionMasterFilter()"><option value="all">TODOS</option><option value="unread">NÃO LIDOS</option><option value="read">LIDOS</option></select><button class="btn" onclick="missionMasterReportsRefresh()">ATUALIZAR</button></div><div id="mrmasterlist" class="mrmasterlist"><div class="mut">Aguardando autenticação...</div></div></section>`);
    $('#mapp').insertAdjacentHTML('beforeend',`<section id="mcmaster" class="card mcmaster"><div class="mrhead"><div><div class="k">MASTER // MATRIZ DE CREDENCIAIS</div><h2>CREDENCIAIS & TRANSMISSÕES</h2><p class="mut">Cadastre um código livre e associe a um documento. Enquanto a credencial estiver ativa, o documento fica exclusivo para quem validar o código.</p></div><button class="btn" onclick="missionMasterCodeReset()">NOVA CREDENCIAL</button></div><div class="mcmastergrid"><div class="mccreate"><label>Identificação da credencial<input id="mclabel" placeholder="ex.: PACOTE ROSETA // 01"></label><label>Código exato<input id="mccodeadmin" autocomplete="off" spellcheck="false" placeholder="DIGITE O CÓDIGO EXATO"></label><p class="small warn">Sensível a maiúsculas/minúsculas. Letras, números, espaços e caracteres especiais são aceitos.</p><label>Documento exclusivo<select id="mcfile"><option value="">SELECIONE UM DOCUMENTO</option></select></label><label>Mensagem da interferência<textarea id="mcmessage">UMA TRANSMISSÃO INESPERADA ACONTECEU.</textarea></label><label class="mccheck"><input id="mcenabled" type="checkbox" checked> CREDENCIAL ATIVA</label><p id="mceditnote" class="small mut">O documento selecionado ficará invisível até a credencial ser validada.</p><button id="mcsave" class="btn a" onclick="missionMasterSaveCode()">CADASTRAR CREDENCIAL</button></div><div><div id="mcmasterlist" class="mcmasterlist"><div class="mut">Aguardando autenticação...</div></div></div></div></section>`)}
}

missionInject();
setInterval(()=>{if(MASTER&&pin&&!document.hidden){if(!mrMasterReady){mrMasterReady=true;missionMasterReportsRefresh();missionMasterCodesRefresh()}else missionMasterReportsRefresh()}},5500);
