'use strict';
const sepulcroUnlockedPage=sepulcroPage;
sepulcroPage=function(){return sepReleased()?sepulcroUnlockedPage():stationSectorPage()};
function render(force=false){if(!me)return;let f=fingerprint();if(!force&&f===fp){alertRender();return}capDraft();fp=f;alertRender();let html=view==='dash'?dash():view==='sepulcro'?sepulcroPage():view==='sector'?stationSectorPage():view==='pani'?pani():view==='files'?files():creds();$('#view').innerHTML=html;putDraft();navRender();bind()}
async function status(){try{prog=await rpc('pani_crew_status',{p_token:tok})||{}}catch(e){console.warn('legacy status unavailable',e);prog={}}await sepulcroCrewRefresh(false);return prog}
function crewNavMarkup(){let special=sepReleased()?'<button class="btn" data-v="sepulcro">PORTAS ENTERRADAS</button>':'<button class="btn" data-v="sector">SETOR W77-01</button>';return `<button class="btn" data-v="dash">VISÃO GERAL</button>${special}<button class="btn" data-v="pani">PANI</button><button class="btn" data-v="files">ARQUIVOS</button><button class="btn" data-v="cred">CREDENCIAIS</button>`}
function crewSyncNav(force=false){if(MASTER)return;let n=$('#nav');if(!n)return;let mode=sepReleased()?'released':'routine';if(!force&&n.dataset.sepMode===mode)return;n.dataset.sepMode=mode;n.innerHTML=crewNavMarkup();document.querySelectorAll('[data-v]').forEach(b=>b.onclick=async()=>{view=b.dataset.v;if(view==='sepulcro'){if(!sepReleased()){view='sector'}else await sepulcroCrewRefresh(true)}render(true)});if(!sepReleased()&&view==='sepulcro')view='sector';navRender()}
function bind(){let e;if((e=$('#openSepulcro')))e.onclick=async()=>{if(!sepReleased()){view='sector';return render(true)}view='sepulcro';await sepulcroCrewRefresh(true);render(true)};if(view==='pani'&&$('#ask'))$('#ask').onclick=()=>{let q=$('#q').value.toLowerCase(),k=sectorKey(),a;if(!sepReleased()){a=q.includes('quant')?`Existem ${state.occupancy} assinaturas biométricas detectadas na estação.`:q.includes('funç')||q.includes('cargo')?`${me.display_name}: ${me.mission_role}. Setor: ${NL[k]} // ${N[k]}.`:q.includes('porta')||q.includes('sepul')||q.includes('acesso')?'Nenhuma ocorrência extraordinária de autorização está ativa para esta credencial.':q.includes('energia')?`PANI CORE: ${state.system_health?.pani??100}%. Rotina de estação dentro dos parâmetros autorizados.`:q.includes('transmiss')?(state.transmission?'TRANSMISSION: CONNECTED. Origem não catalogada.':'Nenhuma transmissão externa catalogada neste momento.'):'Solicitação registrada. Não há resposta adicional autorizada para esta credencial.'}else{a=q.includes('quant')?`Existem ${state.occupancy} assinaturas biométricas detectadas na estação.`:q.includes('funç')||q.includes('cargo')?`${me.display_name}: ${me.mission_role}. Setor: ${NL[k]} // ${N[k]}.`:q.includes('sepul')||q.includes('porta')?`Sua credencial é válida. O acesso de ${NL[k]} ${solved(k)?'foi restaurado':'não existe no diretório normal. A camada de A. Dena exige uma prova semântica.'}`:q.includes('traduz')||q.includes('sinal')?'PANI pode correlacionar suportes e reconstruir arquivos. Tradução automática do idioma não está autorizada.':q.includes('transmiss')?(state.transmission?'TRANSMISSION: CONNECTED. Origem não catalogada.':'Nenhuma transmissão externa catalogada neste momento.'):'Solicitação registrada. Não há resposta autorizada para esta credencial.'}$('#ans').textContent=a};if(view==='cred'&&$('#crs'))$('#crs').onclick=async()=>{try{let r=await rpc('pani_crew_register_credential',{p_token:tok,p_code:$('#cr').value});await status();toast(r.ok?'Credencial registrada.':'Credencial não reconhecida.',!r.ok);render(true)}catch{toast('Falha ao registrar credencial.',true)}}}
function sepReleaseReveal(){if(MASTER||$('#sepreveal'))return;if(!$('#seprevealstyle'))document.head.insertAdjacentHTML('beforeend',`<style id="seprevealstyle">.sep-release-reveal{position:fixed;inset:0;z-index:200;background:#010609f2;display:grid;place-items:center;overflow:hidden}.sep-release-reveal:before{content:'';position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 3px,#30d3b306 3px 4px);animation:sepScan 7s linear infinite}.sep-release-noise{position:absolute;inset:-30%;background:radial-gradient(circle at 50% 50%,#31d3b31a,transparent 38%),linear-gradient(90deg,transparent 49.7%,#31d3b320 50%,transparent 50.3%);transform:rotate(-7deg);animation:sepNoise .18s steps(2) infinite}.sep-release-core{position:relative;width:min(720px,88vw);border:1px solid var(--a);background:#061116f7;padding:28px;border-radius:14px;box-shadow:0 0 70px #31d3b32b}.sep-release-core h1{font-size:clamp(28px,6vw,54px);margin:8px 0 18px}.sep-release-core b{color:var(--red);font-size:18px;letter-spacing:.04em}.sep-release-reveal.phase2 .sep-release-core{border-color:var(--red);box-shadow:0 0 90px #ff5b6535;animation:sepJolt .12s steps(2) 4}.sep-release-reveal.phase2 .k{color:var(--red)}@keyframes sepScan{to{transform:translateY(16px)}}@keyframes sepNoise{50%{opacity:.35;transform:translate(4px,-3px) rotate(-7deg)}}@keyframes sepJolt{50%{transform:translate(3px,-2px) skewX(-.5deg)}}</style>`);document.body.insertAdjacentHTML('beforeend',`<div id="sepreveal" class="sep-release-reveal"><div class="sep-release-noise"></div><div class="sep-release-core"><div class="k">PANI // DIRECTORY MUTATION DETECTED</div><h1>ACESSO EXTRAORDINÁRIO</h1><div class="term">CREDENTIAL: VALID\nSECTOR ENTRY: NOT FOUND\nSTATUS: RESTORATION LAYER DETECTED\nSIGNATURE: A. DENA</div><p>Esta não é uma negação de acesso.</p><b>É uma ausência de registro.</b></div></div>`);setTimeout(()=>$('#sepreveal')?.classList.add('phase2'),850);setTimeout(async()=>{let o=$('#sepreveal');if(o)o.remove();view='sepulcro';await sepulcroCrewRefresh(true);crewSyncNav(true);render(true)},3400)}
async function crewInit(){if(!tok){$('#gate').classList.remove('hidden');conn('CREDENCIAL AUSENTE',false);return}$('#loading').classList.remove('hidden');try{me=await rpc('pani_crew_auth',{p_token:tok});await Promise.all([getState(),status()]);$('#loading').classList.add('hidden');$('#crew').classList.remove('hidden');let k=sectorKey();$('#who').textContent=me.display_name;$('#role').textContent=me.mission_role;$('#occ').textContent=me.occupation;$('#badge').innerHTML=`<div class="sub">SETOR AUTORIZADO // ${STATION_ID}</div><b>${NL[k]} // ${N[k]}</b><div class="sub" style="margin-top:6px">Credencial vinculada às funções deste setor da estação.</div>`;crewSyncNav(true);render(true);setInterval(pollCrew,2200)}catch(e){console.error('crewInit',e);$('#loadtxt').innerHTML='<span class="bad">Credencial inválida ou serviço temporariamente indisponível.</span>';conn('ACESSO INDISPONÍVEL',false)}}
async function pollCrew(){if(document.hidden)return;try{let old=fp,wasReleased=sepReleased();await Promise.all([getState(),status()]);let nowReleased=sepReleased();crewSyncNav(false);if(!wasReleased&&nowReleased){sepReleaseReveal();return}if(wasReleased&&!nowReleased){if(view==='sepulcro')view='sector';toast('PANI // ROTINA EXTRAORDINÁRIA ENCERRADA');render(true);return}render(old!==fingerprint())}catch(e){console.error('pollCrew',e);conn('CONEXÃO INSTÁVEL',false)}}
function confirmBox(title,body,ok){$('#mtitle').textContent=title;$('#mbody').textContent=body;$('#modal').classList.remove('hidden');$('#mcancel').onclick=()=>$('#modal').classList.add('hidden');$('#mconfirm').onclick=()=>{$('#modal').classList.add('hidden');ok()}}
async function ma(a,p={}){return rpc('pani_master_action',{p_pin:pin,p_action:a,p_payload:p})}
async function sepMasterToggleRelease(){let released=!!sepMasterState.released;if(released)return confirmBox('Ocultar Protocolo Sepulcro?','Os jogadores perderão imediatamente o acesso à tela de enigmas. O progresso já obtido será preservado para uma futura liberação.',async()=>{try{sepMasterState=await rpc('pani_sepulcro_master_action',{p_pin:pin,p_action:'hide',p_payload:{}});await mrefresh();toast('SEPULCRO OCULTO DOS TERMINAIS')}catch(e){console.error(e);toast('Falha ao ocultar o protocolo.',true)}});confirmBox('Liberar Protocolo Sepulcro?','A tela normal de setor será substituída pelo acesso às Portas Enterradas em todos os terminais. Jogadores conectados receberão a revelação imediatamente.',async()=>{try{sepMasterState=await rpc('pani_sepulcro_master_action',{p_pin:pin,p_action:'release',p_payload:{}});await mrefresh();toast('PROTOCOLO SEPULCRO LIBERADO')}catch(e){console.error(e);toast('Falha ao liberar o protocolo.',true)}})}
async function mrefresh(){try{await getState();sepMasterState=await sepMasterRefresh();if(document.activeElement!==$('#occupancy'))$('#occupancy').value=state.occupancy;$('#mmode').textContent='STATION: '+STATION_ID;$('#msep').textContent=sepMasterState.released?`SEPULCRO: ${sepMasterState.solved_count||0}/5`:'SEPULCRO: OCULTO';$('#msync').textContent='PANI: '+(state.system_health?.pani??100)+'%';let event=!sepMasterState.released?'OCULTO DOS TERMINAIS':sepMasterState.reciprocity_established?'RECIPROCIDADE ESTABELECIDA':sepMasterState.alien_event_armed?'EVENTO ARMADO':sepMasterState.inv_available?'INV DISPONÍVEL':'LIBERADO // INV BLOQUEADA';$('#msepstate').textContent=event;let rb=$('#seprelease');if(rb){rb.textContent=sepMasterState.released?'OCULTAR DOS JOGADORES':'LIBERAR PARA JOGADORES';rb.className='btn '+(sepMasterState.released?'':'a')}$('#progress').innerHTML=sepMasterProgressHTML(sepMasterState);let lg=await rpc('pani_master_logs',{p_pin:pin,p_limit:60});$('#logs').textContent=(lg||[]).map(r=>`[${new Date(r.created_at).toLocaleTimeString()}] ${r.actor} :: ${r.event_type} :: ${r.detail||''}`).join('\n')||'Sem eventos.'}catch(e){console.error('mrefresh',e);conn('MASTER // CONEXÃO INSTÁVEL',false)}}
function isUnauthorized(e){let m=String(e?.message||'').toLowerCase(),raw=String(e?.raw||'').toLowerCase();return e?.status===401||e?.status===403||m.includes('unauthorized')||raw.includes('unauthorized')}
async function masterInit(){
  $('#mlogin').classList.remove('hidden');conn('MASTER // AGUARDANDO AUTENTICAÇÃO');
  $('#auth').onclick=async()=>{pin=$('#pin').value.trim();let b=$('#auth');if(!pin){toast('Informe o PIN do Diretor de Sessão.',true);return}b.disabled=true;b.textContent='AUTENTICANDO...';try{conn('MASTER // VERIFICANDO BACKEND');await backendHealth();conn('MASTER // VALIDANDO CREDENCIAL');await rpc('pani_master_logs',{p_pin:pin,p_limit:1});$('#mlogin').classList.add('hidden');$('#mapp').classList.remove('hidden');conn('MASTER ONLINE',true);await mrefresh();if(!window.__paniMasterPoll)window.__paniMasterPoll=setInterval(()=>{if(!document.hidden)mrefresh()},3000)}catch(e){console.error('masterAuth',e);if(isUnauthorized(e)){toast('PIN inválido.',true);conn('MASTER // ACESSO NEGADO',false)}else{toast('Backend indisponível. Tente novamente em alguns segundos.',true);conn('MASTER // BACKEND INDISPONÍVEL',false)}}finally{b.disabled=false;b.textContent='AUTENTICAR'}};
  $('#pin').addEventListener('keydown',e=>{if(e.key==='Enter')$('#auth').click()});
  $('#save').onclick=async()=>{try{await ma('state',{occupancy:+$('#occupancy').value});await mrefresh();toast('Estado da estação atualizado.')}catch{toast('Falha ao atualizar.',true)}};
  $('#seprelease').onclick=()=>sepMasterToggleRelease();
  $('#separm').onclick=()=>sepMasterArm();
  $('#sepreset').onclick=()=>sepMasterReset();
  if($('#trans'))$('#trans').onclick=()=>confirmBox('Ativar TRANSMISSION?','Esse evento permanece disponível como ferramenta narrativa do mestre e não pertence ao antigo sistema do satélite.',async()=>{try{await ma('transmission');await mrefresh();toast('TRANSMISSION CONNECTED.')}catch{toast('Falha.',true)}});
  $('#clear').onclick=async()=>{try{await ma('clear_alert');await mrefresh()}catch{}};
  $('#send').onclick=async()=>{let m=$('#msg').value.trim();if(!m)return;try{await ma('broadcast',{message:m,severity:$('#sev').value});$('#msg').value='';await mrefresh();toast('Mensagem transmitida.')}catch{toast('Falha na transmissão.',true)}};
}
window.addEventListener('online',()=>conn('RECONECTANDO...'));
window.addEventListener('offline',()=>conn('SEM CONEXÃO',false));
window.addEventListener('error',e=>{console.error('window.error',e.error||e.message);conn('FALHA DE INTERFACE',false)});
window.addEventListener('unhandledrejection',e=>{console.error('unhandledrejection',e.reason)});
(async()=>{try{MASTER?await masterInit():await crewInit()}catch(e){console.error('boot',e);conn('FALHA DE INICIALIZAÇÃO',false);toast('Falha de inicialização. Recarregue a página.',true)}})();
