'use strict';
function render(force=false){if(!me)return;let f=fingerprint();if(!force&&f===fp){alertRender();return}if(!force&&paniEditing($('#view'))){alertRender();return}capDraft();fp=f;alertRender();let html=view==='eco'?ecoPage():view==='dash'?dash():view==='sector'?stationSectorPage():view==='pani'?pani():view==='files'?files():creds();$('#view').innerHTML=html;putDraft();navRender();bind();if(view==='eco')ecoBind();document.dispatchEvent(new CustomEvent('pani:render',{detail:{view}}))}
async function status(){try{prog=await rpc('pani_crew_status',{p_token:tok})||{}}catch(e){console.warn('crew status unavailable',e);prog={}}return prog}
function crewNavMarkup(){let eco=(ecoState?.released&&ecoState?.eligible)||view==='eco'?'<button class="btn" data-v="eco">ECO-W77</button>':'';return '<button class="btn" data-v="dash">VISÃO GERAL</button><button class="btn" data-v="sector">SETOR W77-01</button><button class="btn" data-v="pani">PANI</button><button class="btn" data-v="files">ARQUIVOS</button><button class="btn" data-v="cred">CREDENCIAIS</button>'+eco}
function crewSyncNav(force=false){if(MASTER)return;let n=$('#nav');if(!n)return;let mode=(ecoState?.released&&ecoState?.eligible)||view==='eco'?'routine-eco':'routine';if(!force&&n.dataset.mode===mode)return;n.dataset.mode=mode;n.innerHTML=crewNavMarkup();n.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;render(true)});navRender()}
function bind(){if(view==='pani'&&$('#ask'))$('#ask').onclick=()=>{let q=$('#q').value.toLowerCase(),k=sectorKey(),a=q.includes('quant')?`Existem ${state.occupancy} assinaturas biométricas detectadas na estação.`:q.includes('funç')||q.includes('cargo')?`${me.display_name}: ${me.mission_role}. Setor: ${NL[k]} // ${N[k]}.`:q.includes('energia')?`PANI CORE: ${state.system_health?.pani??100}%. Rotina da estação dentro dos parâmetros autorizados.`:q.includes('transmiss')?(state.transmission?'TRANSMISSION: CONNECTED. Origem não catalogada.':'Nenhuma transmissão externa catalogada neste momento.'):'Solicitação registrada. Não há resposta adicional autorizada para esta credencial.';$('#ans').textContent=a};if(view==='cred'&&$('#crs'))$('#crs').onclick=async()=>{try{let r=await rpc('pani_crew_register_credential',{p_token:tok,p_code:$('#cr').value});await status();toast(r.ok?'Credencial registrada.':'Credencial não reconhecida.',!r.ok);render(true)}catch{toast('Falha ao registrar credencial.',true)}}}
async function crewInit(){if(!tok){$('#gate').classList.remove('hidden');conn('CREDENCIAL AUSENTE',false);return}$('#loading').classList.remove('hidden');try{me=await rpc('pani_crew_auth',{p_token:tok});let routeCrew=ECO_ROUTE.startsWith('eco-w77/')?ECO_ROUTE.split('/')[1]:'';if(routeCrew&&routeCrew!==me.crew_id)throw Error('route_credential_mismatch');await Promise.all([getState(),status(),ecoCrewRefresh(false)]);$('#loading').classList.add('hidden');$('#crew').classList.remove('hidden');let k=sectorKey();$('#who').textContent=me.display_name;$('#role').textContent=me.mission_role;$('#occ').textContent=me.occupation;$('#badge').innerHTML=`<div class="sub">SETOR AUTORIZADO // ${STATION_ID}</div><b>${NL[k]} // ${N[k]}</b><div class="sub" style="margin-top:6px">Credencial vinculada às funções deste setor da estação.</div>`;crewSyncNav(true);render(true);setInterval(pollCrew,2200)}catch(e){console.error('crewInit',e);$('#loadtxt').innerHTML='<span class="bad">Credencial inválida ou rota incompatível.</span>';conn('ACESSO INDISPONÍVEL',false)}}
async function pollCrew(){if(document.hidden)return;try{await Promise.all([getState(),status(),ecoCrewRefresh(false)]);crewSyncNav(false);render(false)}catch(e){console.error('pollCrew',e);conn('CONEXÃO INSTÁVEL',false)}}
function confirmBox(title,body,ok){$('#mtitle').textContent=title;$('#mbody').textContent=body;$('#modal').classList.remove('hidden');$('#mcancel').onclick=()=>$('#modal').classList.add('hidden');$('#mconfirm').onclick=()=>{$('#modal').classList.add('hidden');ok()}}
async function ma(a,p={}){return rpc('pani_master_action',{p_pin:pin,p_action:a,p_payload:p})}
async function mrefresh(){try{await Promise.all([getState(),ecoMasterRefresh(false)]);if(document.activeElement!==$('#occupancy'))$('#occupancy').value=state.occupancy;$('#mmode').textContent='STATION: '+STATION_ID;$('#msync').textContent='PANI: '+(state.system_health?.pani??100)+'%';let lg=await rpc('pani_master_logs',{p_pin:pin,p_limit:60});$('#logs').textContent=(lg||[]).map(r=>`[${new Date(r.created_at).toLocaleTimeString()}] ${r.actor} :: ${r.event_type} :: ${r.detail||''}`).join('\n')||'Sem eventos.'}catch(e){console.error('mrefresh',e);conn('MASTER // CONEXÃO INSTÁVEL',false)}}
function isUnauthorized(e){let m=String(e?.message||'').toLowerCase(),raw=String(e?.raw||'').toLowerCase();return e?.status===401||e?.status===403||m.includes('unauthorized')||raw.includes('unauthorized')}
async function masterInit(){
  $('#mlogin').classList.remove('hidden');conn('MASTER // AGUARDANDO AUTENTICAÇÃO');
  $('#auth').onclick=async()=>{pin=$('#pin').value.trim();let b=$('#auth');if(!pin){toast('Informe o PIN do Diretor de Sessão.',true);return}b.disabled=true;b.textContent='AUTENTICANDO...';try{conn('MASTER // VERIFICANDO BACKEND');await backendHealth();conn('MASTER // VALIDANDO CREDENCIAL');await rpc('pani_master_logs',{p_pin:pin,p_limit:1});$('#mlogin').classList.add('hidden');$('#mapp').classList.remove('hidden');conn('MASTER ONLINE',true);await mrefresh();if(!window.__paniMasterPoll)window.__paniMasterPoll=setInterval(()=>{if(!document.hidden)mrefresh()},3000)}catch(e){console.error('masterAuth',e);if(isUnauthorized(e)){toast('PIN inválido.',true);conn('MASTER // ACESSO NEGADO',false)}else{toast('Backend indisponível. Tente novamente em alguns segundos.',true);conn('MASTER // BACKEND INDISPONÍVEL',false)}}finally{b.disabled=false;b.textContent='AUTENTICAR'}};
  $('#pin').addEventListener('keydown',e=>{if(e.key==='Enter')$('#auth').click()});
  $('#save').onclick=async()=>{try{await ma('state',{occupancy:+$('#occupancy').value});await mrefresh();toast('Estado da estação atualizado.')}catch{toast('Falha ao atualizar.',true)}};
  if($('#trans'))$('#trans').onclick=()=>confirmBox('Ativar TRANSMISSION?','Esse evento permanece disponível como ferramenta narrativa independente do mestre.',async()=>{try{await ma('transmission');await mrefresh();toast('TRANSMISSION CONNECTED.')}catch{toast('Falha.',true)}});
  $('#clear').onclick=async()=>{try{await ma('clear_alert');await mrefresh()}catch{}};
  $('#send').onclick=async()=>{let m=$('#msg').value.trim();if(!m)return;try{await ma('broadcast',{message:m,severity:$('#sev').value});$('#msg').value='';await mrefresh();toast('Mensagem transmitida.')}catch{toast('Falha na transmissão.',true)}};
}
window.addEventListener('online',()=>conn('RECONECTANDO...'));
window.addEventListener('offline',()=>conn('SEM CONEXÃO',false));
window.addEventListener('error',e=>{console.error('window.error',e.error||e.message);conn('FALHA DE INTERFACE',false)});
window.addEventListener('unhandledrejection',e=>{console.error('unhandledrejection',e.reason)});
(async()=>{try{MASTER?await masterInit():await crewInit()}catch(e){console.error('boot',e);conn('FALHA DE INICIALIZAÇÃO',false);toast('Falha de inicialização. Recarregue a página.',true)}})();
