'use strict';

/* PANI // PROTOCOLO CONTRAPROVA // A Coluna Ausente
 * Nomes internos antigos permanecem para compatibilidade. Esta experiência
 * não traduz glifos, não atribui letras e não estabelece reciprocidade. */

const CONTRA_SECTORS=['ops','gen','env','med','sec'];
const CONTRA_META={
  ops:{title:'DEPENDÊNCIA FANTASMA',tool:'INSPECTOR DE ARQUITETURA DE RETORNO',docs:['TA-04','TA-09'],method:['O que existe fisicamente?','O que foi prometido?','De onde vem a capacidade ausente?']},
  gen:{title:'O QUE MUDOU?',tool:'COMPARADOR DE CAMADAS',docs:['IV-03','IV-08'],method:['O que permaneceu igual?','Qual camada divergiu?','A divergência atravessou outro suporte?']},
  env:{title:'A DIREÇÃO QUE SOBREVIVE AO TESTE',tool:'MESA DE ISOLAMENTO DE VARIÁVEIS',docs:['HM-04','HM-11'],method:['Qual variável foi alterada?','O que persistiu?','A referência foi normalizada?']},
  med:{title:'O ARQUIVO QUE CHEGOU ANTES',tool:'VALIDADOR DE CRONOLOGIA CLÍNICA',docs:['ATLAS CLÍNICO','MATRIZ PROSPECTIVA'],method:['O que existia antes?','Quando ocorreu a exposição?','O registro descrevia risco ou resposta esperada?']},
  sec:{title:'A PRESENÇA SEM TRAVESSIA',tool:'REPLAYER DE INCURSÃO',docs:['RV-03','RV-09','BLACKBOX 20MAY26'],method:['Onde a presença foi confirmada?','Qual fronteira deveria registrar passagem?','Existe travessia correspondente?']},
  inv:{title:'A COLUNA AUSENTE',tool:'MATRIZ DE CONTRAPROVA',docs:['AD-06','AD-15'],method:['Onde apareceu?','O que existia antes?','O que substituiu?','Já apareceu em outro suporte?']}
};
const CONTRA_MODELS=[
  ['independent','FALHAS INDEPENDENTES','Cinco causas diferentes surgindo no mesmo período.'],
  ['mechanical','SABOTAGEM MECÂNICA','Explica parte de OPS, mas não os demais suportes.'],
  ['biological','CONTAMINAÇÃO BIOLÓGICA','Explica organismos e corpos, mas não permissões ou portas.'],
  ['sensors','ERRO GERAL DE SENSORES','Falha diante de impressões, plantas e documentos físicos.'],
  ['relation','INFORMAÇÃO / RELAÇÃO','Um domínio capaz de atravessar suportes diferentes.']
];
const OPS_EVIDENCE=[
  ['prop_main','PROPULSÃO PRINCIPAL','TA-04','Capacidade operacional alta; permite manobra.'],
  ['prop_aux','PROPULSÃO AUXILIAR','TA-04','Recurso local de manobra e correção.'],
  ['rp02','RETURN PROPULSION UNIT // RP-02','TA-04','INSTALLATION STATUS: NOT INSTALLED. DAMAGE: NONE.'],
  ['local_plan','PLANO LOCAL DE RETORNO','TA-04','NO LOCAL FLIGHT PLAN FOUND.'],
  ['recovery','RECUPERAÇÃO / SOCORRO','TA-09','Dependência de rede e autorização Panacea.'],
  ['authority','AUTORIDADE DE RETORNO','TA-09','LOCAL OVERRIDE: DENIED / DISABLED.']
];
const MED_INITIAL_ORDER=['clinical','premission','comparison','launch','semantic'];
const MED_CARDS={
  premission:['ARQUIVO PRÉ-MISSÃO','CREATED antes do lançamento','MATRIZ PROSPECTIVA'],
  launch:['LANÇAMENTO','Início da exposição operacional da tripulação','REGISTRO DE MISSÃO'],
  clinical:['OBSERVAÇÕES CLÍNICAS','Respostas fisiológicas registradas por Caio','ATLAS CLÍNICO'],
  semantic:['1º DESLOCAMENTO SEMÂNTICO','Primeira ocorrência observada posteriormente','ATLAS / LOG'],
  comparison:['COMPARAÇÃO POSTERIOR','Concordância média calculada: 89,4%','CORRELAÇÃO PANI']
};
const SEC_STEPS=[
  ['T+00','CONTATO EXTERNO','Assinaturas externas registradas no perímetro.','PORTAS: SELADAS'],
  ['T+01','APROXIMAÇÃO','Contatos reduzem distância. Lockdown permanece nominal.','PORTAS: SELADAS'],
  ['T+02','INTERFERÊNCIA','Resposta não catalogada atravessa radar e comunicação.','PORTAS: SELADAS'],
  ['T+03','MOVIMENTO INTERNO','Presença interna confirmada por sensores independentes.','TRAVESSIA: NÃO ENCONTRADA'],
  ['T+04','PERDA DE SINAIS','Cinco assinaturas da tripulação deixam de ser localizáveis.','SEC-C12: LOCKED'],
  ['T+05','CAIXA-PRETA','Corpos identificados: 0. Localização: UNRESOLVED.','ABERTURAS: 0']
];

let sepDraft=contraFreshDraft(),sepBusy=false,sepSelectedEvidence=null,sepSelectedPiece=null,sepCooldownUntil=0;

function contraFreshDraft(){return{
  ops:{bins:{installed:[],absent:[],external:[]},route:[]},
  gen:{stable:[],divergent:'',physicalPrint:false,hypothesis:''},
  env:{tests:[],normalized:false,conclusion:''},
  med:{order:[...MED_INITIAL_ORDER],links:{},distinction:''},
  sec:{step:0,inspected:[0],presence:'',crossing:'',conclusion:''},
  inv:{assignments:{},selectedModel:''}
}}
function contraResetDraft(k){let fresh=contraFreshDraft();sepDraft[k]=fresh[k];sepSelectedEvidence=null;sepSelectedPiece=null}
function contraSolvedCount(){return CONTRA_SECTORS.reduce((n,k)=>n+(sepState?.[k+'_solved']?1:0),0)}
function contraMethod(k){return `<section class="contra-method"><div><div class="k">AD-15 // MÉTODO DE ANÁLISE</div><h3>${CONTRA_META[k].tool}</h3></div><div class="contra-checks">${CONTRA_META[k].method.map(x=>`<span>□ ${esc(x)}</span>`).join('')}</div></section>`}
function contraDocs(k){return `<div class="contra-docs"><span class="k">EVIDÊNCIAS VINCULADAS</span>${CONTRA_META[k].docs.map(x=>`<button class="btn" onclick="contraOpenDocument('${esc(x)}')">${esc(x)}</button>`).join('')}</div>`}
function contraOpenDocument(query){view='files';render(true);setTimeout(()=>{let input=$('#pfsearch');if(input){input.value=query;if(typeof paniFileSearch==='function')paniFileSearch(query)}},90)}
function sepProgress(){let cards=CONTRA_SECTORS.map(k=>{let done=!!sepState?.[k+'_solved'];return `<div class="${done?'done':''}"><b>${NL[k]}</b><span>${done?'ASSINATURA PUBLICADA':'CONTRAPROVA PENDENTE'}</span></div>`}).join(''),received=contraSolvedCount(),invClass=sepState?.inv_solved?'done':received===5||sepState?.matrix_open?'ready':'locked',invText=sepState?.inv_solved?'HIPÓTESE ESTABILIZADA':`${received}/5 ASSINATURAS`;return `<div class="sep-progress">${cards}<div class="${invClass}"><b>INV</b><span>${invText}</span></div></div>`}
function sepHeader(k){let done=!!sepState?.[k+'_solved'],status=done?'ESTABILIZADA':k==='inv'?'CORRELAÇÃO':'EM ANÁLISE';return `<header class="sep-head"><div><div class="k">PANI // CONTRAPROVA // ${NL[k]}</div><h2>${CONTRA_META[k].title}</h2><p class="mut">DOCUMENTO RECUPERADO ≠ DOCUMENTO CONFIÁVEL<br>GLYPH SEMANTICS: UNRESOLVED<br>ALPHABET MAPPING: NOT ATTEMPTED</p></div><span class="sep-status ${done?'ok':'warn'}">${status}</span></header>`}
function sepControls(k){let cooldown=Math.max(0,Math.ceil((sepCooldownUntil-Date.now())/1000));return `${contraDocs(k)}<div class="sep-tools"><button class="btn" onclick="sepHint()">SOLICITAR CORRELAÇÃO PANI</button><span class="mut small">CONTRADIÇÕES: ${sepState?.attempts||0}</span><span class="mut small">PISTA: ${sepState?.hint_level||0}/4</span>${cooldown?`<span class="warn small">RECALIBRANDO ${cooldown}s</span>`:''}</div><div id="sepfeedback" class="term sep-feedback">${esc(sepState?.last_feedback||'PANI aguardando contraprova.')}</div>`}
function contraSignature(k){return sepState?.signatures?.[k]||'ASSINATURA DE CONTRADIÇÃO ESTABILIZADA'}
function sepSolved(k){return `${sepHeader(k)}${sepProgress()}${contraMethod(k)}<section class="contra-signature"><div class="k">ASSINATURA PUBLICADA PARA INV</div><b>${esc(contraSignature(k))}</b><p>A conclusão foi estabilizada. Nenhum valor semântico foi atribuído aos Sinais.</p></section>${sepControls(k)}`}

/* OPS */
function contraEvidenceCard(id,label,source,body,selected=false){return `<button type="button" draggable="true" class="contra-evidence ${selected?'selected':''}" data-evidence="${id}" ondragstart="contraDragEvidence(event,'${id}')" onclick="contraSelectEvidence('${id}')"><span>${esc(source)}</span><b>${esc(label)}</b><small>${esc(body)}</small></button>`}
function contraSelectEvidence(id){sepSelectedEvidence=sepSelectedEvidence===id?null:id;render(true)}
function contraDragEvidence(event,id){sepSelectedEvidence=id;event.dataTransfer?.setData('text/plain',id);if(event.dataTransfer)event.dataTransfer.effectAllowed='move'}
function contraDropOps(bin,event){event.preventDefault();let id=event.dataTransfer?.getData('text/plain')||sepSelectedEvidence;if(id)contraOpsMove(id,bin)}
function contraOpsMove(id,bin){Object.values(sepDraft.ops.bins).forEach(arr=>{let i=arr.indexOf(id);if(i>=0)arr.splice(i,1)});if(sepDraft.ops.bins[bin])sepDraft.ops.bins[bin].push(id);sepSelectedEvidence=null;render(true)}
function contraOpsPool(){let placed=new Set(Object.values(sepDraft.ops.bins).flat()),remaining=OPS_EVIDENCE.filter(x=>!placed.has(x[0]));return `<div class="contra-evidence-pool">${remaining.length?remaining.map(x=>contraEvidenceCard(...x,sepSelectedEvidence===x[0])).join(''):'<span class="mut">Todos os cartões foram classificados.</span>'}</div>`}
function contraOpsBin(id,title){let cards=sepDraft.ops.bins[id].map(key=>{let data=OPS_EVIDENCE.find(x=>x[0]===key);return data?contraEvidenceCard(...data,sepSelectedEvidence===key):''}).join('');return `<section class="contra-bin" onclick="if(sepSelectedEvidence)contraOpsMove(sepSelectedEvidence,'${id}')" ondragover="event.preventDefault()" ondrop="contraDropOps('${id}',event)"><div class="k">${title}</div>${cards||'<span class="contra-drop-hint">ARRASTE OU SELECIONE UM CARTÃO</span>'}</section>`}
function contraToggleRoute(id){let arr=sepDraft.ops.route,i=arr.indexOf(id);if(i>=0)arr.splice(i,1);else arr.push(id);render(true)}
function contraRouteNode(id,label,sub){let on=sepDraft.ops.route.includes(id);return `<button class="contra-route-node ${on?'on':''}" onclick="contraToggleRoute('${id}')"><b>${label}</b><span>${sub}</span></button>`}
function sepOps(){let k='ops';if(sepState?.ops_solved)return sepSolved(k);return `${sepHeader(k)}${sepProgress()}${contraMethod(k)}<p>Classifique cada evidência conforme aquilo que a estação realmente possui. Em seguida, monte somente a cadeia de capacidades que poderia sustentar uma rota autônoma.</p>${contraOpsPool()}<div class="contra-bins">${contraOpsBin('installed','INSTALADO / LOCAL')}${contraOpsBin('absent','NÃO INSTALADO / AUSENTE')}${contraOpsBin('external','EXTERNO')}</div><section class="contra-route"><div class="k">GRAFO DE RETORNO // SELECIONE OS NÓS REAIS</div><div>${contraRouteNode('prop_main','PROPULSÃO','MANOBRA')}${contraRouteNode('prop_aux','AUXILIAR','CORREÇÃO')}<i>→</i>${contraRouteNode('rp02','RP-02','RETORNO')}<i>→</i>${contraRouteNode('recovery','RECUPERAÇÃO','AUTORIZAÇÃO')}</div></section><button id="sepsubmit" class="btn a contra-submit" onclick="sepSubmitOps()">EXECUTAR CONTRAPROVA</button>${sepControls(k)}`}
function sepSubmitOps(){return sepAttempt({module:'ops',bins:sepDraft.ops.bins,route:sepDraft.ops.route})}

/* GEN */
function contraToggleGenStable(id){let arr=sepDraft.gen.stable,i=arr.indexOf(id);if(i>=0)arr.splice(i,1);else arr.push(id);render(true)}
function contraSetGenDivergent(id){sepDraft.gen.divergent=id;render(true)}
function contraSetGenHypothesis(id){sepDraft.gen.hypothesis=id;render(true)}
function contraLayer(id,label,source,note,mode){let selected=mode==='stable'?sepDraft.gen.stable.includes(id):sepDraft.gen.divergent===id,action=mode==='stable'?`contraToggleGenStable('${id}')`:`contraSetGenDivergent('${id}')`;return `<button class="contra-layer ${selected?'on':''}" onclick="${action}"><span>${source}</span><b>${label}</b><small>${note}</small><i>${selected?'FIXADA':mode==='stable'?'FIXAR COMO INVARIANTE':'MARCAR DIVERGÊNCIA'}</i></button>`}
function sepGen(){let k='gen';if(sepState?.gen_solved)return sepSolved(k);return `${sepHeader(k)}${sepProgress()}${contraMethod(k)}<p>Sobreponha as camadas da mesma amostra. Fixe o que permanece invariável e marque a única camada que escapa entre leituras.</p><div class="contra-layer-stack">${contraLayer('sample','AMOSTRA / TECIDO','IV-03','Estrutura biológica observada fisicamente.','stable')}${contraLayer('slide','LÂMINA','IV-08','Material e disposição preservados.','stable')}${contraLayer('spectrum','ESPECTRO','IV-08','Assinatura instrumental coincide.','stable')}${contraLayer('descriptive_record','RESULTADO DESCRITIVO','IV-08','A sequência escrita muda entre leituras.','divergent')}</div><label class="contra-proof-check"><input type="checkbox" ${sepDraft.gen.physicalPrint?'checked':''} onchange="sepDraft.gen.physicalPrint=this.checked;render(true)"> A impressão física reproduz a divergência fora do monitor.</label><div class="contra-models compact"><button class="${sepDraft.gen.hypothesis==='mutation'?'selected':''}" onclick="contraSetGenHypothesis('mutation')"><b>MUTAÇÃO</b><span>O objeto mudou.</span></button><button class="${sepDraft.gen.hypothesis==='sequencer_failure'?'selected':''}" onclick="contraSetGenHypothesis('sequencer_failure')"><b>FALHA DE SEQUENCIADOR</b><span>O instrumento mudou.</span></button><button class="${sepDraft.gen.hypothesis==='record_change'?'selected':''}" onclick="contraSetGenHypothesis('record_change')"><b>ALTERAÇÃO DO REGISTRO</b><span>A descrição mudou.</span></button></div><button id="sepsubmit" class="btn a contra-submit" onclick="sepSubmitGen()">COMPARAR CAMADAS</button>${sepControls(k)}`}
function sepSubmitGen(){return sepAttempt({module:'gen',stable:sepDraft.gen.stable,divergent:sepDraft.gen.divergent,physical_print:sepDraft.gen.physicalPrint,hypothesis:sepDraft.gen.hypothesis})}

/* ENV */
function contraToggleEnvTest(id){let arr=sepDraft.env.tests,i=arr.indexOf(id);if(i>=0)arr.splice(i,1);else if(arr.length<3)arr.push(id);else return sepFeedback('Selecione exatamente três testes de isolamento.',true);sepDraft.env.normalized=false;render(true)}
function contraNormalizeEnv(){if(sepDraft.env.tests.length!==3)return sepFeedback('Três testes independentes são necessários.',true);sepDraft.env.normalized=true;render(true)}
function contraSetEnvConclusion(id){sepDraft.env.conclusion=id;render(true)}
function contraEnvTest(id,label,result){let selected=sepDraft.env.tests.includes(id);return `<button class="contra-test ${selected?'selected':''}" onclick="contraToggleEnvTest('${id}')"><span>${selected?'TESTE SELECIONADO':'EVIDÊNCIA DISPONÍVEL'}</span><b>${label}</b><small>${result}</small></button>`}
function sepEnv(){let k='env';if(sepState?.env_solved)return sepSolved(k);let normalized=sepDraft.env.normalized;return `${sepHeader(k)}${sepProgress()}${contraMethod(k)}<p>Escolha três testes capazes de eliminar explicações concorrentes. Só então normalize as referências e compare os vetores finais.</p><div class="contra-tests">${contraEnvTest('light','ALTERAÇÃO DE LUZ','Vetor final persiste.')}${contraEnvTest('airflow','INVERSÃO DO FLUXO DE AR','Vetor final persiste.')}${contraEnvTest('rotation','ROTAÇÃO DOS VASOS','Orientação retorna ao mesmo eixo da estação.')}${contraEnvTest('humidity','VARIAÇÃO DE UMIDADE','Sem desvio correspondente.')}${contraEnvTest('crt','CAMPO DE REFERÊNCIA TERRESTRE','Referência controlada estabelecida.')}${contraEnvTest('label','TROCA DE ETIQUETA','Não altera uma variável ambiental.')}</div><button class="btn ${sepDraft.env.tests.length===3?'a':''}" onclick="contraNormalizeEnv()" ${sepDraft.env.tests.length===3?'':'disabled'}>NORMALIZAR REFERÊNCIA</button><div class="contra-vector-board ${normalized?'normalized':''}"><div class="k">MAPA COMUM DA ESTAÇÃO</div><div class="contra-vectors"><i></i><i></i><i></i><i></i></div><b>${normalized?'VETORES CONVERGENTES // CAUSAS ALTERADAS':'REFERÊNCIAS NÃO NORMALIZADAS'}</b></div><div class="contra-models compact"><button class="${sepDraft.env.conclusion==='environmental_cause'?'selected':''}" onclick="contraSetEnvConclusion('environmental_cause')"><b>CAUSA AMBIENTAL</b><span>Uma variável local determina o vetor.</span></button><button class="${sepDraft.env.conclusion==='organism'?'selected':''}" onclick="contraSetEnvConclusion('organism')"><b>ORGANISMO</b><span>A espécie explica a orientação.</span></button><button class="${sepDraft.env.conclusion==='direction_invariant'?'selected':''}" onclick="contraSetEnvConclusion('direction_invariant')"><b>DIREÇÃO INVARIANTE</b><span>A causa muda; a direção persiste.</span></button></div><button id="sepsubmit" class="btn a contra-submit" onclick="sepSubmitEnv()">VALIDAR ISOLAMENTO</button>${sepControls(k)}`}
function sepSubmitEnv(){return sepAttempt({module:'env',tests:sepDraft.env.tests,normalized:sepDraft.env.normalized,conclusion:sepDraft.env.conclusion})}

/* MED */
function contraMedMove(id,delta){let arr=sepDraft.med.order,i=arr.indexOf(id),j=Math.max(0,Math.min(arr.length-1,i+delta));if(i===j)return;arr.splice(i,1);arr.splice(j,0,id);render(true)}
function contraMedDrag(event,id){event.dataTransfer?.setData('text/plain',id)}
function contraMedDrop(event,target){event.preventDefault();let id=event.dataTransfer?.getData('text/plain');if(!id||id===target)return;let arr=sepDraft.med.order,from=arr.indexOf(id),to=arr.indexOf(target);arr.splice(from,1);arr.splice(to,0,id);render(true)}
function contraMedCard(id,index){let [title,body,source]=MED_CARDS[id];return `<article draggable="true" class="contra-time-card" ondragstart="contraMedDrag(event,'${id}')" ondragover="event.preventDefault()" ondrop="contraMedDrop(event,'${id}')"><span>${String(index+1).padStart(2,'0')} // ${source}</span><b>${title}</b><small>${body}</small><div><button onclick="contraMedMove('${id}',-1)" ${index===0?'disabled':''}>↑</button><button onclick="contraMedMove('${id}',1)" ${index===sepDraft.med.order.length-1?'disabled':''}>↓</button></div></article>`}
function contraMedLink(id,label,options){return `<label><b>${label}</b><select onchange="sepDraft.med.links['${id}']=this.value"><option value="">VINCULAR SINTOMA...</option>${options.map(([v,t])=>`<option value="${v}" ${sepDraft.med.links[id]===v?'selected':''}>${t}</option>`).join('')}</select></label>`}
function contraSetMedDistinction(id){sepDraft.med.distinction=id;render(true)}
function sepMed(){let k='med';if(sepState?.med_solved)return sepSolved(k);let opts=[['thermal_drop','QUEDA TÉRMICA'],['rem_sync','REM SINCRONIZADO'],['pain_without_lesion','DOR SEM LESÃO'],['cognitive_fixation','FIXAÇÃO COGNITIVA']];return `${sepHeader(k)}${sepProgress()}${contraMethod(k)}<p>Ordene os registros pela metadata mais conservadora. Depois vincule cada previsão à resposta clínica específica que ela antecipava.</p><div class="contra-timeline">${sepDraft.med.order.map(contraMedCard).join('')}</div><div class="contra-links">${contraMedLink('thermal','PREVISÃO: INSTABILIDADE TÉRMICA',opts)}${contraMedLink('rem','PREVISÃO: PADRÃO DE SONO',opts)}${contraMedLink('pain','PREVISÃO: RESPOSTA NOCICEPTIVA',opts)}${contraMedLink('fixation','PREVISÃO: FIXAÇÃO COGNITIVA',opts)}</div><div class="contra-models compact"><button class="${sepDraft.med.distinction==='generic_risk'?'selected':''}" onclick="contraSetMedDistinction('generic_risk')"><b>RISCO GENÉRICO</b><span>Possibilidade ampla, sem resposta definida.</span></button><button class="${sepDraft.med.distinction==='specific_expected'?'selected':''}" onclick="contraSetMedDistinction('specific_expected')"><b>RESPOSTA ESPERADA ESPECÍFICA</b><span>Vocabulário experimental anterior à missão.</span></button></div><button id="sepsubmit" class="btn a contra-submit" onclick="sepSubmitMed()">VALIDAR CRONOLOGIA</button>${sepControls(k)}`}
function sepSubmitMed(){return sepAttempt({module:'med',order:sepDraft.med.order,links:sepDraft.med.links,distinction:sepDraft.med.distinction})}

/* SEC */
function contraSecStep(delta){sepDraft.sec.step=Math.max(0,Math.min(SEC_STEPS.length-1,sepDraft.sec.step+delta));if(!sepDraft.sec.inspected.includes(sepDraft.sec.step))sepDraft.sec.inspected.push(sepDraft.sec.step);render(true)}
function contraMarkPresence(){sepDraft.sec.presence=`t0${sepDraft.sec.step}`;render(true)}
function contraSetSec(field,value){sepDraft.sec[field]=value;render(true)}
function sepSec(){let k='sec';if(sepState?.sec_solved)return sepSolved(k);let step=sepDraft.sec.step,[time,title,body,doors]=SEC_STEPS[step],inspected=new Set(sepDraft.sec.inspected);return `${sepHeader(k)}${sepProgress()}${contraMethod(k)}<p>Reproduza as três trilhas do ataque. Marque o primeiro momento de presença interna confirmada e procure a travessia necessária nos registros de portas.</p><section class="contra-replayer"><div class="contra-replay-track">${SEC_STEPS.map((x,i)=>`<button class="${i===step?'active':''} ${inspected.has(i)?'seen':''}" onclick="sepDraft.sec.step=${i};if(!sepDraft.sec.inspected.includes(${i}))sepDraft.sec.inspected.push(${i});render(true)">${x[0]}</button>`).join('')}</div><div class="contra-replay-screen"><div><span>${time}</span><b>${title}</b><p>${body}</p></div><div class="term">${doors}</div></div><div class="actions"><button class="btn" onclick="contraSecStep(-1)" ${step===0?'disabled':''}>◀ ANTERIOR</button><button class="btn a" onclick="contraMarkPresence()">MARCAR PRESENÇA AQUI</button><button class="btn" onclick="contraSecStep(1)" ${step===5?'disabled':''}>PRÓXIMO ▶</button></div></section><div class="contra-sec-grid"><section><div class="k">PRESENÇA INTERNA MARCADA</div><b>${sepDraft.sec.presence?sepDraft.sec.presence.toUpperCase():'NÃO MARCADA'}</b></section><section><div class="k">TRAVESSIA CORRESPONDENTE</div><div class="contra-choice-row"><button class="${sepDraft.sec.crossing==='route_a'?'selected':''}" onclick="contraSetSec('crossing','route_a')">ROTA A</button><button class="${sepDraft.sec.crossing==='route_b'?'selected':''}" onclick="contraSetSec('crossing','route_b')">ROTA B</button><button class="${sepDraft.sec.crossing==='none'?'selected':''}" onclick="contraSetSec('crossing','none')">NÃO ENCONTRADA</button></div></section></div><div class="contra-models compact"><button class="${sepDraft.sec.conclusion==='sensor_failure'?'selected':''}" onclick="contraSetSec('conclusion','sensor_failure')"><b>FALHA DE SENSOR</b><span>A presença não é confiável.</span></button><button class="${sepDraft.sec.conclusion==='hidden_route'?'selected':''}" onclick="contraSetSec('conclusion','hidden_route')"><b>ROTA NÃO CATALOGADA</b><span>Uma porta invisível explica o evento.</span></button><button class="${sepDraft.sec.conclusion==='presence_without_traversal'?'selected':''}" onclick="contraSetSec('conclusion','presence_without_traversal')"><b>PRESENÇA SEM TRAVESSIA</b><span>Os logs não explicam a presença confirmada.</span></button></div><button id="sepsubmit" class="btn a contra-submit" onclick="sepSubmitSec()">VALIDAR REPLAYER</button>${sepControls(k)}`}
function sepSubmitSec(){return sepAttempt({module:'sec',inspected:sepDraft.sec.inspected,presence:sepDraft.sec.presence,crossing:sepDraft.sec.crossing,conclusion:sepDraft.sec.conclusion})}

/* INV */
function contraSignatureBoard(){let parts=sepState?.signature_parts||{};return `<div class="contra-signature-board">${CONTRA_SECTORS.map(k=>{let done=!!sepState?.[k+'_solved'],p=parts[k];return `<article class="${done?'published':'sealed'}"><span>${NL[k]}</span>${done&&p?`<b>${esc(p.physical)}</b><i>↔</i><b>${esc(p.relation)}</b>`:'<b>ASSINATURA NÃO PUBLICADA</b>'}</article>`}).join('')}</div>`}
function contraInvPieces(){let parts=sepState?.signature_parts||{},pieces=[];CONTRA_SECTORS.forEach(k=>{if(!sepState?.[k+'_solved']||!parts[k])return;pieces.push([`${k}:physical`,NL[k],parts[k].physical]);pieces.push([`${k}:relation`,NL[k],parts[k].relation])});let placed=new Set(Object.keys(sepDraft.inv.assignments));return pieces.filter(x=>!placed.has(x[0])).map(x=>contraInvPiece(...x)).join('')||'<span class="mut">Todas as metades publicadas foram posicionadas.</span>'}
function contraInvPiece(id,sector,text){let selected=sepSelectedPiece===id;return `<button draggable="true" class="contra-piece ${selected?'selected':''}" data-piece="${id}" ondragstart="contraDragPiece(event,'${id}')" onclick="contraSelectPiece('${id}')"><span>${sector}</span><b>${esc(text)}</b></button>`}
function contraSelectPiece(id){sepSelectedPiece=sepSelectedPiece===id?null:id;render(true)}
function contraDragPiece(event,id){sepSelectedPiece=id;event.dataTransfer?.setData('text/plain',id)}
function contraAssignPiece(column,event){event?.preventDefault?.();let id=event?.dataTransfer?.getData('text/plain')||sepSelectedPiece;if(!id)return;sepDraft.inv.assignments[id]=column;sepSelectedPiece=null;render(true)}
function contraUnassignPiece(id){delete sepDraft.inv.assignments[id];render(true)}
function contraInvColumn(id,title){let parts=sepState?.signature_parts||{},rows=Object.entries(sepDraft.inv.assignments).filter(([,col])=>col===id).map(([piece])=>{let [sector,side]=piece.split(':'),value=parts?.[sector]?.[side]||piece;return `<button onclick="contraUnassignPiece('${piece}')"><span>${NL[sector]||sector}</span><b>${esc(value)}</b></button>`}).join('');return `<section class="contra-matrix-column" onclick="if(sepSelectedPiece)contraAssignPiece('${id}')" ondragover="event.preventDefault()" ondrop="contraAssignPiece('${id}',event)"><div class="k">${title}</div>${rows||'<span class="contra-drop-hint">ARRASTE AS METADES PARA ESTA COLUNA</span>'}</section>`}
function contraSetInvModel(id){sepDraft.inv.selectedModel=id;render(true)}
function contraInvFinal(){let seq=sepState?.sequence08_visible;return `<section class="contra-final"><div class="k">PANI // CONSISTENCY ENGINE</div><h2>CINCO SUPORTES. UMA CLASSE DE CONTRADIÇÃO.</h2><div class="term">SECTOR PROOFS ................. 5/5\nCROSS-SUPPORT CONTRADICTION ... CONFIRMED\nCOMMON FAILURE DOMAIN .......... INFORMATION / RELATION\nGLYPH SEMANTICS ................ UNRESOLVED\nALPHABET MAPPING ............... NOT ATTEMPTED\n\nRESTORING: AD-06 // CORRELATION LAYER</div><blockquote>“Eu procurei significado cedo demais. O padrão vem antes da linguagem. Descobre primeiro o que muda — e o que continua igual.”<span>CAMADA RECUPERADA // A. DENA</span></blockquote>${seq?`<div class="contra-seq"><div class="k">SEQ-08 // RECURRENCE HIGH</div><div>${Array.from({length:8},(_,i)=>`<span>S-${String(i+1).padStart(2,'0')}</span>`).join('')}</div><p>STRUCTURE: STABLE // SEMANTICS: UNKNOWN // TRANSLATION: DEFERRED</p></div>`:'<p class="mut">SEQ-08 permanece retida até publicação do Diretor da Sessão.</p>'}</section>${sepControls('inv')}`}
function sepInv(){let k='inv';if(sepState?.inv_solved)return `${sepHeader(k)}${sepProgress()}${contraInvFinal()}`;let count=contraSolvedCount(),matrixReady=count===5||!!sepState?.matrix_open,matrixValidated=!!sepState?.matrix_validated;return `${sepHeader(k)}${sepProgress()}${contraMethod(k)}<p>As assinaturas publicadas pelos setores aparecem abaixo. Elas são conclusões estabilizadas, não respostas completas nem traduções.</p>${contraSignatureBoard()}${!matrixReady?`<section class="contra-waiting"><b>MATRIZ PARCIAL // ${count}/5</b><p>Aliya pode acompanhar o padrão emergente. A validação final exige cinco assinaturas ou liberação manual do Mestre.</p></section>`:matrixValidated?`<section class="contra-model-stage"><div class="k">SELEÇÃO DE MODELO // EXPLICAR SEM ADIVINHAR</div><p>Escolha o modelo que explica simultaneamente todas as linhas com o menor número de contradições.</p><div class="contra-models">${CONTRA_MODELS.map(([id,title,body])=>`<button class="${sepDraft.inv.selectedModel===id?'selected':''}" onclick="contraSetInvModel('${id}')"><b>${title}</b><span>${body}</span></button>`).join('')}</div><button id="sepsubmit" class="btn a contra-submit" onclick="sepSubmitInvModel()">TESTAR MODELO COMUM</button></section>`:`<section class="contra-matrix"><div class="k">MATRIZ DE CONTRAPROVA // REORGANIZE AS METADES</div><div class="contra-piece-pool">${contraInvPieces()}</div><div class="contra-matrix-grid">${contraInvColumn('physical','SUPORTE / ESTADO FÍSICO')}${contraInvColumn('relation','REGRA / REGISTRO / RELAÇÃO')}<section class="contra-missing-column"><div class="k">COLUNA AUSENTE</div><span>?</span></section></div><button id="sepsubmit" class="btn a contra-submit" onclick="sepSubmitInvMatrix()">VALIDAR MATRIZ</button></section>`}${sepControls(k)}`}
function sepSubmitInvMatrix(){return sepAttempt({module:'inv',stage:'matrix',assignments:sepDraft.inv.assignments})}
function sepSubmitInvModel(){if(!sepDraft.inv.selectedModel)return sepFeedback('Selecione um modelo para testar.',true);confirmBox('Estabilizar hipótese comum?','A PANI testará o modelo contra as cinco assinaturas. Nenhum Sinal será traduzido e nenhuma letra será atribuída.',()=>sepAttempt({module:'inv',stage:'model',model:sepDraft.inv.selectedModel}))}

function sepulcroPage(){let k=sectorKey(),body=k==='ops'?sepOps():k==='gen'?sepGen():k==='env'?sepEnv():k==='med'?sepMed():k==='sec'?sepSec():sepInv();return `<div class="card sep-page">${body}</div>`}
function sepFeedback(text,bad=false){let box=$('#sepfeedback');if(box){box.textContent=text;box.classList.toggle('sep-bad',bad)}toast(text,bad)}
async function sepulcroCrewRefresh(open=false){if(MASTER||!tok||!me)return sepState;try{sepState=await rpc(open?'pani_contraprova_open':'pani_contraprova_crew_state',{p_token:tok});return sepState}catch(error){console.error('contraprova state',error);return sepState}}
async function sepAttempt(payload){if(sepBusy)return null;let wait=sepCooldownUntil-Date.now();if(wait>0)return sepFeedback(`PANI // RECALIBRAÇÃO EM ${Math.ceil(wait/1000)}s`,true);sepBusy=true;sepCooldownUntil=Date.now()+2400;let button=$('#sepsubmit');if(button)button.disabled=true;try{let response=await rpc('pani_contraprova_attempt',{p_token:tok,p_payload:payload});await sepulcroCrewRefresh(false);if(response?.ok){if(response.matrix_validated)sepFeedback(response.message||'MATRIZ COERENTE');else if(response.resolved){contraResetDraft('inv');contraFinalSequence()}else{contraResetDraft(response.sector||sectorKey());sepFeedback(response.message||'CONTRAPROVA ESTABILIZADA')}render(true)}else{let message=response?.feedback||response?.message||'A hipótese mantém contradições não explicadas.';sepFeedback(message,true);if(response?.hint_offer)setTimeout(()=>sepFeedback(`${message}\n\nPANI: uma correlação assistida está disponível.`,true),50)}return response}catch(error){console.error(error);sepFeedback('PANI // FALHA AO VALIDAR A CONTRAPROVA',true);return null}finally{sepBusy=false;if(button)button.disabled=false}}
async function sepHint(){try{let response=await rpc('pani_contraprova_hint',{p_token:tok});await sepulcroCrewRefresh(false);if(response?.completed){contraResetDraft(response.sector||sectorKey());toast(response.message||'MÓDULO COMPLETADO COM ASSISTÊNCIA PANI');return render(true)}if(response?.ok)sepFeedback(`PANI // PISTA ${response.level}: ${response.hint}`);else sepFeedback(response?.message||'PISTA INDISPONÍVEL',true)}catch(error){sepFeedback('PANI // CORRELAÇÃO INDISPONÍVEL',true)}}
function contraFinalSequence(){if($('#contrafinaloverlay'))return;document.body.insertAdjacentHTML('beforeend',`<div id="contrafinaloverlay" class="contra-final-overlay"><div class="contra-final-noise"></div><div class="contra-final-core"><div class="k">PANI // CONSISTENCY ENGINE</div><h1>CINCO SUPORTES.</h1><h2>UMA CLASSE DE CONTRADIÇÃO.</h2><div id="contrafinalmsg" class="term">CROSS-SUPPORT MODEL: VALIDATING...</div></div></div>`);let overlay=$('#contrafinaloverlay');setTimeout(()=>{let x=$('#contrafinalmsg');if(x)x.textContent='COMMON FAILURE DOMAIN\nINFORMATION / RELATION'},1200);setTimeout(()=>{let x=$('#contrafinalmsg');if(x)x.textContent='GLYPH SEMANTICS: UNRESOLVED\nALPHABET MAPPING: NOT ATTEMPTED'},2600);setTimeout(()=>{overlay?.remove();render(true)},5000)}

/* MASTER */
function sepMasterProgressHTML(state){let crew=state?.crew||[];return `<div class="contra-master-summary"><div><span>ASSINATURAS</span><b>${state?.solved_count||0}/5</b></div><div><span>FASE</span><b>${state?.inv_solved?'RESOLVIDA':state?.matrix_open?'MATRIZ LIBERADA':'EVIDÊNCIAS'}</b></div><div><span>SINAIS</span><b>UNRESOLVED</b></div></div><table><tr><th>Tripulante</th><th>Setor</th><th>Estado</th><th>Contr.</th><th>Pista</th><th>Controle</th></tr>${crew.map(row=>{let done=!!state?.[row.sector+'_solved'],inv=row.sector==='inv',status=done?inv?'HIPÓTESE':'PUBLICADA':inv?`${state?.solved_count||0}/5 RECEBIDAS`:'PENDENTE';return `<tr><td>${esc(row.display_name)}</td><td>${String(row.sector).toUpperCase()}</td><td class="${done?'ok':'warn'}">${status}</td><td>${row.attempts||0}</td><td>${row.hint_level||0}/4</td><td><button class="btn" onclick="sepMasterSolve('${row.sector}')" ${done?'disabled':''}>${inv?'FORÇAR FINAL':'PUBLICAR'}</button><button class="btn" onclick="sepMasterHint('${row.sector}')">+ PISTA</button></td></tr>`}).join('')}</table>`}
async function sepMasterRefresh(){if(!MASTER||!pin)return sepMasterState;sepMasterState=await rpc('pani_contraprova_master_state',{p_pin:pin});return sepMasterState}
async function sepMasterAction(action,payload={}){sepMasterState=await rpc('pani_contraprova_master_action',{p_pin:pin,p_action:action,p_payload:payload});await mrefresh();return sepMasterState}
function sepMasterSolve(k){let label=k==='inv'?'Forçar hipótese final?':`Publicar assinatura ${String(k).toUpperCase()}?`,body=k==='inv'?'A matriz será marcada como resolvida sem traduzir Sinais ou estabelecer reciprocidade.':'Use este controle quando o jogador estiver ausente ou quando um problema técnico impedir a conclusão do módulo.';confirmBox(label,body,async()=>{try{await sepMasterAction('solve',{sector:k});toast(`MASTER // ${String(k).toUpperCase()} ATUALIZADO`)}catch(error){toast('Falha ao atualizar a contraprova.',true)}})}
async function sepMasterHint(k){try{await sepMasterAction('hint',{sector:k});toast(`PISTA ENVIADA // ${String(k).toUpperCase()}`)}catch(error){toast('Falha ao enviar pista.',true)}}
function sepMasterReset(){confirmBox('Resetar Protocolo Contraprova?','Assinaturas, matriz, pistas e contagens serão apagadas. Arquivos, relatórios, credenciais e transmissões permanecem intactos.',async()=>{try{await sepMasterAction('reset');toast('PROTOCOLO CONTRAPROVA RESETADO')}catch(error){toast('Falha ao resetar o protocolo.',true)}})}
function sepMasterArm(){let armed=!!sepMasterState?.alien_event_armed;confirmBox(armed?'Desarmar evento independente dos Alheios?':'Armar evento independente dos Alheios?',armed?'O alerta narrativo será encerrado sem alterar nenhuma assinatura ou hipótese da Contraprova.':'Este controle permanece como ferramenta narrativa do Mestre. O Protocolo Contraprova não aciona este evento automaticamente.',async()=>{try{await sepMasterAction(armed?'disarm_event':'arm_event');toast(armed?'EVENTO DOS ALHEIOS DESARMADO':'EVENTO DOS ALHEIOS ARMADO MANUALMENTE')}catch(error){toast('Falha ao alterar o evento.',true)}})}
async function sepMasterToggleAutoHint(){try{await sepMasterAction('auto_hint',{enabled:!sepMasterState?.auto_hint});toast(`AUTO-HINT ${sepMasterState?.auto_hint?'ATIVO':'INATIVO'}`)}catch(error){toast('Falha ao alterar auto-hint.',true)}}
async function sepMasterToggleMatrix(){try{await sepMasterAction('matrix',{open:!sepMasterState?.matrix_open});toast(`MATRIZ ${sepMasterState?.matrix_open?'LIBERADA':'RESTRITA'}`)}catch(error){toast('Falha ao alterar a matriz.',true)}}
async function sepMasterToggleSequence(){try{await sepMasterAction('sequence',{visible:!sepMasterState?.sequence08_visible});toast(`SEQ-08 ${sepMasterState?.sequence08_visible?'PUBLICADA':'OCULTA'}`)}catch(error){toast('Falha ao alterar a SEQ-08.',true)}}

setTimeout(()=>{if(typeof missionReportPage==='function'&&!missionReportPage.__station){let old=missionReportPage;missionReportPage=function(){return old().replaceAll('W77-02','W77-01')};missionReportPage.__station=true}if(!MASTER&&view==='sepulcro')render(true)},80);
