'use strict';
const SEP_META={
 ops:{title:'O RETORNO QUE NÃO EXISTE',docs:'TA-',checksum:'R¤S¤RVA',concepts:['c24','c22','c21','c25','c18']},
 gen:{title:'O CORPO E O REGISTRO',docs:'Genet',checksum:'T¤CIDO',concepts:['c20','c18','c16','c27','c06']},
 env:{title:'PARA BAIXO NÃO É UM LUGAR',docs:'Helena',checksum:'R¤F¤R¤NCIA',concepts:['c09','c19','c10','c22','c13']},
 med:{title:'O SINTOMA ANTES DO PACIENTE',docs:'Caio',checksum:'PR¤VISTO',concepts:['c27','c13','c19','c05','c16']},
 sec:{title:'A PORTA QUE NÃO ABRIU',docs:'RV',checksum:'D¤T¤CTADO',concepts:['c03','c25','c05','c09','c22']},
 inv:{title:'A PRIMEIRA LETRA',docs:'',checksum:'',concepts:[]}
};
const SEP_OBS=[45,135,225,315];
let sepDraft={concept:null,envRot:[0,0,0,0]},sepBusy=false,sepSequenceRunning=false;
function sepConceptStyle(asset){let m=/^c(\d{2})$/.exec(String(asset||''));if(!m)return '';let i=Number(m[1])-1,col=i%6,row=Math.floor(i/6),x=col*20,y=row*25,u='url("./tx-concept-sprite.webp?v=concept-v8")';return `-webkit-mask-image:${u};mask-image:${u};-webkit-mask-size:600% 500%;mask-size:600% 500%;-webkit-mask-position:${x}% ${y}%;mask-position:${x}% ${y}%;-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;`}
function sepConceptCard(k,i){return `<button type="button" class="sep-concept ${sepDraft.concept===k?'selected':''}" data-concept="${k}" aria-label="Sinal conceitual ${i+1}"><i style='${sepConceptStyle(k)}'></i><span>SINAL ${String(i+1).padStart(2,'0')}</span></button>`}
function sepConceptPicker(k){return `<div class="sep-concept-block"><div class="k">CHAVE DE SENTIDO // SELECIONE O SINAL</div><p class="mut small">Os rótulos foram removidos. Escolha o símbolo que representa a conclusão demonstrada.</p><div class="sep-concepts">${SEP_META[k].concepts.map((x,i)=>sepConceptCard(x,i)).join('')}</div></div>`}
function sepEGlyph(cls=''){let p=window.PANI_ALPHA_PATHS?.a05||'';return p?`<svg class="sep-e-glyph ${cls}" viewBox="0 0 128 128" aria-hidden="true"><path d="${p}" fill="currentColor" fill-rule="evenodd"/></svg>`:`<span class="sep-e-glyph sep-glyph-loading ${cls}">◇</span>`}
function sepWord(pattern){return pattern.split('¤').map((x,i)=>i?sepEGlyph('mini')+esc(x):esc(x)).join('')}
function sepChecksumBox(k){let done=!!sepState?.[k+'_solved'];if(!done||!SEP_META[k].checksum)return '';return `<div class="sep-reward"><div class="k">CHECKSUM RECUPERADO</div><div class="sep-checksum">${sepWord(SEP_META[k].checksum)}</div><p class="mut small">PANI preservou o mesmo caractere gráfico. Nenhum valor alfabético foi atribuído.</p></div>`}
function sepProgress(){return `<div class="sep-progress">${['ops','gen','env','med','sec'].map(k=>`<div class="${sepState[k+'_solved']?'done':''}"><b>${NL[k]}</b><span>${sepState[k+'_solved']?'RESTAURADO':'SEPULTADO'}</span></div>`).join('')}<div class="${sepState.inv_solved?'done':sepState.inv_available?'ready':'locked'}"><b>INV</b><span>${sepState.inv_solved?'CONCLUÍDO':sepState.inv_available?'DISPONÍVEL':'5/5 NECESSÁRIO'}</span></div></div>`}
function sepHeader(k){let done=!!sepState[k+'_solved'];return `<div class="sep-head"><div><div class="k">PANI // ACCESS RESTORATION // ${NL[k]}</div><h2>SEPULTURA-${NL[k]} // ${SEP_META[k].title}</h2><p class="mut">CREDENTIAL: VALID<br>SECTOR ENTRY: ${done?'RESTORED':'NOT FOUND'}<br>STATUS: ${done?'SEMANTIC PROOF ACCEPTED':'SEMANTIC BURIAL DETECTED'}</p></div><span class="sep-status ${done?'ok':'warn'}">${done?'ABERTO':'SEPULTADO'}</span></div>`}
function sepControls(k){return `<div class="sep-tools"><button class="btn" onclick="sepRelatedDocs('${k}')">ABRIR DOCUMENTOS RELACIONADOS</button><button class="btn" onclick="sepHint()">SOLICITAR CORRELAÇÃO PANI</button><span class="mut small">Tentativas registradas: ${sepState.attempts||0}</span></div><div id="sepfeedback" class="term sep-feedback">${esc(sepState.last_feedback||'PANI aguardando prova.')}</div>`}
function sepSolved(k){return `${sepHeader(k)}${sepProgress()}<div class="sep-restored"><b>✓ ACESSO RESTAURADO</b><p>A prova foi aceita e permanecerá registrada no backend da PANI.</p></div>${sepChecksumBox(k)}${sepControls(k)}`}
function sepSelectOptions(){return `<option value="">CLASSIFICAR...</option><option value="local_sufficient">LOCAL / SUFICIENTE</option><option value="local_insufficient">LOCAL / INSUFICIENTE</option><option value="absent">AUSENTE</option><option value="external">EXTERNO</option>`}
function sepOps(){let k='ops';if(sepState.ops_solved)return sepSolved(k);return `${sepHeader(k)}${sepProgress()}<p>Um caminho de retorno foi prometido. Um caminho de retorno não foi instalado. Classifique todos os nós e indique a origem da única capacidade que a equipe não controla.</p><div class="sep-nodegrid">${[['opmain','PROPULSÃO PRINCIPAL'],['opaux','PROPULSÃO AUXILIAR'],['oprp','RP-02'],['opplan','PLANO LOCAL DE RETORNO'],['oprec','RECUPERAÇÃO / SOCORRO'],['opauth','AUTORIDADE DE RETORNO']].map(x=>`<label>${x[1]}<select id="${x[0]}">${sepSelectOptions()}</select></label>`).join('')}</div>${sepConceptPicker(k)}<button id="sepsubmit" class="btn a" onclick="sepSubmitOps()">VALIDAR PROVA</button>${sepControls(k)}`}
function sepGen(){let k='gen';if(sepState.gen_solved)return sepSolved(k);let o='<option value="">IDENTIFICAR...</option><option value="morte">MORTE</option><option value="conhecimento">CONHECIMENTO</option><option value="sangue">SANGUE</option><option value="energia">ENERGIA</option>';return `${sepHeader(k)}${sepProgress()}<p>Reconstitua os quatro vetores a partir das descrições. Depois determine qual camada permaneceu verdadeira quando as leituras divergiram.</p><div class="sep-gen-grid"><label>H-01 // metabolismo reduzido; persistência estrutural<select id="gh01">${o}</select></label><label>H-02 // linguagem, padrões, geometrias e ordenação<select id="gh02">${o}</select></label><label>H-03 // expansão, vasculatura e agressividade material<select id="gh03">${o}</select></label><label>H-04 // oscilação térmica/bioelétrica e instabilidade<select id="gh04">${o}</select></label></div><div class="sep-readings"><div class="term">MESMA AMOSTRA // TRÊS LEITURAS\nLEITURA 1: A C G T  A C G T  A C G T\nLEITURA 2: A C G T  A ? G T  A C G T\nLEITURA 3: A C G T  A ? G T  A ? G T</div><div><label>FONTE VERDADEIRA<select id="gsource"><option value="">SELECIONE...</option><option value="objeto">OBJETO FÍSICO</option><option value="registro">REGISTRO DIGITAL</option><option value="impressao">IMPRESSÃO</option></select></label></div></div>${sepConceptPicker(k)}<button id="sepsubmit" class="btn a" onclick="sepSubmitGen()">VALIDAR PROVA</button>${sepControls(k)}`}
function sepEnvCard(i,name,rotation,dir){let r=sepDraft.envRot[i]||0,total=(SEP_OBS[i]+r)%360;return `<div class="sep-camera"><div><b>${name}</b><span>ROTAÇÃO INSTALADA ${rotation}°</span></div><div class="sep-arrow" style="transform:rotate(${r}deg)">↗</div><small>observado: ${dir} // normalizado: ${String(total).padStart(3,'0')}°</small><button class="btn" type="button" onclick="sepRotateCamera(${i})">GIRAR +90°</button></div>`}
function sepEnv(){let k='env';if(sepState.env_solved)return sepSolved(k);return `${sepHeader(k)}${sepProgress()}<p>As câmeras não compartilham o mesmo “cima”. Retire a câmera da equação até as quatro observações coincidirem na referência da estação.</p><div id="sepcameras" class="sep-cameras">${sepEnvCard(0,'CÂMERA 1',0,'NE')}${sepEnvCard(1,'CÂMERA 2',90,'SE')}${sepEnvCard(2,'CÂMERA 3',180,'SW')}${sepEnvCard(3,'CÂMERA 4',270,'NW')}</div><div id="sepconvergence" class="term">CONVERGÊNCIA LOCAL: ${sepLocalConvergence()}%</div><label>O QUE A EQUIPE REALMENTE ENCONTROU?<select id="efinding"><option value="">SELECIONE...</option><option value="luz">UMA LUZ</option><option value="gravidade">UMA GRAVIDADE</option><option value="organismo">UM ORGANISMO</option><option value="posicao">UMA POSIÇÃO / LUGAR</option></select></label>${sepConceptPicker(k)}<button id="sepsubmit" class="btn a" onclick="sepSubmitEnv()">VALIDAR PROVA</button>${sepControls(k)}`}
function sepTimeSelect(id){return `<select id="${id}"><option value="">ORDENAR...</option><option value="prediction_before">PREVISÃO → SINTOMA</option><option value="symptom_before">SINTOMA → PREVISÃO</option><option value="same_time">MESMO MOMENTO</option></select>`}
function sepMed(){let k='med';if(sepState.med_solved)return sepSolved(k);return `${sepHeader(k)}${sepProgress()}<p>O painel foi ordenado pelo momento em que Caio abriu os registros. Reconstrua a ordem causal usando metadata, não a ordem visual.</p><div class="sep-med-table"><div><b>QUEDA TÉRMICA</b>${sepTimeSelect('mthermal')}</div><div><b>REM SINCRONIZADO</b>${sepTimeSelect('mrem')}</div><div><b>DOR SEM LESÃO</b>${sepTimeSelect('mpain')}</div><div><b>FIXAÇÃO COGNITIVA</b>${sepTimeSelect('mfix')}</div><div class="anchor"><b>DESLOCAMENTO SEMÂNTICO / GRÁFICO</b><span class="warn">ainda não observado no momento da descoberta</span>${sepTimeSelect('msemantic')}</div></div>${sepConceptPicker(k)}<button id="sepsubmit" class="btn a" onclick="sepSubmitMed()">VALIDAR CRONOLOGIA</button>${sepControls(k)}`}
function sepSec(){let k='sec';if(sepState.sec_solved)return sepSolved(k);let tried=(sepState.attempts||0)>0;return `${sepHeader(k)}${sepProgress()}<p>Trace a entrada dos invasores respeitando o lockdown. Toda rota precisa ser demonstrável pelo Black Box.</p><div class="sep-lockmap"><div>EXT</div><div class="locked">A // LOCKED</div><div class="locked">SEC-C12 // LOCKED</div><div>INT</div><div class="locked">B // LOCKED</div><div class="locked">SEC // LOCKED</div></div><div class="actions"><button class="btn" onclick="sepTryRoute('a')">TESTAR ROTA EXT → A → C12 → INT</button><button class="btn" onclick="sepTryRoute('b')">TESTAR ROTA EXT → B → SEC → INT</button><button class="btn" onclick="sepTryRoute('x')">TESTAR ROTA ALTERNATIVA</button></div>${tried?`<div class="sep-hypothesis"><div class="k">HIPÓTESE DE FRONTEIRA LIBERADA</div><label><input id="sno" type="checkbox"> A incursão NÃO UTILIZOU PORTAS como fronteira obrigatória.</label></div>`:`<div class="term">PANI: prove ao menos uma rota antes de negar a premissa.</div>`}${sepConceptPicker(k)}<button id="sepsubmit" class="btn a" onclick="sepSubmitSec()" ${tried?'':'disabled'}>VALIDAR PROVA POR CONTRADIÇÃO</button>${sepControls(k)}`}
function sepInvChecksums(){return [['OPS','R¤S¤RVA'],['GEN','T¤CIDO'],['ENV','R¤F¤R¤NCIA'],['MED','PR¤VISTO'],['SEC','D¤T¤CTADO']].map(x=>`<div class="sep-inv-row"><b>${x[0]}</b><span>${sepWord(x[1])}</span></div>`).join('')}
function sepInv(){let k='inv';if(sepState.inv_solved)return `${sepHeader(k)}${sepProgress()}<div class="sep-restored reciprocity"><b>RECIPROCIDADE ESTABELECIDA</b><p>Um Sinal deixou de ser ruído e recebeu significado humano.</p></div><div class="sep-finaltoken">${sepConceptCard('c27',0).replace('SINAL 01','ENTENDIMENTO REGISTRADO')}</div>${sepControls(k)}`;if(!sepState.inv_available)return `${sepHeader(k)}${sepProgress()}<div class="sep-invlocked"><b>SEPULTURA-INV NÃO POSSUI ÍNDICE RESTAURÁVEL</b><p>As cinco provas setoriais precisam ser concluídas. Progresso atual: ${sepSolvedCount()}/5.</p></div>${sepControls(k)}`;return `${sepHeader(k)}${sepProgress()}<p>Cinco setores devolveram o mesmo caractere em palavras diferentes. Proponha UMA letra que restaure todos os checksums sem exceção.</p><div class="sep-inv-list">${sepInvChecksums()}</div><div class="sep-alpha-hyp"><div>${sepEGlyph('large')}</div><label>VALOR PROPOSTO<input id="sepLetter" maxlength="1" autocomplete="off" spellcheck="false" placeholder="_"></label></div><div class="alert">WARNING: SEMANTIC ASSIGNMENT WILL BE PERSISTENT.</div><button class="btn r" onclick="sepConfirmInv()">CONFIRMAR HIPÓTESE</button>${sepControls(k)}`}
function sepulcroPage(){let k=sectorKey();let body=k==='ops'?sepOps():k==='gen'?sepGen():k==='env'?sepEnv():k==='med'?sepMed():k==='sec'?sepSec():sepInv();setTimeout(sepBindConcepts,0);return `<div class="card sep-page">${body}</div>`}
function sepBindConcepts(){document.querySelectorAll('.sep-concept[data-concept]').forEach(b=>{b.onclick=()=>{sepDraft.concept=b.dataset.concept;document.querySelectorAll('.sep-concept').forEach(x=>x.classList.toggle('selected',x.dataset.concept===sepDraft.concept))}})}
function sepFeedback(t,bad=false){let e=$('#sepfeedback');if(e){e.textContent=t;e.classList.toggle('sep-bad',bad)}toast(t,bad)}
async function sepulcroCrewRefresh(open=false){if(MASTER||!tok||!me)return sepState;try{sepState=await rpc(open?'pani_sepulcro_open':'pani_sepulcro_crew_state',{p_token:tok});return sepState}catch(e){console.error('sepulcro state',e);return sepState}}
async function sepAttempt(payload){if(sepBusy)return null;sepBusy=true;let b=$('#sepsubmit');if(b)b.disabled=true;try{let r=await rpc('pani_sepulcro_attempt',{p_token:tok,p_payload:payload});await sepulcroCrewRefresh(false);if(r?.ok){sepDraft={concept:null,envRot:[0,0,0,0]};sepFeedback(r.message||'PROVA ACEITA');render(true)}else{sepFeedback(r.feedback||r.message||'PROVA INCONSISTENTE',true);if(r.convergence!=null){let c=$('#sepconvergence');if(c)c.textContent='CONVERGÊNCIA VALIDADA PELA PANI: '+r.convergence+'%'}if(r.route_failed)render(true)}return r}catch(e){console.error(e);sepFeedback('PANI // FALHA AO VALIDAR A PROVA',true);return null}finally{sepBusy=false;if(b)b.disabled=false}}
function sepSubmitOps(){return sepAttempt({prop_main:$('#opmain').value,prop_aux:$('#opaux').value,rp02:$('#oprp').value,local_plan:$('#opplan').value,recovery:$('#oprec').value,authority:$('#opauth').value,concept:sepDraft.concept})}
function sepSubmitGen(){return sepAttempt({h01:$('#gh01').value,h02:$('#gh02').value,h03:$('#gh03').value,h04:$('#gh04').value,source:$('#gsource').value,concept:sepDraft.concept})}
function sepRotateCamera(i){sepDraft.envRot[i]=(sepDraft.envRot[i]+90)%360;let c=$('#sepcameras');if(c)c.innerHTML=sepEnvCard(0,'CÂMERA 1',0,'NE')+sepEnvCard(1,'CÂMERA 2',90,'SE')+sepEnvCard(2,'CÂMERA 3',180,'SW')+sepEnvCard(3,'CÂMERA 4',270,'NW');let x=$('#sepconvergence');if(x)x.textContent='CONVERGÊNCIA LOCAL: '+sepLocalConvergence()+'%'}
function sepLocalConvergence(){let target=[0,270,180,90];return target.reduce((n,x,i)=>n+(sepDraft.envRot[i]===x?25:0),0)}
function sepSubmitEnv(){return sepAttempt({r1:sepDraft.envRot[0],r2:sepDraft.envRot[1],r3:sepDraft.envRot[2],r4:sepDraft.envRot[3],finding:$('#efinding').value,concept:sepDraft.concept})}
function sepSubmitMed(){return sepAttempt({thermal:$('#mthermal').value,rem:$('#mrem').value,pain:$('#mpain').value,fixation:$('#mfix').value,semantic:$('#msemantic').value,concept:sepDraft.concept})}
function sepTryRoute(route){return sepAttempt({action:'route',route})}
function sepSubmitSec(){return sepAttempt({hypothesis:$('#sno')?.checked?'no_doors':'',concept:sepDraft.concept})}
function sepConfirmInv(){let l=($('#sepLetter')?.value||'').trim();if(!l)return sepFeedback('Informe uma hipótese alfabética.',true);confirmBox('Confirmar hipótese alfabética?','A atribuição será persistente em todas as reconstruções futuras. Confirmar não é apenas traduzir: é declarar que este símbolo significa alguma coisa para nós.',async()=>{let r=await sepAttempt({letter:l});if(r?.ok)sepReciprocitySequence()})}
async function sepHint(){try{let r=await rpc('pani_sepulcro_hint',{p_token:tok});if(r.ok)sepFeedback(`PANI // PISTA ${r.level}: ${r.hint}`);else{let m=Math.ceil(Number(r.available_in||0)/60);sepFeedback(`${r.message||'PISTA INDISPONÍVEL'}${m>0?' // '+m+' min':''}`,true)}await sepulcroCrewRefresh(false)}catch(e){sepFeedback('PANI // CORRELAÇÃO INDISPONÍVEL',true)}}
function sepRelatedDocs(k){view='files';render(true);setTimeout(()=>{let q=SEP_META[k]?.docs||'';let e=$('#pfsearch');if(e&&q){e.value=q;if(typeof paniFileSearch==='function')paniFileSearch(q)}},80)}
function sepReciprocitySequence(){if(sepSequenceRunning)return;sepSequenceRunning=true;let o=$('#sepreciprocity');if(!o){document.body.insertAdjacentHTML('beforeend',`<div id="sepreciprocity" class="sep-recip-overlay hidden"><div class="sep-recip-noise"></div><div class="sep-recip-core"><div class="k">PANI // CORRELAÇÃO SEMÂNTICA</div><h1 id="seprectitle">HIPÓTESE CONFIRMADA</h1><div id="seprecglyph"></div><div id="seprecmsg" class="term"></div></div></div>`);o=$('#sepreciprocity')}o.classList.remove('hidden');$('#seprecglyph').innerHTML=sepEGlyph('huge');$('#seprecmsg').textContent='VALOR ATRIBUÍDO: E\nCONFIDENCE: 100.0%\nRECIPROCITY: ESTABLISHED';setTimeout(()=>{$('#seprecmsg').textContent='NOVO SINAL EXTERNO.'},1500);setTimeout(()=>{$('#seprecmsg').textContent='NÃO.\nCORREÇÃO.\nO SINAL JÁ ESTAVA PRESENTE.'},2600);setTimeout(()=>{$('#seprecmsg').textContent='ELE RESPONDEU.\n\nPROXIMITY WARNING // MOVEMENT INTERNAL DETECTED'},3900);setTimeout(()=>{o.classList.add('hidden');sepSequenceRunning=false},7200)}
function sepMasterProgressHTML(s){let crew=s?.crew||[];return `<table><tr><th>Tripulante</th><th>Setor</th><th>Estado</th><th>Tent.</th><th>Controle</th></tr>${crew.map(r=>{let done=!!s[r.sector+'_solved'];let locked=r.sector==='inv'&&!s.inv_available&&!s.inv_solved;return `<tr><td>${esc(r.display_name)}</td><td>${String(r.sector).toUpperCase()}</td><td class="${done?'ok':locked?'mut':'warn'}">${done?'RESTAURADO':locked?'BLOQUEADO':'SEPULTADO'}</td><td>${r.attempts||0}</td><td><button class="btn" onclick="sepMasterSolve('${r.sector}')" ${done?'disabled':''}>SOLVE</button></td></tr>`}).join('')}</table>`}
async function sepMasterRefresh(){if(!MASTER||!pin)return sepMasterState;sepMasterState=await rpc('pani_sepulcro_master_state',{p_pin:pin});return sepMasterState}
async function sepMasterSolve(k){try{sepMasterState=await rpc('pani_sepulcro_master_action',{p_pin:pin,p_action:'solve',p_payload:{sector:k}});await mrefresh();toast(`MASTER // ${String(k).toUpperCase()} RESTAURADO`)}catch(e){toast('Falha ao restaurar setor.',true)}}
async function sepMasterReset(){confirmBox('Resetar Protocolo Sepulcro?','As seis portas semânticas, tentativas, pistas e a primeira associação alfabética serão apagadas. Relatórios e arquivos permanecem intactos.',async()=>{try{sepMasterState=await rpc('pani_sepulcro_master_action',{p_pin:pin,p_action:'reset',p_payload:{}});await mrefresh();toast('PROTOCOLO SEPULCRO RESETADO')}catch(e){toast('Falha ao resetar Sepulcro.',true)}})}
async function sepMasterArm(){confirmBox('Armar evento dos Alheios?','Isso ativa manualmente o sinal externo, alerta de proximidade e movimento interno, sem exigir a resolução da letra.',async()=>{try{sepMasterState=await rpc('pani_sepulcro_master_action',{p_pin:pin,p_action:'arm_event',p_payload:{}});await mrefresh();toast('EVENTO DOS ALHEIOS ARMADO')}catch(e){toast('Falha ao armar evento.',true)}})}
const sepMissionReportPage=typeof missionReportPage==='function'?missionReportPage:null;
setTimeout(()=>{if(typeof missionReportPage==='function'&&!missionReportPage.__station){let old=missionReportPage;missionReportPage=function(){return old().replaceAll('W77-02','W77-01')};missionReportPage.__station=true}if(!MASTER&&view==='sepulcro')render(true)},80);
